USE FASTMONEYPRO_ACCOUNT
GO
--EXEC FASTMONEYPRO_ACCOUNT.DBO.PROC_AGENT_CASH_COLLECTION @FLAG ='search',@USER ='admin',@FROM_DATE ='2019-10-09',@TO_DATE ='2019-10-11'

ALTER PROC PROC_AGENT_CASH_COLLECTION
(
	@FLAG VARCHAR(20)
	,@USER VARCHAR(50) = NULL
	,@FROM_DATE VARCHAR(20) = NULL
	,@TO_DATE VARCHAR(20) = NULL
	,@AGENT_ID VARCHAR(30) = NULL
	,@TYPE CHAR(1) = NULL
)	
AS;
SET NOCOUNT ON;
SET XACT_ABORT ON;
BEGIN
	IF @FLAG = 'SEARCH'
	BEGIN
		CREATE TABLE #TEMP_RPT(AGENT_ID INT, AGENT_NAME VARCHAR(100), REFERRAL_CODE VARCHAR(20), REFERRAL_NAME VARCHAR(100), ACCT_NUM VARCHAR(30), CASH_COLLECTED MONEY)

		IF EXISTS(SELECT * FROM FASTMONEYPRO_REMIT.DBO.APPLICATIONUSERS(NOLOCK) WHERE USERNAME = @USER AND USERTYPE = 'A')
		BEGIN
			INSERT INTO #TEMP_RPT(AGENT_ID, AGENT_NAME, REFERRAL_CODE, REFERRAL_NAME, ACCT_NUM)
			SELECT AM.AGENTID, AM.AGENTNAME, R.REFERRAL_CODE, R.REFERRAL_NAME, AC.ACCT_NUM 
			FROM FASTMONEYPRO_REMIT.DBO.REFERRAL_AGENT_WISE R(NOLOCK)
			INNER JOIN FASTMONEYPRO_REMIT.DBO.AGENTMASTER AM(NOLOCK) ON AM.AGENTID = R.BRANCH_ID 
			INNER JOIN AC_MASTER AC(NOLOCK) ON AC.AGENT_ID = R.ROW_ID AND AC.ACCT_RPT_CODE = 'RA'
			WHERE R.AGENT_ID = 0
			AND R.BRANCH_ID = @AGENT_ID
		END
		ELSE
		BEGIN
			INSERT INTO #TEMP_RPT(AGENT_ID, AGENT_NAME, REFERRAL_CODE, REFERRAL_NAME, ACCT_NUM)
			SELECT AM.AGENTID, AM.AGENTNAME, R.REFERRAL_CODE, R.REFERRAL_NAME, AC.ACCT_NUM 
			FROM FASTMONEYPRO_REMIT.DBO.REFERRAL_AGENT_WISE R(NOLOCK)
			INNER JOIN FASTMONEYPRO_REMIT.DBO.AGENTMASTER AM(NOLOCK) ON AM.AGENTID = R.BRANCH_ID 
			INNER JOIN AC_MASTER AC(NOLOCK) ON AC.AGENT_ID = R.ROW_ID AND AC.ACCT_RPT_CODE = 'RA'
			WHERE R.AGENT_ID = 0

			INSERT INTO #TEMP_RPT(AGENT_ID, AGENT_NAME, REFERRAL_CODE, REFERRAL_NAME, ACCT_NUM)
			SELECT A.AGENT_ID, A.ACCT_NAME, '', A.ACCT_NAME, A.ACCT_NUM
			FROM FASTMONEYPRO_REMIT.DBO.AGENTMASTER AM(NOLOCK) 
			INNER JOIN FASTMONEYPRO_REMIT.DBO.APPLICATIONUSERS AU(NOLOCK) ON AU.AGENTID = AM.AGENTID
			INNER JOIN AC_MASTER A(NOLOCK) ON A.AGENT_ID = AU.USERID AND A.ACCT_RPT_CODE = 'TCA'
			WHERE ACTASBRANCH = 'N'
			AND PARENTID = 393877
		END

		SELECT ACCT_NUM = T.ACC_NUM, SUM(TRAN_AMT) TRAN_AMT
		INTO #CASH_COLLECT
		FROM #TEMP_RPT A(NOLOCK)
		INNER JOIN FASTMONEYPRO_ACCOUNT.DBO.TRAN_MASTER T(NOLOCK) ON A.ACCT_NUM = T.ACC_NUM
		WHERE T.tran_date BETWEEN @FROM_DATE AND @TO_DATE + ' 23:59:59'
		AND PART_TRAN_TYPE = 'CR'
		AND ISNULL(FIELD2, '') <> 'REMITTANCE VOUCHER'
		GROUP BY ACC_NUM

		UPDATE R SET R.CASH_COLLECTED = C.TRAN_AMT 
		FROM #TEMP_RPT R
		INNER JOIN #CASH_COLLECT C ON C.ACCT_NUM = R.ACCT_NUM

		SELECT DISTINCT AGENT_ID, AGENT_NAME 
		FROM #TEMP_RPT
		ORDER BY AGENT_NAME

		SELECT AGENT_ID,
				 AGENT_NAME,
				 REFERRAL_CODE,
				 REFERRAL_NAME,
				 ACCT_NUM,
				 CASH_COLLECTED
		FROM #TEMP_RPT
		WHERE CASH_COLLECTED <> 0
		ORDER BY AGENT_NAME ASC
	END
	ELSE IF @FLAG = 'drill-down'
	BEGIN	
		CREATE TABLE #TEMP_RPT_DRILL_DOWN(AGENT_ID INT, AGENT_NAME VARCHAR(100), REFERRAL_CODE VARCHAR(20), REFERRAL_NAME VARCHAR(100), NARRATION VARCHAR(200), TRAN_DATE VARCHAR(20), ACCT_NUM VARCHAR(30), CASH_COLLECTED MONEY)

		DECLARE @ACC_NUM VARCHAR(30)
		IF @TYPE = 'A'
		BEGIN	
			SELECT @ACC_NUM = A.ACCT_NUM
			from AC_MASTER A(NOLOCK) 
			WHERE A.AGENT_ID = @AGENT_ID
			AND A.ACCT_RPT_CODE = 'TCA'
		END
		ELSE
		BEGIN
			SELECT @ACC_NUM = AC.ACCT_NUM 
			FROM FASTMONEYPRO_REMIT.DBO.REFERRAL_AGENT_WISE R(NOLOCK)
			INNER JOIN FASTMONEYPRO_REMIT.DBO.AGENTMASTER AM(NOLOCK) ON AM.AGENTID = R.BRANCH_ID 
			INNER JOIN AC_MASTER AC(NOLOCK) ON AC.AGENT_ID = R.ROW_ID AND AC.ACCT_RPT_CODE = 'RA'
			WHERE R.AGENT_ID = 0
			AND R.REFERRAL_CODE = @AGENT_ID
		END
		
		SELECT T.ACC_NUM, T.TRAN_AMT, convert(varchar, TRAN_DATE, 23) TRAN_DATE, TRAN_PARTICULAR
		FROM FASTMONEYPRO_ACCOUNT.DBO.TRAN_MASTER T(NOLOCK) 
		INNER JOIN FASTMONEYPRO_ACCOUNT.DBO.TRAN_MASTERDETAIL D(NOLOCK) ON D.REF_NUM = T.REF_NUM
		WHERE T.tran_date BETWEEN @FROM_DATE AND @TO_DATE + ' 23:59:59'
		AND PART_TRAN_TYPE = 'CR'
		AND ISNULL(FIELD2, '') <> 'REMITTANCE VOUCHER'
		AND T.ACC_NUM = @ACC_NUM
	END
END
--EXEC FASTMONEYPRO_ACCOUNT.DBO.PROC_AGENT_CASH_COLLECTION @FLAG ='drill-down',@USER ='admin',@FROM_DATE ='2019-09-01',@TO_DATE ='2019-10-11',@AGENT_ID ='52791',@TYPE ='A'



