
CREATE PROCEDURE PROC_VAULT_TRANSFER_ACC
(
	@USER VARCHAR(50) 
	,@ROW_ID INT 
)
AS;
SET NOCOUNT ON;
SET XACT_ABORT ON;
BEGIN
	DECLARE @sessionId	VARCHAR(50)	= NEWID()

	SELECT * 
	FROM BRANCH_CASH_IN_OUT(NOLOCK) 
	WHERE rowId = @ROW_ID
END