CREATE TABLE AGENT_BRANCH_RUNNING_BALANCE
(
	ROW_ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY
	,B_ID INT NOT NULL
	,B_TYPE CHAR(1)			--A: AGENT BALANCE(AGENTMASTER(ACTASBRANCH='N')), B: BRANCH BALANCE(AGENTMASTER(ACTASBRANCH='Y')), U: USER BALANCE(APPLICATIONUSERS(USERTYPE='A')), R: REFERRAL BALANCE(REFERRAL_AGENT_WISE)
	,B_NAME VARCHAR(100) NOT NULL
	,TODAY_SEND MONEY 
	,TODAY_CANCEL MONEY
	,PREVIOUS_SEND MONEY
	,PREVIOUS_CANCEL MONEY
)

--ACTASBRANCH = NO i.e agents
INSERT INTO AGENT_BRANCH_RUNNING_BALANCE
SELECT agentId,'A',agentName,0,0,0,0
from agentmaster WHERE AGENTTYPE=2903 AND ACTASBRANCH = 'N' AND PARENTID = '393877'

--ACTASBRANCH = YES i.e agents but it acts as branch
INSERT INTO AGENT_BRANCH_RUNNING_BALANCE
SELECT agentId,'B',agentName,0,0,0,0
from agentmaster WHERE AGENTTYPE=2903 AND ACTASBRANCH = 'Y' AND PARENTID = '393877'

--SHIKSHYA i.e user
INSERT INTO AGENT_BRANCH_RUNNING_BALANCE
SELECT userId,'U',userName,0,0,0,0
from APPLICATIONUSERS WHERE userid = '52766'


 --DEEPMALA i.e user
INSERT INTO AGENT_BRANCH_RUNNING_BALANCE
SELECT userId,'U',userName,0,0,0,0
from APPLICATIONUSERS WHERE userid = '52772'

--suja i.e referral
INSERT INTO AGENT_BRANCH_RUNNING_BALANCE 
SELECT ROW_ID,'R',REFERRAL_NAME,0,0,0,0 FROM dbo.REFERRAL_AGENT_WISE
WHERE ROW_ID = 1


SELECT * FROM AGENT_BRANCH_RUNNING_BALANCE
