alter TABLE TBLCUSTOMERMODIFYLOGS ALTER COLUMN NEWVALUE NVARCHAR(300)
alter TABLE TBLCUSTOMERMODIFYLOGS ALTER COLUMN OLDVALUE NVARCHAR(300)

ALTER TABLE dbo.TBLCUSTOMERMODIFYLOGS ADD amendmentId VARCHAR(MAX)

