ALTER TABLE API_BANK_LIST ADD JME_BANK_CODE VARCHAR(10)

CREATE TABLE API_BANK_LIST_MASTER
(
	MASTER_BANK_ID BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY
	,BANK_NAME VARCHAR(150) NOT NULL 
	,JME_BANK_CODE VARCHAR(30) NULL
	,BANK_STATE VARCHAR(100) NULL
	,BANK_DISTRICT VARCHAR(100) NULL
	,BANK_ADDRESS NVARCHAR(250) NULL
	,BANK_PHONE NVARCHAR(50) NULL
	,BANK_EMAIL NVARCHAR(150) NULL
	,SUPPORT_CURRENCY VARCHAR(5) NULL
	,BANK_COUNTRY VARCHAR(45) NOT NULL
	,PAYMENT_TYPE_ID INT NOT NULL
	,IS_ACTIVE BIT NOT NULL
);

CREATE TABLE API_BANK_LIST_MASTER_TMP
(
	MASTER_BANK_ID BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY
	,BANK_NAME VARCHAR(150) NOT NULL 
	,TMP_BANK_ID INT NULL
	,PARTNER_ID INT NULL
	,JME_BANK_CODE VARCHAR(30) NULL
	,BANK_STATE VARCHAR(100) NULL
	,BANK_DISTRICT VARCHAR(100) NULL
	,BANK_ADDRESS NVARCHAR(250) NULL
	,BANK_PHONE NVARCHAR(50) NULL
	,BANK_EMAIL NVARCHAR(150) NULL
	,SUPPORT_CURRENCY VARCHAR(5) NULL
	,BANK_COUNTRY VARCHAR(45) NOT NULL
	,PAYMENT_TYPE_ID INT NOT NULL
	,IS_ACTIVE BIT NOT NULL
);

CREATE TABLE API_BANK_LIST_TMP
(
	ROW_ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY
	,SESSION_ID VARCHAR(50) NULL
	,MASTER_BANK_ID BIGINT NULL
	,API_PARTNER_ID INT NOT NULL				
	,BANK_NAME VARCHAR(150) NOT NULL 
	,BANK_CODE1 VARCHAR(100) NULL
	,BANK_CODE2 VARCHAR(100) NULL
	,BANK_STATE VARCHAR(100) NULL
	,BANK_DISTRICT VARCHAR(100) NULL
	,BANK_ADDRESS NVARCHAR(250) NULL
	,BANK_PHONE NVARCHAR(50) NULL
	,BANK_EMAIL NVARCHAR(150) NULL
	,SUPPORT_CURRENCY VARCHAR(5) NULL
	,BANK_COUNTRY VARCHAR(45) NOT NULL
	,PAYMENT_TYPE_ID INT NOT NULL
	,IS_ACTIVE BIT NOT NULL
);

select * from API_BANK_LIST_MASTER
WHERE BANK_NAME LIKE '%Biratlaxmi%'

SELECT * FROM API_BANK_LIST_TMP 
WHERE BANK_NAME LIKE '%Biratlaxmi%'


select * from API_BANK_LIST where bank_country = 'Nepal' and payment_type_id = 2

INSERT INTO API_BANK_LIST_MASTER(BANK_NAME,BANK_CODE1, SUPPORT_CURRENCY, BANK_COUNTRY, PAYMENT_TYPE_ID, IS_ACTIVE)
SELECT BANK_NAME,BANK_CODE1, SUPPORT_CURRENCY, BANK_COUNTRY, PAYMENT_TYPE_ID, IS_ACTIVE FROM API_BANK_LIST where bank_country = 'Nepal' and payment_type_id = 2

EXEC PROC_MAP_BANK_DATA @flag = 'MASTER-DATA', @user = null, @COUNTRY_CODE = 'NP', @PAYMENT_TYPE_ID = '2', @API_PARTNER_ID  = '394130'

