--ALTER TABLE API_CITY_LIST ALTER COLUMN STATE_ID VARCHAR(20)
--ALTER TABLE dbo.API_BANK_BRANCH_LIST ADD PAYMENT_TYPE_ID INT NULL
CREATE TABLE API_BANK_LIST 
(
	BANK_ID BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY
	,MASTER_BANK_ID BIGINT NULL
	,API_PARTNER_ID INT NOT NULL				
	,BANK_NAME VARCHAR(150) NOT NULL 
	,BANK_CODE1 VARCHAR(100) NULL
	,BANK_CODE2 VARCHAR(100) NULL
	,BANK_STATE VARCHAR(100) NULL
	,BANK_DISTRICT VARCHAR(100) NULL
	,BANK_ADDRESS NVARCHAR(250) NULL
	,BANK_PHONE NVARCHAR(50) NULL
	,BANK_EMAIL NVARCHAR(150) NULL
	,SUPPORT_CURRENCY VARCHAR(5) NULL
	,BANK_COUNTRY VARCHAR(45) NOT NULL
	,PAYMENT_TYPE_ID INT NOT NULL
	,IS_ACTIVE BIT NOT NULL
);
ALTER TABLE API_BANK_LIST ADD MASTER_BANK_ID BIGINT NULL

CREATE TABLE API_BANK_BRANCH_LIST
(
	BRANCH_ID BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY
	,BANK_ID BIGINT NOT NULL				
	,BRANCH_NAME VARCHAR(150) NOT NULL 
	,BRANCH_CODE1 VARCHAR(100) NULL
	,BRANCH_CODE2 VARCHAR(100) NULL
	,BRANCH_STATE VARCHAR(100) NULL
	,BRANCH_DISTRICT VARCHAR(100) NULL
	,BRANCH_ADDRESS NVARCHAR(250) NULL
	,BRANCH_PHONE NVARCHAR(50) NULL
	,BRANCH_EMAIL NVARCHAR(150) NULL
	,PAYMENT_TYPE_ID INT NOT NULL
	,BRANCH_COUNTRY VARCHAR(45) NOT NULL
	,IS_ACTIVE BIT NOT NULL
);

CREATE TABLE API_STATE_LIST
(
	STATE_ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY
	,API_PARTNER_ID INT NOT NULL
	,STATE_NAME VARCHAR(100) NOT NULL
	,STATE_CODE VARCHAR(20) NULL
	,STATE_COUNTRY VARCHAR(45) NOT NULL
	,PAYMENT_TYPE_ID INT NULL
	,IS_ACTIVE BIT NOT NULL
);

CREATE TABLE API_CITY_LIST
(
	CITY_ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY
	,STATE_ID INT NULL
	,CITY_NAME VARCHAR(100) NOT NULL
	,CITY_CODE VARCHAR(20) NULL
	,CITY_COUNTRY VARCHAR(45) NOT NULL
	,PAYMENT_TYPE_ID INT NULL
	,IS_ACTIVE BIT NOT NULL
);

CREATE TABLE API_TOWN_LIST
(
	TOWN_ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY
	,STATE_ID INT NULL
	,CITY_ID INT NULL
	,TOWN_NAME VARCHAR(100) NOT NULL
	,TOWN_CODE VARCHAR(20) NULL
	,TOWN_COUNTRY VARCHAR(45) NOT NULL
	,PAYMENT_TYPE_ID INT NULL
	,IS_ACTIVE BIT NOT NULL
);


ALTER TABLE dbo.API_BANK_LIST ALTER COLUMN BANK_NAME NVARCHAR(200)