
CREATE TABLE BANK_GUARENTEE
(
	rowId INT NOT NULL IDENTITY(1,1) PRIMARY KEY
	,[date] DATETIME NOT NULL
	,depositAmount MONEY NOT NULL
	,holdRate DECIMAL(10,2) NOT NULL
	,pendingAmount	MONEY NOT NULL
);

--INSERT INTO BANK_GUARENTEE
--SELECT dateadd(day, -1, GETDATE()), 100000, 5, 100000

SELECT * FROM BANK_GUARENTEE
