
USE FastMoneyPro_Account

CREATE TABLE CASH_ACCOUNT_LIST
(
	ROW_ID INT NOT NULL IDENTITY(1, 1) PRIMARY KEY
	,ACC_NUM VARCHAR(30) NOT NULL
	,ACC_NAME VARCHAR(150) NOT NULL
	,GL_CODE INT
)

CREATE TABLE CASH_IN_OUT_HISTORY
(
	ROW_ID BIGINT NOT NULL IDENTITY(1, 1) PRIMARY KEY
	,IN_AMOUNT MONEY NOT NULL
	,OUT_AMOUNT MONEY NOT NULL
	,IN_ACCOUNT VARCHAR(30) NOT NULL
	,OUT_ACCOUNT VARCHAR(30) NOT NULL
	,TRAN_DATE DATETIME NOT NULL
	,REFERENCE_ID BIGINT NOT NULL
	,REFERENCE_TABLE VARCHAR(50) NOT NULL
	,NARRATION NVARCHAR(250) NOT NULL
)

INSERT INTO CASH_ACCOUNT_LIST
SELECT ACCT_NUM, ACCT_NAME, GL_CODE FROM AC_MASTER WHERE GL_CODE = 119 UNION ALL
SELECT ACCT_NUM, ACCT_NAME, GL_CODE FROM AC_MASTER WHERE GL_CODE = 122 UNION ALL
SELECT ACCT_NUM, ACCT_NAME, GL_CODE FROM AC_MASTER WHERE GL_CODE = 120 UNION ALL
SELECT ACCT_NUM, ACCT_NAME, GL_CODE FROM AC_MASTER WHERE GL_CODE = 121 UNION ALL
SELECT ACCT_NUM, ACCT_NAME, GL_CODE FROM AC_MASTER WHERE GL_CODE = 127 UNION ALL
SELECT ACCT_NUM, ACCT_NAME, GL_CODE FROM AC_MASTER WHERE GL_CODE = 118 UNION ALL
SELECT ACCT_NUM, ACCT_NAME, GL_CODE FROM AC_MASTER WHERE GL_CODE = 22 UNION ALL
SELECT ACCT_NUM, ACCT_NAME, GL_CODE FROM AC_MASTER WHERE GL_CODE = 126 

SELECT * FROM AC_MASTER WHERE ACCT_NUM = '121901714'

SELECT * FROM AC_MASTER WHERE GL_CODE = 126

