
CREATE TABLE API_BANK_BRANCH_LIST_LOG
 (
	ROW_ID INT IDENTITY(1,1)
	,BANK_ID BIGINT NOT NULL
	,BRANCH_ID BIGINT NOT NULL
	,OLD_BRANCH_CODE1 BIGINT NULL
	,NEW_BRANCH_CODE1 BIGINT NULL
	,MODIFIED_BY VARCHAR(30) NULL
	,MODIFIED_DATE DATETIME NULL
)