CREATE TABLE API_PAYOUT_LOACTION
(
    [Id] [BIGINT] IDENTITY(1,1) NOT NULL,
	[PAYOUT_NAME] VARCHAR(250) NULL,
	[PAYOUT_CODE] VARCHAR(10) NULL,
	[BANK_ID] VARCHAR(500) NULL,
	[BANK_NAME] VARCHAR(500) NULL,
	[NEED_BANK] BIT,
	PRIMARY KEY CLUSTERED
	(
	[Id] ASC
	) WITH (PAD_INDEX=OFF,STATISTICS_NORECOMPUTE=OFF, IGNORE_DUP_KEY=OFF,ALLOW_ROW_LOCKS=ON, ALLOW_PAGE_LOCKS=ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE API_PAYOUT_BRANCH_LOACTION
(
    [Id] [BIGINT] IDENTITY(1,1) NOT NULL,
	[PAYOUT_ID] VARCHAR(10) NULL,
	[BRANCH_CODE] VARCHAR(10) NULL,
	[BRANCH_NAME] VARCHAR(250) NULL,
	[BRANCH_ADDRESS] VARCHAR(500) NULL,
	[NEED_BANK] BIT,
	[CITY_ID] BIGINT,
	PRIMARY KEY CLUSTERED
	(
	[Id] ASC
	) WITH (PAD_INDEX=OFF,STATISTICS_NORECOMPUTE=OFF, IGNORE_DUP_KEY=OFF,ALLOW_ROW_LOCKS=ON, ALLOW_PAGE_LOCKS=ON) ON [PRIMARY]
) ON [PRIMARY]
GO

--DROP TABLE dbo.API_PAYOUT_LOACTION
--DROP TABLE dbo.API_PAYOUT_BRANCH_LOACTION