CREATE TABLE CUSTOMER_DEPOSIT_LOGS
(
	tranId BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY 
	,tranDate DATETIME NOT NULL
	,depositAmount MONEY NOT NULL
	,paymentAmount MONEY NOT NULL
	,particulars NVARCHAR(500) NOT NULL
	,closingBalance MONEY NOT NULL
	,isAuto	BIT NOT NULL
	,bankName NVARCHAR(150) NOT NULL
	,processedBy VARCHAR(50) NULL
	,processedDate DATETIME NULL
	,customerId BIGINT
);

CREATE TABLE CUSTOMER_TRANSACTIONS
(
	rowId BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY
	,customerId BIGINT NOT NULL
	,tranDate DATETIME NOT NULL
	,particulars NVARCHAR(500) NOT NULL
	,deposit MONEY NOT NULL
	,withdraw MONEY NOT NULL
	,refereceId BIGINT
	,head VARCHAR(40) NOT NULL
	,createdBy VARCHAR(50) NOT NULL
	,createdDate DATETIME NOT NULL
	,bankId INT NULL
);


ALTER TABLE CUSTOMER_DEPOSIT_LOGS ADD isSkipped BIT
ALTER TABLE CUSTOMER_DEPOSIT_LOGS ADD isSettled BIT
ALTER TABLE CUSTOMER_DEPOSIT_LOGS ADD skippedBy VARCHAR(50) NULL
ALTER TABLE CUSTOMER_DEPOSIT_LOGS ADD skippedDate DATETIME NULL
ALTER TABLE CUSTOMER_TRANSACTIONS ADD bankId INT NULL
