UPDATE APPLICATIONMENUS SET isActive = 'N' WHERE menuName = 'MODIFY CUSTOMER BANK'
UPDATE APPLICATIONMENUS SET isActive = 'N' WHERE menuName = 'APPROVE/REJECT AUTO DEBIT'
UPDATE APPLICATIONMENUS SET isActive = 'N' WHERE menuName = 'CUSTOMER ID VERIFICATION'
UPDATE APPLICATIONMENUS SET isActive = 'N' WHERE menuName = 'CUSTOMER MODIFICATION'

UPDATE APPLICATIONMENUS SET menuGroup = 'Deposit API' WHERE menuName = 'FUND DEPOSIT REPORT'
UPDATE APPLICATIONMENUS SET menuGroup = 'Customer Management' WHERE menuName = 'Customer SOA'


SELECT * FROM APPLICATIONMENUS WHERE menuName = 'Customer SOA'



