USE FastMoneyPro_Remit
GO

ALTER TABLE REFERRAL_INCENTIVE_TRANSACTION_WISE ADD TXN_DATE DATETIME NULL

ALTER TABLE REFERRAL_INCENTIVE_TRANSACTION_WISE ADD TAX_AMOUNT MONEY NULL

CREATE TABLE REFERRAL_INCENTIVE_TRANSACTION_WISE
(
	ROW_ID BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY
	,REFERRAL_ID INT NOT NULL
	,PARTNER_ID INT NOT NULL
	,TRAN_ID BIGINT NOT NULL
	,COMMISSION_PCNT DECIMAL(5,2) NOT NULL DEFAULT(0)
	,PAID_COMMISSION MONEY NOT NULL DEFAULT(0)
	,FX_PCNT DECIMAL(5,2) NOT NULL DEFAULT(0)
	,PAID_FX MONEY NOT NULL DEFAULT(0)
	,FLAT_RATE MONEY NOT NULL DEFAULT(0)
	,PAID_FLAT MONEY NOT NULL DEFAULT(0)
	,PAID_NEW_CUSTOMER_RATE MONEY NOT NULL DEFAULT(0)
	,PAID_NEW_CUSTOMER MONEY NOT NULL DEFAULT(0)
	,CUSTOMER_ID BIGINT NULL
	,CREATED_DATE DATETIME NOT NULL
	,IS_CANCEL BIT NOT NULL
);



