ALTER TABLE dbo.REFERRAL_AGENT_WISE ADD REFERRAL_LIMIT MONEY,RULE_TYPE CHAR(1)
ALTER TABLE REFERRAL_AGENT_WISE ADD REFERRAL_TYPE_CODE CHAR(2), REFERRAL_TYPE VARCHAR(30), BRANCH_ID INT
CREATE TABLE REFERRAL_AGENT_WISE
(
	ROW_ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY
	,AGENT_ID INT NOT NULL
	,REFERRAL_CODE VARCHAR(50) NOT NULL
	,REFERRAL_NAME VARCHAR(150) NOT NULL
	,REFERRAL_ADDRESS VARCHAR(250) NULL
	,REFERRAL_MOBILE VARCHAR(25) NULL
	,REFERRAL_EMAIL VARCHAR(80) NULL
	,REFERRAL_ID INT DEFAULT(0) NOT NULL
	,CREATED_BY VARCHAR(60) NOT NULL
	,CREATED_DATE DATETIME NULL
	,MODIFIED_BY VARCHAR(60) NULL
	,MODIFIED_DATE DATETIME NULL
	,IS_ACTIVE BIT DEFAULT(0) NOT NULL
);


SELECT * FROM REFERRAL_AGENT_WISE



