ALTER TABLE REMITTRAN ALTER COLUMN TRANSTATUS VARCHAR(40)
ALTER TABLE dbo.remitTran ADD PayerId BIGINT NULL  
ALTER TABLE dbo.remitTran ADD PayerBranchId BIGINT NULL 
ALTER TABLE dbo.remitTranTemp ADD PayerId BIGINT NULL  
ALTER TABLE dbo.remitTranTemp ADD PayerBranchId BIGINT NULL