CREATE TABLE TBL_FUND_TRANSFER
(
	ROW_ID BIGINT NOT NULL IDENTITY(1, 1) PRIMARY KEY
	,SETTINGS_ID INT NOT NULL
	,AMOUNT MONEY NOT NULL
	,TRAN_DATE DATETIME NOT NULL
	,CREATED_BY VARCHAR(50) NOT NULL
	,CREATED_DATE DATETIME NOT NULL
	,CURRENCY VARCHAR(5) NOT NULL
	,IS_SUCCESS BIT NULL
	,VOUCHER_NUM VARCHAR(20)
	,ERROR_MSG VARCHAR(250)
)

