
CREATE TABLE TBL_USER_2FA_SETUP
(
	ROW_ID INT IDENTITY(1, 1) NOT NULL PRIMARY KEY
	, [USER_ID] INT NOT NULL
	, [USER_NAME] VARCHAR(50) NOT NULL
	, USER_UNIQUE_CODE VARCHAR(200) NOT NULL
	, CREATED_BY VARCHAR(50) NOT NULL
	, CREATED_DATE DATETIME NOT NULL
	, MAIL_SEND_DATE DATETIME NULL
	, MAIL_SEND_USER VARCHAR(50) NULL
)

CREATE TABLE TBL_USER_2FA_LOG
(
	ROW_ID BIGINT IDENTITY(1, 1) NOT NULL PRIMARY KEY
	, USER_2FA_ID INT NOT NULL
	, LOGIN_IP_ADDRESS VARCHAR(50) NOT NULL
	, LOGIN_COUNTRY NVARCHAR(200) 
	, LOGIN_COUNTRY_CODE NVARCHAR(200) 
	, LOGIN_CITY NVARCHAR(200) 
	, LOGIN_REGION NVARCHAR(200) 
	, LOGIN_LAT NVARCHAR(200) 
	, LOGIN_LONG NVARCHAR(200) 
	, LOGIN_TIMEZONE NVARCHAR(200) 
	, LOGIN_ZIPCODDE NVARCHAR(200) 
	, LOGIN_BROWSER NVARCHAR(100)
	, LOGIN_BROWSER_VERSION VARCHAR(100)
	, LOGIN_DATE DATETIME
	, OTP_USED VARCHAR(10)
	, IS_SUCCESSFUL BIT
)

SELECT * FROM TBL_USER_2FA_SETUP

select * from applicationfunctions where parentfunctionid='10101300'
EXEC proc_AddFunction'40112010','40112000','Print'

update applicationfunctions set functionName='Send QR Code' where functionid='10101360'

