

CREATE TABLE TBL_SMS_SEND_LOGS
(
	ROW_ID BIGINT NOT NULL IDENTITY(1, 1) PRIMARY KEY
	,MOBILE_NUMBER VARCHAR(20)
	,CONTROL_NO VARCHAR(30)
	,PROCESS_ID VARCHAR(50)
	,MSG_BODY NVARCHAR(700)
	,CREATED_BY VARCHAR(50)
	,CREATED_DATE DATETIME
	,IS_SEND_SUCCESS BIT
	,[STATUS] VARCHAR(20)
	,STATUS_DETAIL VARCHAR(100)
	,MT_ID VARCHAR(50)
);

