ALTER TABLE TBL_CUSTOMER_KYC ALTER COLUMN remarks NVARCHAR(800)  NULL
ALTER TABLE TBL_CUSTOMER_KYC add trackingNo VARCHAR(20)  NULL
CREATE TABLE TBL_CUSTOMER_KYC
(
	rowId BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	customerId INT NOT NULL,
	kycMethod INT NOT NULL,
	kycStatus INT NOT NULL,
	remarks NVARCHAR(800)  NULL,
	createdBy VARCHAR(30) NOT NULL,
	createdDate DATETIME NOT NULL,
	modifiedBy VARCHAR(30) NULL,
	modifiedDate DATETIME NULL,
	isDeleted BIT NOT NULL DEFAULT(0),
	deletedBy VARCHAR(30) NULL,
	deletedDate DATETIME NULL
);



