CREATE TABLE TBL_FUND_TRANSFER_SETTINGS
(
	ROW_ID INT NOT NULL IDENTITY(1, 1) PRIMARY KEY
	,CURRENCY VARCHAR(5) NOT NULL
	,FROM_ACC VARCHAR(30) NOT NULL
	,TO_ACC VARCHAR(30) NOT NULL
	,[DESCRIPTION] NVARCHAR(250) NOT NULL
)