

CREATE TABLE TEMP_TRAN_UPLOAD
(
	ROW_ID INT IDENTITY(1, 1) NOT NULL PRIMARY KEY
	,SESSION_ID VARCHAR(50)
	,[USER] VARCHAR(50)
	,ACC_NUM VARCHAR(30)
	,AMOUNT MONEY
	,TRAN_DATE DATETIME
	,TRAN_TYPE CHAR(2)
	,NARRATION VARCHAR(250)
);

SELECT TOP 2* FROM TEMP_TRAN_UPLOAD
ORDER BY ROW_ID

SELECT * FROM TEMP_TRAN_UPLOAD
