
CREATE TABLE TP_API_RATE_SETUP
(
	ROW_ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY
	,SENDING_COUNTRY INT NOT NULL
	,PAYOUT_COUNTRY INT NOT NULL
	,SENDING_CURRENCY VARCHAR(50) NOT NULL
	,PAYOUT_CURRENCY VARCHAR(50) NOT NULL
	,PAYOUT_PARTNER INT NULL
	,PARTNER_CUSTOMER_RATE FLOAT NULL
	,PARTNER_SETTLEMENT_RATE FLOAT NULL
	,RATE_MARGIN_OVER_PARTNER_RATE FLOAT NULL
	,JME_MARGIN FLOAT NULL
	,OVERRIDE_CUSTOMER_RATE FLOAT NULL
	,IS_ACTIVE BIT NOT NULL
	,MODIFIED_BY VARCHAR(50) NULL
	,MODIFIED_DATE DATETIME NULL
);

CREATE TABLE TP_API_RATE_SETUP_HISTORY
(
	ROW_ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY
	,API_RATE_SETUP_ROW_ID INT NOT NULL
	,SENDING_COUNTRY INT NOT NULL
	,PAYOUT_COUNTRY INT NOT NULL
	,SENDING_CURRENCY VARCHAR(50) NOT NULL
	,PAYOUT_CURRENCY VARCHAR(50) NOT NULL
	,PAYOUT_PARTNER INT NULL
	,PARTNER_CUSTOMER_RATE FLOAT NULL
	,PARTNER_SETTLEMENT_RATE FLOAT NULL
	,RATE_MARGIN_OVER_PARTNER_RATE FLOAT NULL
	,JME_MARGIN FLOAT NULL
	,OVERRIDE_CUSTOMER_RATE FLOAT NULL
	,IS_ACTIVE BIT NOT NULL
	,CREATED_BY VARCHAR(50) NULL
	,CREATED_DATE DATETIME NULL
);

