DROP TABLE TRAN_API_CALL_HISTORY

CREATE TABLE TRAN_API_CALL_HISTORY
(
	ROW_ID BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY
	,TRAN_ID BIGINT NOT NULL 
	,REQUESTED_BY  VARCHAR(100) NOT NULL 
	,RESPOSE_DATE  DATETIME NOT NULL 
	,RESPONSE_CODE VARCHAR(8) NOT NULL
	,RESPONSE_MSG VARCHAR(250) NOT NULL
);
CREATE INDEX TRAN_ID__INDEX 
ON TRAN_API_CALL_HISTORY(TRAN_ID)
