
CREATE TABLE TRANSIT_CASH_SETTLEMENT
(
	ROW_ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY
	,REFERRAL_CODE VARCHAR(50) NOT NULL
	,RECEIVING_MODE CHAR(1)
	,RECEIVING_BANK_BRANCH INT NOT NULL
	,AMOUNT MONEY NOT NULL
	,TRAN_DATE DATETIME NOT NULL
	,CREATED_BY VARCHAR(50) NOT NULL
	,CREATED_DATE DATETIME NOT NULL
);
