
CREATE PROC PROC_UNTRANSACTED_REPORT
(
	@USER	VARCHAR(40)
	,@FROM_DATE	VARCHAR(25)
	,@TO_DATE	VARCHAR(25)
	,@DATE_TYPE	CHAR(1)
)
AS;
SET NOCOUNT ON;
SET XACT_ABORT ON;
BEGIN
	SELECT CUSTOMERID, 
			DEPOSIT_AMOUNT = SUM(DEPOSIT), 
			[DEPOSIT_DATE] = CONVERT(VARCHAR, tranDate, 111)
	FROM CUSTOMER_TRANSACTIONS (NOLOCK)
	WHERE HEAD = 'Customer Deposit'
	GROUP BY CONVERT(VARCHAR, tranDate, 111), CUSTOMERID

	SELECT CUSTOMERID, 
			REMITTANCE_AMOUNT = SUM(WITHDRAW), 
			[REMITTANCE_DATE] = CONVERT(VARCHAR, tranDate, 111)
	FROM CUSTOMER_TRANSACTIONS (NOLOCK)
	WHERE HEAD = 'Send Txn: Bank Deposit'
	GROUP BY CONVERT(VARCHAR, tranDate, 111), CUSTOMERID
END

