SET QUOTED_IDENTIFIER ON
SET ANSI_NULLS ON
GO
--DECLARE @MEMBESHIP_ID VARCHAR(20)
--EXEC PROC_GENERATE_MEMBERSHIP_ID  @USER = 'ADMIN', @CUSTOMERID = 12131, @MEMBESHIP_ID = @MEMBESHIP_ID

ALTER PROC PROC_GENERATE_MEMBERSHIP_ID
(
	@USER VARCHAR(40) 
	,@CUSTOMERID BIGINT 
	,@MEMBESHIP_ID VARCHAR(15) OUT 
	,@loginBranchId BIGINT = NULL
)
AS;
SET NOCOUNT ON;
SET XACT_ABORT ON;
BEGIN
	DECLARE @AGENTID VARCHAR(10), @RANDOM_NUMBER VARCHAR(12), @AGENTTYPE VARCHAR(5), @BRANCHCODE CHAR(3), @maxValue INT, @USERTYPE VARCHAR(5)
	IF @USER IN ('online','mobile')
	BEGIN
		IF @USER ='online'
		BEGIN
		    SET @BRANCHCODE='ONL'
		END
		ELSE
		BEGIN
		    SET @BRANCHCODE='MOB'
		END
			SELECT maxValue = ISNULL(maxValue, 1)
			FROM agentMaster (NOLOCK) 
			WHERE agentId =(SELECT agentId FROM dbo.Vw_GetAgentID WHERE SearchText='PayTxnFromMobile')
			
			UPDATE agentMaster SET MAXVALUE = @maxValue + 1 WHERE AGENTID = (SELECT agentId FROM dbo.Vw_GetAgentID WHERE SearchText='PayTxnFromMobile')
	END
	ELSE
	BEGIN
	    
	SELECT @AGENTID = AM.AGENTID,
			@AGENTTYPE = AM.agentType,
			@BRANCHCODE = BRANCHCODE,
			@maxValue = ISNULL(maxValue, 1),
			@USERTYPE = ISNULL(AU.USERTYPE, 'HO')
	FROM APPLICATIONUSERS AU(NOLOCK) 
	INNER JOIN agentMaster AM(NOLOCK) ON AM.AGENTID = AU.agentId
	WHERE userName = @USER
	
	IF @loginBranchId <> 0
	BEGIN
		SET @AGENTID = @loginBranchId

		SELECT @AGENTID = AGENTID,
			@AGENTTYPE = agentType,
			@BRANCHCODE = BRANCHCODE,
			@maxValue = ISNULL(maxValue, 1),
			@USERTYPE = 'A'
		FROM agentMaster (NOLOCK) WHERE  AGENTID = @AGENTID

	END

	IF @USERTYPE NOT IN ('HO')
	BEGIN
		IF @AGENTTYPE = '2904'
		BEGIN
			SELECT @BRANCHCODE = BRANCHCODE, @maxValue = ISNULL(maxValue, 1), @AGENTID = AGENTID
			FROM agentMaster (NOLOCK) 
			WHERE PARENTID = @AGENTID
		END

		UPDATE agentMaster SET MAXVALUE = @maxValue + 1 WHERE AGENTID = @AGENTID 
	END
	ELSE
	BEGIN
		SELECT @BRANCHCODE = BRANCHCODE, @maxValue = ISNULL(maxValue, 1), @AGENTID = AGENTID
		FROM agentMaster (NOLOCK) 
		WHERE PARENTID = @AGENTID		--main HO

		UPDATE agentMaster SET MAXVALUE = @maxValue + 1 WHERE AGENTID = @AGENTID 
	END
	END

	SELECT @RANDOM_NUMBER = RIGHT('0000000' + CAST(@maxValue AS VARCHAR), 6)

	SET @MEMBESHIP_ID = @BRANCHCODE + @RANDOM_NUMBER
END;

