
--Exec PROC_LIQUIDITY_REPORT @flag='LIQ-S', @date='2020/05/31'

ALTER PROC PROC_LIQUIDITY_REPORT  
(
	@FLAG VARCHAR(10)
	,@DATE VARCHAR(30) = NULL
)
AS;
SET NOCOUNT ON;
SET XACT_ABORT ON;
BEGIN
	IF @FLAG = 'LIQ-S'
	BEGIN
		SET @DATE = @DATE + ' 23:59:59'

		DECLARE @CASH_BALANCE MONEY, @BANK_BALANCE MONEY, @RECEIVABLES_BELOW_FOUR_DAYS MONEY, @CORRESPONDENT_RECEIVABLES MONEY
				, @CUSTOMER_LIAB1 MONEY, @CUSTOMER_LIAB2 MONEY
		
		SELECT @CASH_BALANCE = ISNULL(SUM(CASE WHEN PART_TRAN_TYPE = 'CR' THEN TRAN_AMT * -1 ELSE TRAN_AMT END), 0) 
		FROM TRAN_MASTER (NOLOCK) WHERE 1=1
		AND ACC_NUM IN ('100139297552', '100139297553', '100139208487', '100139219838', '100139297551', '100139292573', '100139258568')
		AND TRAN_DATE <= @DATE  
		
		SELECT @BANK_BALANCE = ISNULL(SUM(CASE WHEN PART_TRAN_TYPE = 'CR' THEN TRAN_AMT * -1 ELSE TRAN_AMT END), 0) 
		FROM TRAN_MASTER (NOLOCK) WHERE 1=1
		AND GL_SUB_HEAD_CODE = 23
		AND TRAN_DATE <= @DATE

		SELECT @CORRESPONDENT_RECEIVABLES = ISNULL(SUM(CASE WHEN PART_TRAN_TYPE = 'CR' THEN TRAN_AMT * -1 ELSE TRAN_AMT END), 0) 
		FROM TRAN_MASTER (NOLOCK) WHERE 1=1
		AND GL_SUB_HEAD_CODE = 110
		AND TRAN_DATE <= @DATE
		
		SELECT @CUSTOMER_LIAB1 = ISNULL(SUM(CASE WHEN PART_TRAN_TYPE = 'CR' THEN TRAN_AMT * -1 ELSE TRAN_AMT END), 0) 
		FROM TRAN_MASTER (NOLOCK) WHERE 1=1
		AND GL_SUB_HEAD_CODE = 79 		
		AND TRAN_DATE <= @DATE

		SELECT @CUSTOMER_LIAB2 = ISNULL(SUM(CASE WHEN PART_TRAN_TYPE = 'CR' THEN TRAN_AMT * -1 ELSE TRAN_AMT END), 0) 
		FROM TRAN_MASTER (NOLOCK) WHERE 1=1
		AND ACC_NUM = '100339261593'
		AND TRAN_DATE <= @DATE

		SELECT ISNULL(@CASH_BALANCE, 0) CASH_BALANCE, ISNULL(@BANK_BALANCE, 0) BANK_BALANCE, ISNULL(@CORRESPONDENT_RECEIVABLES, 0) CORRESPONDENT_RECEIVABLES
				, ISNULL(@RECEIVABLES_BELOW_FOUR_DAYS, 0) BELOW_FOUR_DAYS
				, ISNULL(@CUSTOMER_LIAB1, 0) + ISNULL(@CUSTOMER_LIAB2, 0) CUSTOMER_LIAB
				, TOTAL = ISNULL(@CASH_BALANCE, 0) + ISNULL(@BANK_BALANCE, 0) + ISNULL(@CORRESPONDENT_RECEIVABLES, 0) 
							+ ISNULL(@RECEIVABLES_BELOW_FOUR_DAYS, 0) + ISNULL(@CUSTOMER_LIAB1, 0) + ISNULL(@CUSTOMER_LIAB2, 0)
	END
END



