

ALTER PROC PRO_UPDATE_VAULT_TRANSFER_REFERRAL_CHANGE
(
	@TRAN_ID BIGINT
)
AS
SET NOCOUNT ON;
SET XACT_ABORT ON;
BEGIN
	DECLARE @ROWID VARCHAR(20), @TRAN_DATE VARCHAR(20), @BRANCH_ID INT = NULL, @USER_ID INT, @TRANSFER_AMT MONEY, @HISTORY_ID BIGINT

	SELECT @BRANCH_ID = BRANCHID, @USER_ID = USERID, @TRAN_DATE = CAST(TRANDATE AS DATE), @TRANSFER_AMT = INAMOUNT, @HISTORY_ID = ROWID
	FROM BRANCH_CASH_IN_OUT_HISTORY(NOLOCK) 
	WHERE REFERENCEID = @TRAN_ID
	AND INAMOUNT <> 0

	IF @BRANCH_ID IS NULL
	BEGIN
		RETURN;
	END

	IF NOT EXISTS (SELECT 1 FROM BRANCH_CASH_IN_OUT_HISTORY(NOLOCK) 
					WHERE REFERENCEID = @TRAN_ID AND HEAD = 'Txn Send')
	BEGIN
		RETURN
	END

	DELETE FROM BRANCH_CASH_IN_OUT_HISTORY
	WHERE REFERENCEID = @TRAN_ID AND HEAD = 'Txn Send'

	IF NOT EXISTS(SELECT 1 FROM BRANCH_CASH_IN_OUT_HISTORY (NOLOCK) WHERE BRANCHID = @BRANCH_ID AND HEAD IN ('Transfer To Vault', 'Transfer To Vault(From Vault)') AND CAST(TRANDATE AS DATE) = @TRAN_DATE)
	BEGIN
		RETURN;
	END
	
	
	IF EXISTS(SELECT 1 FROM AGENTMASTER (NOLOCK) WHERE AGENTID = @BRANCH_ID AND ISNULL(isIntl, 0) = 1)
	BEGIN
		RETURN;
	END

	IF @BRANCH_ID <> 394396
	BEGIN
		SELECT @ROWID = MAIN_TABLE_ROW_ID
		FROM BRANCH_CASH_IN_OUT_HISTORY(NOLOCK) 
		WHERE BRANCHID = @BRANCH_ID
		AND USERID = @USER_ID
		AND CAST(TRANDATE AS DATE) = @TRAN_DATE
		AND HEAD = 'Transfer To Vault'

		UPDATE B SET B.OUTAMOUNT = B.OUTAMOUNT -  @TRANSFER_AMT
		FROM BRANCH_CASH_IN_OUT_HISTORY B(NOLOCK) 
		WHERE MAIN_TABLE_ROW_ID = @ROWID
		AND HEAD = 'Transfer To Vault'

		UPDATE B SET B.INAMOUNT = B.INAMOUNT -  @TRANSFER_AMT
		FROM BRANCH_CASH_IN_OUT_HISTORY B(NOLOCK) 
		WHERE REFERENCEID = @ROWID
		AND HEAD = 'TRANSFER TO VAULT AUTO ADJUST'

		UPDATE T SET T.TRAN_AMT = T.TRAN_AMT - @TRANSFER_AMT, T.USD_AMT = T.USD_AMT - @TRANSFER_AMT
		FROM FASTMONEYPRO_ACCOUNT.DBO.TRAN_MASTER T(NOLOCK)
		WHERE FIELD1 = @ROWID 
		AND FIELD2 = 'Vault Transfer'
	END
	ELSE
	BEGIN
		SELECT @ROWID = MAIN_TABLE_ROW_ID
		FROM BRANCH_CASH_IN_OUT_HISTORY(NOLOCK) 
		WHERE BRANCHID = @BRANCH_ID
		AND USERID = 0
		AND CAST(TRANDATE AS DATE) = @TRAN_DATE
		AND HEAD = 'Transfer To Vault(From Vault)'

		UPDATE B SET B.OUTAMOUNT = B.OUTAMOUNT -  @TRANSFER_AMT
		FROM BRANCH_CASH_IN_OUT_HISTORY B(NOLOCK) 
		WHERE MAIN_TABLE_ROW_ID = @ROWID
		AND HEAD = 'Transfer To Vault'

		UPDATE B SET B.INAMOUNT = B.INAMOUNT -  @TRANSFER_AMT
		FROM BRANCH_CASH_IN_OUT_HISTORY B(NOLOCK) 
		WHERE REFERENCEID = @ROWID
		AND HEAD = 'TRANSFER TO VAULT AUTO ADJUST'

		UPDATE T SET T.TRAN_AMT = T.TRAN_AMT - @TRANSFER_AMT, T.USD_AMT = T.USD_AMT - @TRANSFER_AMT
		FROM FASTMONEYPRO_ACCOUNT.DBO.TRAN_MASTER T(NOLOCK)
		WHERE FIELD1 = @ROWID 
		AND FIELD2 = 'Vault Transfer'
	END

	DELETE FROM BRANCH_CASH_IN_OUT_HISTORY WHERE ROWID = @HISTORY_ID
END
