use fastmoneypro_account
RETURN

drop table TRAN_MASTER_2019
drop table TRAN_MASTER_DETAIL_2019


SELECT * INTO TRAN_MASTER_2019
FROM TRAN_MASTER (NOLOCK)

SELECT M.* INTO TRAN_MASTER_DETAIL_2019
FROM TRAN_MASTERDETAIL M(NOLOCK)

select * from FASTMONEYPRO_REMIT.DBO.REMIT_TRAN_STATUS_FROM_INFICARE where controlno = '21933580'


SELECT * FROM FASTMONEYPRO_REMIT.DBO.REMIT_TRAN_STATUS_FROM_INFICARE
ALTER TABLE FASTMONEYPRO_REMIT.DBO.REMIT_TRAN_STATUS_FROM_INFICARE ADD CONTROLNO VARCHAR(30)
ALTER TABLE FASTMONEYPRO_REMIT.DBO.REMIT_TRAN_STATUS_FROM_INFICARE ADD COLLMODE VARCHAR(30)

UPDATE I SET I.CONTROLNO = DBO.decryptDb(R.CONTROLNO), I.COLLMODE = R.COLLMODE
FROM FASTMONEYPRO_REMIT.DBO.REMIT_TRAN_STATUS_FROM_INFICARE I(NOLOCK)
INNER JOIN FASTMONEYPRO_REMIT.DBO.REMITTRAN R(NOLOCK) ON R.UPLOADLOGID = I.TRANNO


SELECT * 
FROM FASTMONEYPRO_REMIT.DBO.REMIT_TRAN_STATUS_FROM_INFICARE R(NOLOCK)
INNER JOIN TRAN_MASTER_2019 M(NOLOCK) ON M.FIELD1 = R.CONTROLNO


SELECT * FROM FASTMONEYPRO_REMIT.DBO.REMIT_TRAN_STATUS_FROM_INFICARE WHERE PAIDDATE IS NOT NULL AND CANCELDATE IS NOT NULL
SELECT * FROM FASTMONEYPRO_REMIT.DBO.REMIT_TRAN_STATUS_FROM_INFICARE WHERE CONTROLNO IS NULL
SELECT * FROM FASTMONEYPRO_REMIT.DBO.REMITTRAN WHERE UPLOADLOGID = 325223

SELECT M.SenderBankName,M.DOT,DBO.DECRYPTDB(M.REFNO),M.REFNO,I.* FROM JME_DB.DBO.MONEYSEND M
INNER JOIN FASTMONEYPRO_REMIT.DBO.REMIT_TRAN_STATUS_FROM_INFICARE  I ON I.TRANNO = M.TRANNO
WHERE I.CONTROLNO IS NULL

SELECT * INTO #PAID 
FROM FASTMONEYPRO_REMIT.DBO.REMIT_TRAN_STATUS_FROM_INFICARE
WHERE PAYSTATUS = 'PAID'

SELECT COUNT(0) FROM #PAID


SELECT M.PAIDDATE, P.PAIDDATE
FROM #PAID P
INNER JOIN FASTMONEYPRO_REMIT.DBO.REMITTRAN M(NOLOCK) ON M.UPLOADLOGID = P.TRANNO
WHERE CAST(M.PAIDDATE AS DATE) <> CAST(P.PAIDDATE AS DATE)

SELECT * INTO #CANCEL 
FROM FASTMONEYPRO_REMIT.DBO.REMIT_TRAN_STATUS_FROM_INFICARE
WHERE TRANSTATUS = 'CANCEL' OR PAYSTATUS = 'CANCEL'

SELECT COUNT(0) FROM #CANCEL

SELECT CAST(M.TRAN_DATE AS DATE), CAST(P.CANCELDATE AS DATE), P.*
FROM #CANCEL P
INNER JOIN TRAN_MASTER M(NOLOCK) ON M.FIELD1 = P.CONTROLNO
WHERE (ISNULL(M.ACCT_TYPE_CODE, 'SEND') = 'Reverse')
AND CAST(M.TRAN_DATE AS DATE) <> CAST(P.CANCELDATE AS DATE)

select * from #CANCEL where controlno = '21933580'
select * from TRAN_MASTER where field1 = '21933580' and (ISNULL(ACCT_TYPE_CODE, 'SEND') = 'Reverse')

update fastmoneypro_remit.dbo.remittran set cancelapproveddate = getdate() where controlno = dbo.fnaencryptstring('21148420')
update tran_master set tran_date = getdate() where field1 = '21148420' and acct_type_code = 'Reverse'


select m.cancelapproveddate, p.*
FROM #CANCEL P
INNER JOIN fastmoneypro_remit.dbo.remittran M(NOLOCK) ON M.uploadlogid = P.tranno
WHERE CAST(M.cancelapproveddate AS DATE) <> CAST(P.CANCELDATE AS DATE)

21207411, 21397232

delete from tran_master where ref_num ='264294'
delete from tran_masterdetail where ref_num ='264294'

update tran_master set tran_date = '2019-05-27 11:52:55.000' where ref_num = '264294.01'
update tran_master set tran_date = '2019-05-27 12:51:53.870' where ref_num = '264293.01'

EXEC proc_CancelTranVoucher @flag = 'REVERSE',@refNum='264293',@vType='J',@refund='N',@user='system',@remarks=''

21355251
21675764
33JP212521341
33JP212676986
select distinct field1, tran_date, canceldate from #tmep t
inner join tran_master m on m.field1 = t.controlno
where ISNULL(M.ACCT_TYPE_CODE, 'SEND') = 'Reverse'

SELECT * FROM #CANCEL C
LEFT JOIN #CANCEL_ACC A ON A.FIELD1 = C.CONTROLNO
WHERE A.FIELD1 IS NULL

SELECT * FROM #CANCEL2 C
LEFT JOIN #CANCEL1 D ON D.REF_NUM = C.REF_NUM
WHERE D.REF_NUM IS NULL

SELECT * FROM #PAID P
LEFT JOIN #PAID1 P1 ON P.CONTROLNO = P1.FIELD1
WHERE P1.FIELD1 IS NULL

SELECT * FROM TRAN_MASTER WHERE FIELD1 = '21933580'


SELECT * FROM CASH_ACCOUNT_LIST
ALTER TABLE CASH_ACCOUNT_LIST ADD ISACTIVE BIT
UPDATE CASH_ACCOUNT_LIST SET ISACTIVE = 0 WHERE ROW_ID = 29


INSERT INTO CASH_IN_OUT_HISTORY
SELECT CASE WHEN PART_TRAN_TYPE = 'DR' THEN TRAN_AMT ELSE 0 END
		, CASE WHEN PART_TRAN_TYPE = 'CR' THEN TRAN_AMT ELSE 0 END, T.ACC_NUM, '', T.TRAN_DATE, T.FIELD1, 'CASH', D.tran_particular
FROM TRAN_MASTER T
INNER JOIN TRAN_MASTERDETAIL D ON D.REF_NUM = T.REF_NUM
INNER JOIN CASH_ACCOUNT_LIST C ON C.ACC_NUM = T.ACC_NUM
WHERE T.TRAN_DATE BETWEEN '2018-12-31' AND '2019-12-31 23:59:59'
--AND PART_TRAN_TYPE = 'DR'
AND C.ISACTIVE = 1

UNION ALL

SELECT TRAN_AMT, 0, T.ACC_NUM, '', T.TRAN_DATE, T.REF_NUM, 'JP', D.tran_particular
FROM TRAN_MASTER T
INNER JOIN TRAN_MASTERDETAIL D ON D.REF_NUM = T.REF_NUM
INNER JOIN #JP A ON A.REF_NUM = T.REF_NUM
INNER JOIN CASH_ACCOUNT_LIST C ON C.ACC_NUM = T.ACC_NUM
WHERE PART_TRAN_TYPE = 'CR'
AND C.ISACTIVE = 1

UNION ALL

SELECT TRAN_AMT, 0, T.ACC_NUM, '', T.TRAN_DATE, T.REF_NUM, 'SMBC', D.tran_particular
FROM TRAN_MASTER T
INNER JOIN TRAN_MASTERDETAIL D ON D.REF_NUM = T.REF_NUM
INNER JOIN #SMBC A ON A.REF_NUM = T.REF_NUM
INNER JOIN CASH_ACCOUNT_LIST C ON C.ACC_NUM = T.ACC_NUM
WHERE PART_TRAN_TYPE = 'CR'
AND C.ISACTIVE = 1

UNION ALL

SELECT TRAN_AMT, 0, T.ACC_NUM, '', T.TRAN_DATE, T.REF_NUM, 'PITTY', D.tran_particular
FROM TRAN_MASTER T
INNER JOIN TRAN_MASTERDETAIL D ON D.REF_NUM = T.REF_NUM
INNER JOIN #PITTY A ON A.REF_NUM = T.REF_NUM
INNER JOIN CASH_ACCOUNT_LIST C ON C.ACC_NUM = T.ACC_NUM
WHERE PART_TRAN_TYPE = 'CR'
AND C.ISACTIVE = 1

DROP TABLE #PITTY
DROP TABLE #SMBC
DROP TABLE #JP
TRUNCATE TABLE CASH_IN_OUT_HISTORY

SELECT DISTINCT REF_NUM INTO #JP
FROM TRAN_MASTER T
WHERE T.TRAN_DATE BETWEEN '2018-12-31' AND '2019-12-31 23:59:59'
AND PART_TRAN_TYPE = 'DR'
AND ACC_NUM IN ('100241011536')


SELECT DISTINCT REF_NUM INTO #SMBC
FROM TRAN_MASTER T
WHERE T.TRAN_DATE BETWEEN '2018-12-31' AND '2019-12-31 23:59:59'
AND PART_TRAN_TYPE = 'DR'
AND ACC_NUM IN ('100241011537')

SELECT DISTINCT REF_NUM INTO #PITTY
FROM TRAN_MASTER T
WHERE T.TRAN_DATE BETWEEN '2018-12-31' AND '2019-12-31 23:59:59'
AND PART_TRAN_TYPE = 'DR'
AND ACC_NUM IN ('100139258568')

SELECT * FROM #JP

--100239220146 JP
--100241011537 SMBC
--DR IN

SELECT * FROM CASH_ACCOUNT_LIST WHERE ACC_NUM = '101139273793'

SELECT CAST(TRAN_DATE AS DATE), SUM(IN_AMOUNT - OUT_AMOUNT) FROM CASH_IN_OUT_HISTORY
GROUP BY CAST(TRAN_DATE AS DATE) 
ORDER BY CAST(TRAN_DATE AS DATE)

select 90574037.00 - 18588697.00

SELECT * FROM FASTMONEYPRO_REMIT.DBO.REMIT_TRAN_STATUS_FROM_INFICARE
WHERE CAST(PAIDDATE AS DATE) = '2019-01-01'
AND COLLMODE = 'CASH COLLECT'

SELECT SUM(TAMT) FROM FASTMONEYPRO_REMIT.DBO.REMITTRAN
WHERE CAST(PAIDDATE AS DATE) = '2019-01-01'
AND COLLMODE = 'CASH COLLECT'


SELECT SUM(IN_AMOUNT), SUM(OUT_AMOUNT) FROM CASH_IN_OUT_HISTORY
WHERE TRAN_DATE BETWEEN '2019-01-01' AND '2019-01-04 23:59:59'

SELECT * FROM CASH_IN_OUT_HISTORY WHERE CAST(TRAN_DATE AS DATE) = '2019-10-01'

SELECT * FROM CASH_IN_OUT_HISTORY WHERE CAST(TRAN_DATE AS DATE) = '2019-01-03'
AND REFERENCE_TABLE = 'CASH'
and in_amount = 0


SELECT * FROM TRAN_MASTER_DELETED WHERE ACC_NUM = '100139219838' AND CAST(TRAN_DATE AS DATE) = '2019-11-11'


SELECT TRAN_AMT, 0, T.ACC_NUM, '', T.TRAN_DATE, T.REF_NUM, 'JP', D.tran_particular, t.PART_TRAN_TYPE
FROM #JP A
INNER JOIN TRAN_MASTER T ON T.REF_NUM = A.REF_NUM
INNER JOIN TRAN_MASTERDETAIL D ON D.REF_NUM = T.REF_NUM
INNER JOIN CASH_ACCOUNT_LIST C ON C.ACC_NUM = T.ACC_NUM
WHERE T.PART_TRAN_TYPE = 'CR'
AND C.ISACTIVE = 1
AND CAST(T.TRAN_DATE AS DATE) =  '2019-11-11'

SELECT * FROM #JP


select * from tran_master where ref_num = '200282'


