USE FASTMONEYPRO_REMIT
--DROP TABLE COMM_CALC_2020
RETURN


UPDATE M SET M.TRAN_AMT = C.TOTAL_AMT, M.USD_AMT = C.TOTAL_AMT 
--SELECT COUNT(0) 
FROM COMM_CALC_2020 C
INNER JOIN FASTMONEYPRO_ACCOUNT.DBO.TRAN_MASTER M ON M.FIELD1 = C.CONTROLNO
WHERE M.ACC_NUM IN ('910139266612')
AND M.ACCT_TYPE_CODE IS NULL

UPDATE M SET M.TRAN_AMT = C.TOTAL_AMT, M.USD_AMT = C.TOTAL_AMT
--SELECT COUNT(0)
FROM COMM_CALC_2020 C
INNER JOIN FASTMONEYPRO_ACCOUNT.DBO.TRAN_MASTER M ON M.FIELD1 = C.CONTROLNO AND C.ACC_NUM = M.ACC_NUM
WHERE M.ACCT_TYPE_CODE IS NULL

update r set r.sAgentComm =  C.TOTAL_AMT
FROM COMM_CALC_2020 C
INNER JOIN REMITTRAN R ON R.ID=C.ID

ALTER TABLE COMM_CALC_2020 ADD ACC_NUM VARCHAR(30)

UPDATE C SET C.ACC_NUM = A.ACCT_NUM
FROM COMM_CALC_2020 C
INNER JOIN FASTMONEYPRO_ACCOUNT.DBO.AC_MASTER A ON A.AGENT_ID = C.sagent
WHERE ACCT_RPT_CODE = 'ACP'

UPDATE COMM_CALC_2020 SET ACC_NUM = '500439297126' WHERE SAGENT = 394393
UPDATE COMM_CALC_2020 SET ACC_NUM = '500439205691' WHERE SAGENT = 394394

select * from FASTMONEYPRO_ACCOUNT.DBO.AC_MASTER WHERE ACCT_RPT_CODE = 'ACP'


SELECT * FROM COMM_CALC_2020 WHERE PROMOTIONCODE='JME0017'

SELECT * FROM AGENTMASTER WHERE ACTASBRANCH = 'N'

SELECT DBO.DECRYPTDB(R.CONTROLNO) CONTROLNO, PCOUNTRY, R.ID, R.TAMT, R.SERVICECHARGE, AGENTFXGAIN
		, R.PROMOTIONCODE, R.SAGENT, R.SAGENTNAME, PSUPERAGENT, PAGENTCOMM
		, FIRST_TRAN = ISNULL(isFirstTran, 'N'), R.CREATEDDATE, TRANSTATUS, CANCELAPPROVEDDATE
INTO COMM_CALC_2020
FROM REMITTRAN R(NOLOCK)
INNER JOIN TRANSENDERS S(NOLOCK) ON S.TRANID = R.ID
WHERE R.CREATEDDATE BETWEEN '2020-03-20' AND GETDATE()
AND R.SAGENT IN (394393, 394394)

select max(createddate) from COMM_CALC_2020

ALTER TABLE COMM_CALC_2020 ADD COMM_PCNT MONEY, FX_PCNT MONEY, NEW_CUST MONEY, FLAT_RATE MONEY
ALTER TABLE COMM_CALC_2020 ADD COMM_AMT MONEY, FX_AMT MONEY, NEW_CUST_AMT MONEY, FLAT_AMT MONEY
ALTER TABLE COMM_CALC_2020 ADD DEDUCT_TAX BIT, DEDUCT_COMM BIT, IS_UPDATED BIT
ALTER TABLE COMM_CALC_2020 ADD TOTAL_AMT MONEY

UPDATE C SET C.COMM_PCNT=R.COMM_PCNT, C.FX_PCNT=R.FX_PCNT, C.NEW_CUST=R.NEW_CUSTOMER, C.FLAT_RATE = R.FLAT_TXN_WISE, 
				C.DEDUCT_TAX = R.DEDUCT_TAX_ON_SC, C.DEDUCT_COMM = R.DEDUCT_P_COMM_ON_SC, C.IS_UPDATED = 1
FROM COMM_CALC_2020 C
INNER JOIN #COMM R ON R.agent_id = C.sagent AND C.PSUPERAGENT = R.PARTNER_ID

DELETE FROM COMM_CALC_2020 WHERE IS_UPDATED IS NULL AND PCOUNTRY = 'VIETNAM'
DELETE FROM COMM_CALC_2020 WHERE IS_UPDATED IS NULL AND PCOUNTRY = 'NEPAL'

UPDATE C SET C.COMM_PCNT=17.50, C.FX_PCNT=40.00, C.NEW_CUST=300.00, C.FLAT_RATE = 0, 
				C.DEDUCT_TAX = 0, C.DEDUCT_COMM = 0, C.IS_UPDATED = 1
FROM COMM_CALC_2020 C
WHERE IS_UPDATED IS NULL


UPDATE COMM_CALC_2020
SET COMM_AMT = CASE WHEN ISNULL(DEDUCT_TAX, 0) = 1 AND ISNULL(DEDUCT_COMM, 0) = 1 THEN (COMM_PCNT * ((SERVICECHARGE - PAGENTCOMM) / 1.1)) / 100
					WHEN ISNULL(DEDUCT_TAX, 0) = 1 AND ISNULL(DEDUCT_COMM, 0) = 0 THEN (COMM_PCNT * (SERVICECHARGE / 1.1)) / 100
					WHEN ISNULL(DEDUCT_TAX, 0) = 0 AND ISNULL(DEDUCT_COMM, 0) = 0 THEN (COMM_PCNT * SERVICECHARGE) / 100
					WHEN ISNULL(DEDUCT_TAX, 0) = 0 AND ISNULL(DEDUCT_COMM, 0) = 1 THEN (COMM_PCNT * (SERVICECHARGE - PAGENTCOMM)) / 100 END
	, FX_AMT = CASE WHEN PSUPERAGENT = 393880 THEN (FX_PCNT * TAMT) / 100
					ELSE (FX_PCNT * AGENTFXGAIN) / 100 END
	, NEW_CUST_AMT = CASE WHEN FIRST_TRAN = 'Y' THEN NEW_CUST ELSE 0 END
	, FLAT_AMT = FLAT_RATE

UPDATE COMM_CALC_2020 SET TOTAL_AMT = ISNULL(COMM_AMT, 0) + ISNULL(FX_AMT, 0) + ISNULL(NEW_CUST_AMT, 0) + ISNULL(FLAT_AMT, 0)

SELECT TOP 3* FROM REFERRAL_INCENTIVE_TRANSACTION_WISE
SELECT * FROM COMM_CALC_2020

SELECT * INTO REFERRAL_INCENTIVE_TRANSACTION_WISE_TEST FROM REFERRAL_INCENTIVE_TRANSACTION_WISE WHERE 1=2

--delete from REFERRAL_INCENTIVE_TRANSACTION_WISE_TEST

INSERT INTO REFERRAL_INCENTIVE_TRANSACTION_WISE_TEST
SELECT REFERRAL_ID, PSUPERAGENT, ID, COMM_PCNT, COMM_AMT, FX_PCNT, FX_AMT, FLAT_RATE, FLAT_AMT, NEW_CUST, NEW_CUST_AMT
		, NULL, CREATEDDATE, 0, CREATEDDATE, NULL, NULL
FROM COMM_CALC_2020


UPDATE R SET R.COMMISSION_PCNT = T.COMMISSION_PCNT, R.PAID_COMMISSION = T.PAID_COMMISSION
		, R.FX_PCNT = T.FX_PCNT, R.PAID_FX = T.PAID_FX, R.FLAT_RATE = T.FLAT_RATE, R.PAID_FLAT = T.PAID_FLAT
		, R.PAID_NEW_CUSTOMER_RATE = T.PAID_NEW_CUSTOMER_RATE, R.PAID_NEW_CUSTOMER = T.PAID_NEW_CUSTOMER
FROM REFERRAL_INCENTIVE_TRANSACTION_WISE_TEST T
INNER JOIN REFERRAL_INCENTIVE_TRANSACTION_WISE R ON R.TRAN_ID = T.TRAN_ID AND R.IS_CANCEL = T.IS_CANCEL

INSERT INTO REFERRAL_INCENTIVE_TRANSACTION_WISE_TEST
SELECT REFERRAL_ID, PSUPERAGENT, ID, COMM_PCNT, -1*COMM_AMT, FX_PCNT, -1*FX_AMT, FLAT_RATE, -1*FLAT_AMT, NEW_CUST, -1*NEW_CUST_AMT
		, NULL, CREATEDDATE, 1, CANCELAPPROVEDDATE, NULL, NULL
FROM COMM_CALC_2020
WHERE TRANSTATUS = 'CANCEL'

SELECT * FROM INCENTIVE_SETUP_REFERRAL_WISE
WHERE REFERRAL_ID=0

SELECT * FROM REFERRAL_AGENT_WISE WHERE REFERRAL_CODE='JME0103'
SELECT AGENT_ID, PARTNER_ID, COMM_PCNT, FX_PCNT, FLAT_TXN_WISE, NEW_CUSTOMER, EFFECTIVE_FROM, DEDUCT_TAX_ON_SC, DEDUCT_P_COMM_ON_SC 
INTO #COMM
FROM INCENTIVE_SETUP_REFERRAL_WISE WHERE AGENT_ID <> 0

INSERT INTO #COMM 
SELECT 394393, PARTNER_ID, COMM_PCNT, FX_PCNT, FLAT_TXN_WISE, NEW_CUSTOMER, EFFECTIVE_FROM, DEDUCT_TAX_ON_SC, DEDUCT_P_COMM_ON_SC 
FROM INCENTIVE_SETUP_REFERRAL_WISE WHERE REFERRAL_ID=0

UNION ALL

SELECT 394394, PARTNER_ID, COMM_PCNT, FX_PCNT, FLAT_TXN_WISE, NEW_CUSTOMER, EFFECTIVE_FROM, DEDUCT_TAX_ON_SC, DEDUCT_P_COMM_ON_SC 
FROM INCENTIVE_SETUP_REFERRAL_WISE WHERE REFERRAL_ID=0

select * from referral_agent_wise where agent_id in (394393, 394394)
SELECT * FROM INCENTIVE_SETUP_REFERRAL_WISE WHERE AGENT_ID <> 0

SELECT * FROM #COMM


SELECT * FROM REFERRAL_INCENTIVE_TRANSACTION_WISE

DROP TABLE IS_FIRST_TRAN

SELECT R.ID, S.isFirstTran, S.CUSTOMERID, R.CREATEDDATE 
INTO IS_FIRST_TRAN
FROM REMITTRAN R(NOLOCK)
INNER JOIN TRANSENDERS S(NOLOCK) ON S.TRANID = R.ID
WHERE R.CREATEDDATE > '2019-12-31'
AND (R.SAGENT IN (394393, 394394) OR R.promotioncode in ('JME0017', 'JME0029'))

select * from referral_agent_wise where agent_id in (394393, 394394)

ALTER TABLE IS_FIRST_TRAN ADD IS_GEN BIT, FIRST_TRAN BIT


SELECT COUNT(0) FROM IS_FIRST_TRAN WHERE IS_GEN IS NULL

DECLARE @CREATEDDATE DATETIME, @CUSTOMERID BIGINT, @ID BIGINT
WHILE EXISTS(SELECT TOP 1 1 FROM IS_FIRST_TRAN WHERE IS_GEN IS NULL)
BEGIN
	DECLARE @IS_FIRST_TRAN BIT = 0

	SELECT  @CREATEDDATE = CREATEDDATE, @CUSTOMERID = CUSTOMERID
			, @ID = ID
	FROM IS_FIRST_TRAN 
	WHERE IS_GEN IS NULL
	
	IF NOT EXISTS(SELECT 1 FROM REMITTRAN R(NOLOCK)
	INNER JOIN TRANSENDERS S(NOLOCK) ON S.TRANID = R.ID
	WHERE R.CREATEDDATE < @CREATEDDATE 
	AND S.CUSTOMERID = @CUSTOMERID)
		SET @IS_FIRST_TRAN = 1

	UPDATE IS_FIRST_TRAN SET IS_GEN = 1, FIRST_TRAN = @IS_FIRST_TRAN WHERE ID = @ID
END

SELECT * FROM IS_FIRST_TRAN WHERE FIRST_TRAN = 1--ISNULL(ISFIRSTTRAN, 'N') = 'Y' 
100370722--45689
100369641--45616

SELECT CREATEDDATE,pcountry,* FROM REMITTRAN R(NOLOCK)
INNER JOIN TRANSENDERS S(NOLOCK) ON S.TRANID = R.ID
WHERE S.CUSTOMERID=45689
ORDER BY R.ID ASC


UPDATE R SET R.isFirstTran = CASE WHEN FIRST_TRAN = 1 THEN 'Y' ELSE 'N' END
FROM IS_FIRST_TRAN I(NOLOCK)
INNER JOIN TRANSENDERS R(NOLOCK) ON R.TRANID = I.ID
WHERE FIRST_TRAN = 1
AND ISNULL(I.ISFIRSTTRAN, 'N') = 'N'




SELECT * FROM IS_FIRST_TRAN WHERE CUSTOMERID IS NULL
SELECT * FROM IS_FIRST_TRAN WHERE CUSTOMERID = 46664



UPDATE S SET S.isFirstTran = 'Y' 
FROM IS_FIRST_TRAN I
INNER JOIN REMITTRAN R ON R.ID=I.ID
INNER JOIN TRANSENDERS S ON S.TRANID=I.ID
WHERE 1=1
--AND R.PROMOTIONCODE = 'JME0162'
AND R.CREATEDDATE > '2020-02-14'
AND FIRST_TRAN = 1

SELECT * FROM REFERRAL_AGENT_WISE WHERE REFERRAL_NAME LIKE '%AMDA%'

UPDATE S SET notifySms = 'Y'
FROM REMITTRAN R
INNER JOIN TRANSENDERS S ON S.TRANID = R.ID
WHERE R.UPLOADLOGID IN (

)


select * from fastmoneypro_account.dbo.ac_master where acct_num = '8090000029'
select * from fastmoneypro_account.dbo.tran_master where acc_num = '8090000029'


select pagentcomm,* from remittrantemp where pcountry in ('pakistan')
and cast(createddate as date) = '2020-03-23'

SELECT * FROM CUSTOMER_DEPOSIT_LOGS WHERE TRANDATE = '2020-02-15'
SELECT WALLETACCOUNTNO,* FROM CUSTOMERMASTER WHERE CUSTOMERID=33749

SELECT ACCT_NUM, ACCT_NAME 
INTO #TEMP
FROM FASTMONEYPRO_ACCOUNT.DBO.AC_MASTER A(NOLOCK)
WHERE ACCT_RPT_CODE = 'CA'

SELECT DEPOSIT_AMT = CASE WHEN PART_TRAN_TYPE = 'DR' THEN TRAN_AMT* FROM FASTMONEYPRO_ACCOUNT.DBO.TRAN_MASTER WHERE ACC_NUM = '802400033748'

SELECT * FROM (
SELECT CAST(TRAN_DATE AS DATE) TRAN_DATE, DEPOSIT_AMT = SUM(CASE WHEN PART_TRAN_TYPE = 'CR' THEN TRAN_AMT ELSE 0 END),
				SENT_AMT = SUM(CASE WHEN PART_TRAN_TYPE = 'CR' THEN TRAN_AMT ELSE 0 END)
FROM #TEMP T
INNER JOIN FASTMONEYPRO_ACCOUNT.DBO.TRAN_MASTER M (NOLOCK) ON M.ACC_NUM = T.ACCT_NUM
WHERE M.TRAN_DATE >= '2020-02-15'
GROUP BY CAST(TRAN_DATE AS DATE)
)X
WHERE DEPOSIT_AMT <> SENT_AMT

SELECT * FROM FASTMONEYPRO_ACCOUNT.DBO.TRAN_MASTER WHERE REF_NUM = '273846'
SELECT * FROM FASTMONEYPRO_ACCOUNT.DBO.TRAN_MASTERDETAIL WHERE REF_NUM = '273846'
