



ALTER FUNCTION [dbo].[FNAGetCustomerAvailableBalance_New](@CUSTOMERID BIGINT)
RETURNS MONEY
AS  
BEGIN
	DECLARE @AVAILABLEBALANCE MONEY, @PENDINGMAPPING MONEY, @PENDINGTRANSACTION MONEY

	SELECT @AVAILABLEBALANCE = AVAILABLEBALANCE 
	FROM CUSTOMERMASTER (NOLOCK)
	WHERE CUSTOMERID = @CUSTOMERID

	SELECT @PENDINGMAPPING = SUM(DEPOSITAMOUNT) FROM CUSTOMER_DEPOSIT_LOGS (NOLOCK)
	WHERE CUSTOMERID = @CUSTOMERID
	AND ISSKIPPED = 0
	AND APPROVEDBY IS NULL

	RETURN ISNULL(@AVAILABLEBALANCE,0) + ISNULL(@PENDINGMAPPING,0) 
END





