------------bank Singapore
IF OBJECT_ID('tempdb..#TempBankSingapore') IS NOT NULL
			DROP TABLE #TempBankSingapore

SELECT * INTO #TempBankSingapore
FROM
(
	SELECT '6500001' BANK_CODE ,'DBS Bank' BANK_NAME UNION ALL
	SELECT '6500002' BANK_CODE ,'OCBC Bank' BANK_NAME UNION ALL
	SELECT '6500003' BANK_CODE ,'UOB Bank' BANK_NAME UNION ALL
	SELECT '6500004' BANK_CODE ,'POSB Bank' BANK_NAME UNION ALL
	SELECT '6500005' BANK_CODE ,'Bank of Singapore' BANK_NAME UNION ALL
	SELECT '6500006' BANK_CODE ,'HSBC Bank' BANK_NAME UNION ALL
	SELECT '6500007' BANK_CODE ,'Standard Chartered Bank' BANK_NAME UNION ALL
	SELECT '6500008' BANK_CODE ,'Malayan Banking (Maybank)' BANK_NAME UNION ALL
	SELECT '6500009' BANK_CODE ,'State Bank of India' BANK_NAME UNION ALL
	SELECT '6500011' BANK_CODE ,'Bank of China' BANK_NAME UNION ALL
	SELECT '6500013' BANK_CODE ,'Citibank' BANK_NAME UNION ALL
	SELECT '6500014' BANK_CODE ,'ANZ Bank' BANK_NAME UNION ALL
	SELECT '6500015' BANK_CODE ,'The Bank of Tokyo-Mitsubishi UFJ' BANK_NAME UNION ALL
	SELECT '6500016' BANK_CODE ,'BNP Paribas' BANK_NAME UNION ALL
	SELECT '6500017' BANK_CODE ,'CIMB Bank' BANK_NAME UNION ALL
	SELECT '6500018' BANK_CODE ,'Deutsche Bank' BANK_NAME UNION ALL
	SELECT '6500019' BANK_CODE ,'Far Eastern Bank' BANK_NAME UNION ALL
	SELECT '6500020' BANK_CODE ,'HL Bank' BANK_NAME UNION ALL
	SELECT '6500021' BANK_CODE ,'Mizuho Bank' BANK_NAME UNION ALL
	SELECT '6500022' BANK_CODE ,'RHB Bank' BANK_NAME UNION ALL
	SELECT '6500023' BANK_CODE ,'Sumitomo Mitsui Banking Corporation' BANK_NAME UNION ALL
	SELECT '6500024' BANK_CODE ,'BANGKOK BANK PUBLIC COMPANY LIMITED' BANK_NAME UNION ALL
	SELECT '6500025' BANK_CODE ,'BANK OF AMERICA' BANK_NAME UNION ALL
	SELECT '6500026' BANK_CODE ,'BANK OF EAST ASIA LTD' BANK_NAME UNION ALL
	SELECT '6500027' BANK_CODE ,'BANK OF INDIA' BANK_NAME UNION ALL
	SELECT '6500028' BANK_CODE ,'CHINATRUST COMMERCIAL BANK CO LTD' BANK_NAME UNION ALL
	SELECT '6500029' BANK_CODE ,'COMMERZBANK AKTIENGESELLSCHAFT' BANK_NAME UNION ALL
	SELECT '6500030' BANK_CODE ,'CréDIT AGRICOLE CORPORATE AND INVESTMENT BANK' BANK_NAME UNION ALL
	SELECT '6500031' BANK_CODE ,'DnB BANK ASA' BANK_NAME UNION ALL
	SELECT '6500032' BANK_CODE ,'FIRST COMMERCIAL BANK' BANK_NAME UNION ALL
	SELECT '6500033' BANK_CODE ,'INDIAN BANK' BANK_NAME UNION ALL
	SELECT '6500034' BANK_CODE ,'INDIAN OVERSEAS BANK' BANK_NAME UNION ALL
	SELECT '6500035' BANK_CODE ,'INTESA SANPAOLO' BANK_NAME UNION ALL
	SELECT '6500036' BANK_CODE ,'KOREA EXCHANGE BANK' BANK_NAME UNION ALL
	SELECT '6500037' BANK_CODE ,'NATIONAL AUSTRALIA BANK LTD' BANK_NAME UNION ALL
	SELECT '6500038' BANK_CODE ,'NORDEA BANK FINLAND PLC' BANK_NAME UNION ALL
	SELECT '6500039' BANK_CODE ,'PT BANK NEGARA INDONESIA (PERSERO)' BANK_NAME UNION ALL
	SELECT '6500040' BANK_CODE ,'SKANDINAVISKA ENSKILDA BANKEN' BANK_NAME UNION ALL
	SELECT '6500041' BANK_CODE ,'SOCIETE GENERALE' BANK_NAME UNION ALL
	SELECT '6500042' BANK_CODE ,'SVENSKA HANDELSBANKEN' BANK_NAME UNION ALL
	SELECT '6500043' BANK_CODE ,'UBS AG' BANK_NAME UNION ALL
	SELECT '6500044' BANK_CODE ,'UCO BANK' BANK_NAME UNION ALL
	SELECT '6500045' BANK_CODE ,'Qatar National Bank SAQ' BANK_NAME UNION ALL
	SELECT '6500001' BANK_CODE ,'DBS Bank' BANK_NAME UNION ALL
	SELECT '6500002' BANK_CODE ,'OCBC Bank' BANK_NAME UNION ALL
	SELECT '6500003' BANK_CODE ,'UOB Bank' BANK_NAME UNION ALL
	SELECT '6500004' BANK_CODE ,'POSB Bank' BANK_NAME UNION ALL
	SELECT '6500006' BANK_CODE ,'HSBC Bank' BANK_NAME UNION ALL
	SELECT '6500007' BANK_CODE ,'Standard Chartered Bank' BANK_NAME UNION ALL
	SELECT '6500008' BANK_CODE ,'Malayan Banking (Maybank)' BANK_NAME UNION ALL
	SELECT '6500011' BANK_CODE ,'Bank of China' BANK_NAME UNION ALL
	SELECT '6500013' BANK_CODE ,'Citibank' BANK_NAME UNION ALL
	SELECT '6500014' BANK_CODE ,'ANZ Bank' BANK_NAME UNION ALL
	SELECT '6500015' BANK_CODE ,'The Bank of Tokyo-Mitsubishi UFJ' BANK_NAME UNION ALL
	SELECT '6500016' BANK_CODE ,'BNP Paribas' BANK_NAME UNION ALL
	SELECT '6500017' BANK_CODE ,'CIMB Bank' BANK_NAME UNION ALL
	SELECT '6500018' BANK_CODE ,'Deutsche Bank' BANK_NAME UNION ALL
	SELECT '6500020' BANK_CODE ,'HL Bank' BANK_NAME UNION ALL
	SELECT '6500021' BANK_CODE ,'Mizuho Bank' BANK_NAME UNION ALL
	SELECT '6500022' BANK_CODE ,'RHB Bank' BANK_NAME UNION ALL
	SELECT '6500023' BANK_CODE ,'Sumitomo Mitsui Banking Corporation' BANK_NAME
)x
DELETE b 
FROM #TempBankSingapore b
INNER JOIN dbo.API_BANK_LIST A ON A.BANK_CODE1=b.BANK_CODE

INSERT INTO API_BANK_LIST(API_PARTNER_ID,BANK_NAME,BANK_CODE1,BANK_STATE,BANK_DISTRICT,BANK_ADDRESS,BANK_PHONE
,BANK_EMAIL,SUPPORT_CURRENCY,BANK_COUNTRY,PAYMENT_TYPE_ID,IS_ACTIVE)
SELECT 394450, BANK_NAME, BANK_CODE, NULL, NULL, NULL, NULL, NULL, NULL, 'SINGAPORE', 2, 1 FROM #TempBankSingapore



---------------- cash 
IF OBJECT_ID('tempdb..#TempCashSINGAPORE') IS NOT NULL
			DROP TABLE #TempCashSINGAPORE

SELECT * INTO #TempCashSINGAPORE
FROM
(
	SELECT 'DBS Bank' BANK_NAME, '6500001' BANK_CODE UNION ALL
	SELECT 'ANZ Bank' BANK_NAME, '6500014' BANK_CODE
)x

DELETE b 
FROM #TempCashSINGAPORE b
INNER JOIN dbo.API_BANK_LIST A ON A.BANK_CODE1=b.BANK_CODE AND A.PAYMENT_TYPE_ID=1

INSERT INTO API_BANK_LIST(API_PARTNER_ID,BANK_NAME,BANK_CODE1,BANK_STATE,BANK_DISTRICT,BANK_ADDRESS,BANK_PHONE
,BANK_EMAIL,SUPPORT_CURRENCY,BANK_COUNTRY,PAYMENT_TYPE_ID,IS_ACTIVE)
SELECT 394450, BANK_NAME, BANK_CODE, NULL, NULL, NULL, NULL, NULL, NULL, 'SINGAPORE', 1, 1 FROM #TempCashSINGAPORE

