
----- Bank Of Pakistan
IF OBJECT_ID('tempdb..#TempBankPakistan') IS NOT NULL
			DROP TABLE #TempBankPakistan

SELECT * INTO #TempBankPakistan
FROM
(
	SELECT 'Waseela' BANK_NAME, '920001' BANK_CODE UNION ALL
	SELECT 'NATIONAL BANK OF PAKISTAN' BANK_NAME, '920002' BANK_CODE UNION ALL
	SELECT 'BANK OF PUNJAB' BANK_NAME, '920003' BANK_CODE UNION ALL
	SELECT 'ALLIED BANK LIMITED' BANK_NAME, '920004' BANK_CODE UNION ALL
	SELECT 'Habib Bank Ltd' BANK_NAME, '920005' BANK_CODE UNION ALL
	SELECT 'MUSLIM COMERCIAL BANK' BANK_NAME, '920006' BANK_CODE UNION ALL
	SELECT 'Askari Bank Limited' BANK_NAME, '920007' BANK_CODE UNION ALL
	SELECT 'BANK ALHABIB' BANK_NAME, '920008' BANK_CODE UNION ALL
	SELECT 'BANK ALFALAH LIMITED' BANK_NAME, '920009' BANK_CODE UNION ALL
	SELECT 'Burj Bank' BANK_NAME, '920010' BANK_CODE UNION ALL
	SELECT 'Dubai Islamic Bank Ltd' BANK_NAME, '920011' BANK_CODE UNION ALL
	SELECT 'FAYSAL BANK LIMITED' BANK_NAME, '920012' BANK_CODE UNION ALL
	SELECT 'HABIB METROPOLITAN BANK' BANK_NAME, '920013' BANK_CODE UNION ALL
	SELECT 'MEEZAN BANK LIMITED' BANK_NAME, '920014' BANK_CODE UNION ALL
	SELECT 'SAMBA BANK' BANK_NAME, '920015' BANK_CODE UNION ALL
	SELECT 'SILK BANK' BANK_NAME, '920016' BANK_CODE UNION ALL
	SELECT 'SONERI BANK LIMITED' BANK_NAME, '920017' BANK_CODE UNION ALL
	SELECT 'NIB BANK' BANK_NAME, '920018' BANK_CODE UNION ALL
	SELECT 'CITI BANK' BANK_NAME, '920020' BANK_CODE UNION ALL
	SELECT 'Sindh Bank' BANK_NAME, '920021' BANK_CODE UNION ALL
	SELECT 'KASB BANK LIMITED' BANK_NAME, '920022' BANK_CODE UNION ALL
	SELECT 'FIRST WOMEN BANK LIMITED' BANK_NAME, '920023' BANK_CODE UNION ALL
	SELECT 'BARCLAYS BANK LIMITED' BANK_NAME, '920024' BANK_CODE UNION ALL
	SELECT 'Oman International Bank' BANK_NAME, '920025' BANK_CODE UNION ALL
	SELECT 'SUMMIT BANK' BANK_NAME, '920026' BANK_CODE UNION ALL
	SELECT 'BANK ISLAMI PAKISTAN LIMITED' BANK_NAME, '920027' BANK_CODE UNION ALL
	SELECT 'HSBC Bank Limited' BANK_NAME, '920028' BANK_CODE UNION ALL
	SELECT 'UNITED BANK LIMITED' BANK_NAME, '920029' BANK_CODE UNION ALL
	SELECT 'Al Barka Bank' BANK_NAME, '920030' BANK_CODE UNION ALL
	SELECT 'Standard Chartered Bank' BANK_NAME, '920031' BANK_CODE UNION ALL
	SELECT 'BANK OF KHYBER' BANK_NAME, '920032' BANK_CODE UNION ALL
	SELECT 'BANK OF AZAD JAMMU KASHMIR' BANK_NAME, '920033' BANK_CODE UNION ALL
	SELECT 'FIRST MICRO FINANCE BANK LIMITED' BANK_NAME, '920034' BANK_CODE UNION ALL
	SELECT 'Model Bank' BANK_NAME, '920035' BANK_CODE UNION ALL
	SELECT 'JAHANGIR SIDDIQUI BANK LTD' BANK_NAME, '920036' BANK_CODE UNION ALL
	SELECT 'DEUTSCHE BANK' BANK_NAME, '920037' BANK_CODE UNION ALL
	SELECT 'Tameer microfinance bank' BANK_NAME, '920038' BANK_CODE UNION ALL
	SELECT 'Apna Microfinance Bank' BANK_NAME, '920039' BANK_CODE UNION ALL
	SELECT 'U Microfinance Bank' BANK_NAME, '920040' BANK_CODE UNION ALL
	SELECT 'ICBC' BANK_NAME, '920041' BANK_CODE UNION ALL
	SELECT 'NRSP' BANK_NAME, '920042' BANK_CODE UNION ALL
	SELECT 'MCB Islamic Bank' BANK_NAME, '920043' BANK_CODE UNION ALL
	SELECT 'Bank Of Tokyo Mitsubishi Ufj Ltd' BANK_NAME, '920045' BANK_CODE UNION ALL
	SELECT 'Emaan Islamic Banking Silkbank' BANK_NAME, '920046' BANK_CODE UNION ALL
	SELECT 'Faisal Islamic Bank Of Bahrain' BANK_NAME, '920047' BANK_CODE UNION ALL
	SELECT 'FINCA Micro Finance BankLimited' BANK_NAME, '920048' BANK_CODE UNION ALL
	SELECT 'SME Bank Ltd' BANK_NAME, '920049' BANK_CODE UNION ALL
	SELECT 'ZARAI TARAQIATI BANK LTD' BANK_NAME, '920050' BANK_CODE UNION ALL
	SELECT 'THE PUNJAB PROVINCIAL COOPERATIVE BANK LTD' BANK_NAME, '920044' BANK_CODE
)x

DELETE b 
FROM #TempBankPakistan b
INNER JOIN dbo.API_BANK_LIST A ON A.BANK_CODE1=b.BANK_CODE

INSERT INTO API_BANK_LIST(API_PARTNER_ID,BANK_NAME,BANK_CODE1,BANK_STATE,BANK_DISTRICT,BANK_ADDRESS,BANK_PHONE
,BANK_EMAIL,SUPPORT_CURRENCY,BANK_COUNTRY,PAYMENT_TYPE_ID,IS_ACTIVE)
SELECT 394450, BANK_NAME, BANK_CODE, NULL, NULL, NULL, NULL, NULL, NULL, 'PAKISTAN', 2, 1 FROM #TempBankPakistan

------ bank for cash pickup pakistan

IF NOT EXISTS(SELECT 'd' FROM dbo.API_BANK_LIST WHERE BANK_CODE1='CPBAFL')
BEGIN
    INSERT INTO API_BANK_LIST(API_PARTNER_ID,BANK_NAME,BANK_CODE1,BANK_STATE,BANK_DISTRICT,BANK_ADDRESS,BANK_PHONE
	,BANK_EMAIL,SUPPORT_CURRENCY,BANK_COUNTRY,PAYMENT_TYPE_ID,IS_ACTIVE)
	SELECT 394450, 'Bank of Alfalah', 'CPBAFL', NULL, NULL, NULL, NULL, NULL, NULL, 'PAKISTAN', 1, 1
END
IF NOT EXISTS(SELECT 'd' FROM dbo.API_BANK_LIST WHERE BANK_CODE1='CPBOP')
BEGIN
    INSERT INTO API_BANK_LIST(API_PARTNER_ID,BANK_NAME,BANK_CODE1,BANK_STATE,BANK_DISTRICT,BANK_ADDRESS,BANK_PHONE
	,BANK_EMAIL,SUPPORT_CURRENCY,BANK_COUNTRY,PAYMENT_TYPE_ID,IS_ACTIVE)
	SELECT 394450, 'Bank Of Punjab', 'CPBOP', NULL, NULL, NULL, NULL, NULL, NULL, 'PAKISTAN', 1, 1
END
IF NOT EXISTS(SELECT 'd' FROM dbo.API_BANK_LIST WHERE BANK_CODE1='CPMCB')
BEGIN
    INSERT INTO API_BANK_LIST(API_PARTNER_ID,BANK_NAME,BANK_CODE1,BANK_STATE,BANK_DISTRICT,BANK_ADDRESS,BANK_PHONE
	,BANK_EMAIL,SUPPORT_CURRENCY,BANK_COUNTRY,PAYMENT_TYPE_ID,IS_ACTIVE)
	SELECT 394450, 'MCB Bank Limited', 'CPMCB', NULL, NULL, NULL, NULL, NULL, NULL, 'PAKISTAN', 1, 1
END


RETURN
------------- wallet for pakistan
IF NOT EXISTS(SELECT 'd' FROM dbo.API_BANK_LIST WHERE BANK_CODE1='EWMBC')
BEGIN
    INSERT INTO API_BANK_LIST(API_PARTNER_ID,BANK_NAME,BANK_CODE1,BANK_STATE,BANK_DISTRICT,BANK_ADDRESS,BANK_PHONE
	,BANK_EMAIL,SUPPORT_CURRENCY,BANK_COUNTRY,PAYMENT_TYPE_ID,IS_ACTIVE)
	SELECT 394450, 'Jazzcash', NULL, NULL, NULL, NULL, NULL, NULL, 'PAKISTAN', 1, 1
END
IF NOT EXISTS(SELECT 'd' FROM dbo.API_BANK_LIST WHERE BANK_CODE1='EWBAFL')
BEGIN
    INSERT INTO API_BANK_LIST(API_PARTNER_ID,BANK_NAME,BANK_CODE1,BANK_STATE,BANK_DISTRICT,BANK_ADDRESS,BANK_PHONE
	,BANK_EMAIL,SUPPORT_CURRENCY,BANK_COUNTRY,PAYMENT_TYPE_ID,IS_ACTIVE)
	SELECT 394450, 'Ewallet Bank Alfalah', 'EWBAFL', NULL, NULL, NULL, NULL, NULL, NULL, 'PAKISTAN', 1, 1
END


--------- biller code list for pakistan
IF OBJECT_ID('tempdb..#TempBillerPakistan') IS NOT NULL
			DROP TABLE #TempBillerPakistan

SELECT * INTO #TempBillerPakistan
FROM(
	SELECT 'Karachi Electric Supply Company' BANK_NAME, 'KESC' BANK_CODE, 'KESC' Currency UNION ALL
	SELECT 'Karachi Electric' BANK_NAME, 'KE' BANK_CODE, 'KE' Currency UNION ALL
	SELECT 'Gujranwala Electric Supply Company Limited' BANK_NAME, 'GEPCO' BANK_CODE, 'GEPCO' Currency UNION ALL
	SELECT 'Hyderabad Electric Supply Company' BANK_NAME, 'HESCO' BANK_CODE, 'HESCO' Currency UNION ALL
	SELECT 'Lahore Electric Supply Company' BANK_NAME, 'LESCO' BANK_CODE, 'LESCO' Currency UNION ALL
	SELECT 'Multan Electric Power Company' BANK_NAME, 'MEPCO' BANK_CODE, 'MEPCO' Currency UNION ALL
	SELECT 'Peshawar Electric Power Supply Company' BANK_NAME, 'PESCO' BANK_CODE, 'PESCO' Currency UNION ALL
	SELECT 'Sialkot Electric Power Supply Company' BANK_NAME, 'SPECO' BANK_CODE, 'SPECO' Currency UNION ALL
	SELECT 'Sui Sothern Gas Company' BANK_NAME, 'SSGC' BANK_CODE, 'SSGC' Currency UNION ALL
	SELECT 'Sui Northern Gas Pipelines Limited' BANK_NAME, 'SNGPL' BANK_CODE, 'SNGPL' Currency UNION ALL
	SELECT 'Saf' BANK_NAME, 'SAF' BANK_CODE, 'SAF' Currency UNION ALL
	SELECT 'Karachi Water And Sewerage Board' BANK_NAME, 'KWSB' BANK_CODE, 'KWSB' Currency UNION ALL
	SELECT 'Water and Sanitation Agency' BANK_NAME, 'FWASA' BANK_CODE, 'FWASA' Currency UNION ALL
	SELECT 'Pakistan Tele Communication Limited' BANK_NAME, 'PTCL' BANK_CODE, 'PTCL' Currency
)x


DELETE b 
FROM #TempBillerPakistan b
INNER JOIN dbo.API_BANK_LIST A ON A.BANK_CODE1=b.BANK_CODE

INSERT INTO API_BANK_LIST(API_PARTNER_ID,BANK_NAME,BANK_CODE1,BANK_STATE,BANK_DISTRICT,BANK_ADDRESS,BANK_PHONE
,BANK_EMAIL,SUPPORT_CURRENCY,BANK_COUNTRY,PAYMENT_TYPE_ID,IS_ACTIVE)
SELECT 394450, BANK_NAME, BANK_CODE, NULL, NULL, NULL, NULL, NULL, Currency, 'PAKISTAN', 2, 1 FROM #TempBillerPakistan
