----- Bank Of Indonesia
IF OBJECT_ID('tempdb..#TempBankIndonesia') IS NOT NULL
			DROP TABLE #TempBankIndonesia


SELECT * INTO #TempBankIndonesia
FROM(
	SELECT 'BANK AGRONIAGA' BANK_NAME, '494' BANK_CODE UNION ALL
	SELECT 'BANK ARTOS INDONESIA' BANK_NAME, '542' BANK_CODE UNION ALL
	SELECT 'BANK BENGKULU' BANK_NAME, '133' BANK_CODE UNION ALL
	SELECT 'BANK UOB INDONESIA' BANK_NAME, '23' BANK_CODE UNION ALL
	SELECT 'BANK BUKOPIN' BANK_NAME, '441' BANK_CODE UNION ALL
	SELECT 'Bank ICB Bumiputera Indonesia' BANK_NAME, '485' BANK_CODE UNION ALL
	SELECT 'BANK BTPN' BANK_NAME, '213' BANK_CODE UNION ALL
	SELECT 'BANK CAPITAL' BANK_NAME, '54' BANK_CODE UNION ALL
	SELECT 'BANK COMMONWEALTH' BANK_NAME, '950' BANK_CODE UNION ALL
	SELECT 'BANK DANAMON' BANK_NAME, '11' BANK_CODE UNION ALL
	SELECT 'BANK DKI' BANK_NAME, '111' BANK_CODE UNION ALL
	SELECT 'BANK PUNDI' BANK_NAME, '558' BANK_CODE UNION ALL
	SELECT 'BANK GANESHA' BANK_NAME, '161' BANK_CODE UNION ALL
	SELECT 'Bank Woori Saudara' BANK_NAME, '212' BANK_CODE UNION ALL
	SELECT 'BANK HSBC' BANK_NAME, '41' BANK_CODE UNION ALL
	SELECT 'BANK INDEX' BANK_NAME, '555' BANK_CODE UNION ALL
	SELECT 'BANK INA PERDANA' BANK_NAME, '513' BANK_CODE UNION ALL
	SELECT 'BII Maybank' BANK_NAME, '16' BANK_CODE UNION ALL
	SELECT 'Bank Jabar Banten' BANK_NAME, '110' BANK_CODE UNION ALL
	SELECT 'BANK JATENG' BANK_NAME, '113' BANK_CODE UNION ALL
	SELECT 'BANK JATIM' BANK_NAME, '114' BANK_CODE UNION ALL
	SELECT 'BANK KESAWAN' BANK_NAME, '167' BANK_CODE UNION ALL
	SELECT 'BANK LAMPUNG' BANK_NAME, '121' BANK_CODE UNION ALL
	SELECT 'BANK MALUKU' BANK_NAME, '131' BANK_CODE UNION ALL
	SELECT 'BANK MANDIRI' BANK_NAME, '8' BANK_CODE UNION ALL
	SELECT 'BANK MAYAPADA INTERNASIONAL' BANK_NAME, '97' BANK_CODE UNION ALL
	SELECT 'BANK MAYORA' BANK_NAME, '553' BANK_CODE UNION ALL
	SELECT 'BANK MEGA' BANK_NAME, '426' BANK_CODE UNION ALL
	SELECT 'BANK MESTIKA' BANK_NAME, '151' BANK_CODE UNION ALL
	SELECT 'BANK MUAMALAT' BANK_NAME, '147' BANK_CODE UNION ALL
	SELECT 'BANK NAGARI' BANK_NAME, '118' BANK_CODE UNION ALL
	SELECT 'BANK NEGARA INDONESIA' BANK_NAME, '9' BANK_CODE UNION ALL
	SELECT 'BANK CIMB NIAGA' BANK_NAME, '22' BANK_CODE UNION ALL
	SELECT 'BANK OCBC NISP' BANK_NAME, '28' BANK_CODE UNION ALL
	SELECT 'BANK NUSA TENGGARA BARAT' BANK_NAME, '128' BANK_CODE UNION ALL
	SELECT 'BANK NUSA TENGGARA TIMUR' BANK_NAME, '130' BANK_CODE UNION ALL
	SELECT 'BANK NUSANTARA PARAHYANGAN' BANK_NAME, '145' BANK_CODE UNION ALL
	SELECT 'BANK PANIN' BANK_NAME, '19' BANK_CODE UNION ALL
	SELECT 'BANK PAPUA' BANK_NAME, '132' BANK_CODE UNION ALL
	SELECT 'BANK PERMATA' BANK_NAME, '13' BANK_CODE UNION ALL
	SELECT 'BANK RAKYAT INDONESIA' BANK_NAME, '2' BANK_CODE UNION ALL
	SELECT 'BANK RIAU' BANK_NAME, '119' BANK_CODE UNION ALL
	SELECT 'BANK SULUT' BANK_NAME, '127' BANK_CODE UNION ALL
	SELECT 'Bank Sumsel Babel' BANK_NAME, '120' BANK_CODE UNION ALL
	SELECT 'BANK SUMUT' BANK_NAME, '117' BANK_CODE UNION ALL
	SELECT 'BANK SWADESI' BANK_NAME, '146' BANK_CODE UNION ALL
	SELECT 'BANK SYARIAH MANDIRI' BANK_NAME, '451' BANK_CODE UNION ALL
	SELECT 'BANK SYARIAH MEGA' BANK_NAME, '506' BANK_CODE UNION ALL
	SELECT 'BPD ACEH' BANK_NAME, '116' BANK_CODE UNION ALL
	SELECT 'BANK BPD BALI' BANK_NAME, '129' BANK_CODE UNION ALL
	SELECT 'BANK BPD DIY' BANK_NAME, '112' BANK_CODE UNION ALL
	SELECT 'BPD JAMBI' BANK_NAME, '115' BANK_CODE UNION ALL
	SELECT 'BPD KALIMANTAN BARAT' BANK_NAME, '123' BANK_CODE UNION ALL
	SELECT 'BPD KALIMANTAN SELATAN' BANK_NAME, '122' BANK_CODE UNION ALL
	SELECT 'BPD KALIMANTAN TENGAH' BANK_NAME, '125' BANK_CODE UNION ALL
	SELECT 'BPD KALIMANTAN TIMUR' BANK_NAME, '124' BANK_CODE UNION ALL
	SELECT 'BPD SULAWESI TENGGARA' BANK_NAME, '135' BANK_CODE UNION ALL
	SELECT 'BPD SULAWESI SELATAN' BANK_NAME, '126' BANK_CODE UNION ALL
	SELECT 'BANK SULTENG' BANK_NAME, '134' BANK_CODE UNION ALL
	SELECT 'BANK SINARMAS' BANK_NAME, '153' BANK_CODE UNION ALL
	SELECT 'BANK KESEJAHTERAAN' BANK_NAME, '535' BANK_CODE UNION ALL
	SELECT 'BANK BTN' BANK_NAME, '200' BANK_CODE UNION ALL
	SELECT 'CITIBANK (Indonesia)' BANK_NAME, '31' BANK_CODE UNION ALL
	SELECT 'STANDARD CHARTERED BANK' BANK_NAME, '50' BANK_CODE UNION ALL
	SELECT 'BANK JTRUST INDONESIA' BANK_NAME, '95' BANK_CODE UNION ALL
	SELECT 'BANK BRI SYARIAH' BANK_NAME, '422' BANK_CODE UNION ALL
	SELECT 'BANK JABAR SYARIAH' BANK_NAME, '425' BANK_CODE UNION ALL
	SELECT 'RABOBANK' BANK_NAME, '89' BANK_CODE UNION ALL
	SELECT 'BCA' BANK_NAME, '624' BANK_CODE UNION ALL
	SELECT 'BNI Syariah' BANK_NAME, '626' BANK_CODE UNION ALL
	SELECT 'Bukopin Syariah' BANK_NAME, '630' BANK_CODE UNION ALL
	SELECT 'Indomonex' BANK_NAME, '600' BANK_CODE UNION ALL
	SELECT 'Jasa Jakarta' BANK_NAME, '601' BANK_CODE UNION ALL
	SELECT 'Maspion' BANK_NAME, '603' BANK_CODE UNION ALL
	SELECT 'Victoria' BANK_NAME, '607' BANK_CODE UNION ALL
	SELECT 'Bank Antar Daerah' BANK_NAME, '609' BANK_CODE UNION ALL
	SELECT 'Chinatrust Indonesia' BANK_NAME, '610' BANK_CODE UNION ALL
	SELECT 'Windu Kentjana International' BANK_NAME, '611' BANK_CODE UNION ALL
	SELECT 'Bank Of Tokyo Mitsubishi' BANK_NAME, '632' BANK_CODE UNION ALL
	SELECT 'BANK ANZ' BANK_NAME, '622' BANK_CODE UNION ALL
	SELECT 'TCASH' BANK_NAME, '911' BANK_CODE UNION ALL
	SELECT 'Bank Artha Graha Internasional' BANK_NAME, '37' BANK_CODE UNION ALL
	SELECT 'Bank DBS' BANK_NAME, '46' BANK_CODE UNION ALL
	SELECT 'Bank ANZ PANIN' BANK_NAME, '61' BANK_CODE UNION ALL
	SELECT 'Bank BOC Indonesia' BANK_NAME, '69' BANK_CODE UNION ALL
	SELECT 'Bank Hana' BANK_NAME, '484' BANK_CODE UNION ALL
	SELECT 'Bank Royal Indonesia' BANK_NAME, '501' BANK_CODE UNION ALL
	SELECT 'Bank Nobubank' BANK_NAME, '503' BANK_CODE UNION ALL
	SELECT 'Bank Woori Indonesia' BANK_NAME, '68' BANK_CODE UNION ALL
	SELECT 'Bank Victoria Syariah' BANK_NAME, '405' BANK_CODE UNION ALL
	SELECT 'Panin Bank Syariah' BANK_NAME, '517' BANK_CODE UNION ALL
	SELECT 'Bank Sahabat Sampoerna' BANK_NAME, '523' BANK_CODE UNION ALL
	SELECT 'Bank Eka Bumi Arta' BANK_NAME, '699' BANK_CODE UNION ALL
	SELECT 'Bank Agris' BANK_NAME, '945' BANK_CODE UNION ALL
	SELECT 'JP Morgan Chase' BANK_NAME, '32' BANK_CODE UNION ALL
	SELECT 'BANK OF AMERICA (Indonesia)' BANK_NAME, '33' BANK_CODE UNION ALL
	SELECT 'Sumitomo Mitsui Indonesia' BANK_NAME, '45' BANK_CODE UNION ALL
	SELECT 'Resona Perdania' BANK_NAME, '47' BANK_CODE UNION ALL
	SELECT 'Mizuho Indonesia' BANK_NAME, '48' BANK_CODE UNION ALL
	SELECT 'Royal Bank Of Scotland' BANK_NAME, '52' BANK_CODE UNION ALL
	SELECT 'BNP Paribas Indonesia' BANK_NAME, '57' BANK_CODE UNION ALL
	SELECT 'Korea Exchange' BANK_NAME, '59' BANK_CODE UNION ALL
	SELECT 'Deutsche Bank' BANK_NAME, '67' BANK_CODE UNION ALL
	SELECT 'Metro Ekspress' BANK_NAME, '152' BANK_CODE UNION ALL
	SELECT 'ICBC Indonesia' BANK_NAME, '164' BANK_CODE UNION ALL
	SELECT 'Bank Bisnis International' BANK_NAME, '459' BANK_CODE UNION ALL
	SELECT 'Andara' BANK_NAME, '466' BANK_CODE UNION ALL
	SELECT 'Yudha Bhakti' BANK_NAME, '490' BANK_CODE UNION ALL
	SELECT 'Mitraniaga' BANK_NAME, '491' BANK_CODE UNION ALL
	SELECT 'Prima Master' BANK_NAME, '520' BANK_CODE UNION ALL
	SELECT 'Liman' BANK_NAME, '526' BANK_CODE UNION ALL
	SELECT 'Anglomas' BANK_NAME, '531' BANK_CODE UNION ALL
	SELECT 'Purba Danarta' BANK_NAME, '547' BANK_CODE UNION ALL
	SELECT 'Multiarta Sentosa' BANK_NAME, '548' BANK_CODE UNION ALL
	SELECT 'Centratama Nasional' BANK_NAME, '559' BANK_CODE UNION ALL
	SELECT 'Fama International' BANK_NAME, '562' BANK_CODE UNION ALL
	SELECT 'BANK MANTAP' BANK_NAME, '564' BANK_CODE UNION ALL
	SELECT 'Harda International' BANK_NAME, '567' BANK_CODE UNION ALL
	SELECT 'Maybank Syariah Indonesia' BANK_NAME, '947' BANK_CODE UNION ALL
	SELECT 'Bank Ekonomi' BANK_NAME, '87' BANK_CODE UNION ALL
	SELECT 'Bank Of China' BANK_NAME, '62001' BANK_CODE UNION ALL
	SELECT 'Bank Ekonomi Raharja' BANK_NAME, '62002' BANK_CODE UNION ALL
	SELECT 'Bank Windu Kentjana' BANK_NAME, '62003' BANK_CODE UNION ALL
	SELECT 'BANK KEB HANA' BANK_NAME, '62004' BANK_CODE UNION ALL
	SELECT 'MNC BANK' BANK_NAME, '62005' BANK_CODE UNION ALL
	SELECT 'Bank SBI Indonesia (Indomonex)' BANK_NAME, '62006' BANK_CODE UNION ALL
	SELECT 'BANK DINAR' BANK_NAME, '62007' BANK_CODE UNION ALL
	SELECT 'Bank BCA Syariah' BANK_NAME, '62008' BANK_CODE UNION ALL
	SELECT 'CNB' BANK_NAME, '62009' BANK_CODE UNION ALL
	SELECT 'BPR/LSB' BANK_NAME, '62010' BANK_CODE UNION ALL
	SELECT 'BPR KS' BANK_NAME, '62011' BANK_CODE UNION ALL
	SELECT 'BPR EKA' BANK_NAME, '62012' BANK_CODE UNION ALL
	SELECT 'INDOSAT (DOMPETKU)' BANK_NAME, '62013' BANK_CODE UNION ALL
	SELECT 'Bank CTBC Indonesia' BANK_NAME, '62014' BANK_CODE UNION ALL
	SELECT 'ATMB PLUS' BANK_NAME, '62015' BANK_CODE UNION ALL
	SELECT 'Bank BARCLAYS' BANK_NAME, '62525' BANK_CODE UNION ALL
	SELECT 'Bank BPR KS' BANK_NAME, '688' BANK_CODE
)x

DELETE b 
FROM #TempBankIndonesia b
INNER JOIN dbo.API_BANK_LIST A ON A.BANK_CODE1=b.BANK_CODE

INSERT INTO API_BANK_LIST(API_PARTNER_ID,BANK_NAME,BANK_CODE1,BANK_STATE,BANK_DISTRICT,BANK_ADDRESS,BANK_PHONE
,BANK_EMAIL,SUPPORT_CURRENCY,BANK_COUNTRY,PAYMENT_TYPE_ID,IS_ACTIVE)
SELECT 394450, BANK_NAME, BANK_CODE, NULL, NULL, NULL, NULL, NULL, NULL, 'INDONESIA', 2, 1 FROM #TempBankIndonesia

----- Bank For Cash Of Indonesia
IF NOT EXISTS(SELECT 'x' FROM dbo.API_BANK_LIST WHERE BANK_CODE1='CPPTPOS')
BEGIN
    INSERT INTO API_BANK_LIST(API_PARTNER_ID,BANK_NAME,BANK_CODE1,BANK_STATE,BANK_DISTRICT,BANK_ADDRESS,BANK_PHONE
	,BANK_EMAIL,SUPPORT_CURRENCY,BANK_COUNTRY,PAYMENT_TYPE_ID,IS_ACTIVE)
	SELECT 394450, 'POS Indonesia', 'CPPTPOS', NULL, NULL, NULL, NULL, NULL, NULL, 'INDONESIA', 1, 1 
END




------- E-Wallet Of Indonesia
IF OBJECT_ID('tempdb..#TempWalletIndonesia') IS NOT NULL
			DROP TABLE #TempWalletIndonesia

SELECT * INTO #TempWalletIndonesia

FROM
(
	SELECT 'Gopay (Gojek E-Money)' BANK_NAME,	'EWGOPAY' BANK_CODE UNION ALL
	SELECT 'Nobu E-Money (OVO)' BANK_NAME,	'EWNOVO' BANK_CODE  UNION ALL
	SELECT 'Permata E-Money (OVO)' BANK_NAME,	'EWPOVO' BANK_CODE  UNION ALL
	SELECT 'Dana E-Money' BANK_NAME,	'EWDANA' BANK_CODE  UNION ALL
	SELECT 'Link Aja' BANK_NAME,	'EWLAJA' BANK_CODE 
)x


DELETE BB 
FROM #TempWalletIndonesia BB
INNER JOIN dbo.API_BANK_LIST ABB
ON	BB.BANK_CODE=ABB.BANK_CODE1

INSERT INTO API_BANK_LIST
		(
			API_PARTNER_ID,BANK_NAME,BANK_CODE1,BANK_COUNTRY,PAYMENT_TYPE_ID,IS_ACTIVE
		)
SELECT		394450, BANK_NAME, BANK_CODE, 'INDONESIA', 13, 1 FROM #TempWalletIndonesia
