IF NOT EXISTS(SELECT 'x' FROM dbo.API_BANK_LIST WHERE BANK_CODE1='CPQBRU')
BEGIN
    INSERT INTO API_BANK_LIST(API_PARTNER_ID,BANK_NAME,BANK_CODE1,BANK_STATE,BANK_DISTRICT,BANK_ADDRESS,BANK_PHONE
	,BANK_EMAIL,SUPPORT_CURRENCY,BANK_COUNTRY,PAYMENT_TYPE_ID,IS_ACTIVE)
	SELECT 394450, 'Qiwi Bank / CONTACT', 'CPQBRU', NULL, NULL, NULL, NULL, NULL, NULL, 'RUSSIA', 1, 1
END