----- Bank Of Nepal
IF OBJECT_ID('tempdb..#TempBankNepal') IS NOT NULL
			DROP TABLE #TempBankNepal

SELECT * INTO #TempBankNepal
FROM
(
	SELECT 'Ace Development Bank Ltd' BANK_NAME, '977028' BANK_CODE UNION ALL
	SELECT 'Agricultural Development Bank' BANK_NAME, '977029' BANK_CODE UNION ALL
	SELECT 'Alpine Development Bank Ltd' BANK_NAME, '977030' BANK_CODE UNION ALL
	SELECT 'Annapurna Bikash Bank' BANK_NAME, '977031' BANK_CODE UNION ALL
	SELECT 'APEX DEVELOPMENT BANK LTD.' BANK_NAME, '977001' BANK_CODE UNION ALL
	SELECT 'Axel Bank' BANK_NAME, '977032' BANK_CODE UNION ALL
	SELECT 'Bageshwori Development Bank Ltd' BANK_NAME, '977033' BANK_CODE UNION ALL
	SELECT 'Bank of Asia Ltd' BANK_NAME, '977034' BANK_CODE UNION ALL
	SELECT 'BANK OF KATHMANDU' BANK_NAME, '977002' BANK_CODE UNION ALL
	SELECT 'BHRIKUTEE DEVELOPMENT BANK LTD.' BANK_NAME, '977013' BANK_CODE UNION ALL
	SELECT 'Biratlaxmi Bikas Bank Ltd' BANK_NAME, '977035' BANK_CODE UNION ALL
	SELECT 'Bishwa Bikash Bank Limited' BANK_NAME, '977036' BANK_CODE UNION ALL
	SELECT 'Business Universal Development Bank Ltd' BANK_NAME, '977037' BANK_CODE UNION ALL
	SELECT 'Century Commerical Bank Ltd' BANK_NAME, '977038' BANK_CODE UNION ALL
	SELECT 'CITIZENS BANK INTERNATIONAL LTD.' BANK_NAME, '977018' BANK_CODE UNION ALL
	SELECT 'CITY DEVELOPMENT BANK LIMITED' BANK_NAME, '977022' BANK_CODE UNION ALL
	SELECT 'Civil Bank Ltd.' BANK_NAME, '977039' BANK_CODE UNION ALL
	SELECT 'Clean Energy Development Bank Ltd' BANK_NAME, '977040' BANK_CODE UNION ALL
	SELECT 'Commerz and Trust Bank Nepal Ltd.' BANK_NAME, '977041' BANK_CODE UNION ALL
	SELECT 'DEVA BIKAS BANK LIMITED' BANK_NAME, '977004' BANK_CODE UNION ALL
	SELECT 'Ekata Bikas Bank' BANK_NAME, '977042' BANK_CODE UNION ALL
	SELECT 'Everest Bank Limited *' BANK_NAME, '977043' BANK_CODE UNION ALL
	SELECT 'Excel Development Bank Ltd' BANK_NAME, '977044' BANK_CODE UNION ALL
	SELECT 'Federal Bank' BANK_NAME, '977045' BANK_CODE UNION ALL
	SELECT 'Gandaki Bikas Bank Ltd' BANK_NAME, '977046' BANK_CODE UNION ALL
	SELECT 'Garima Bikas Bank Limited' BANK_NAME, '977047' BANK_CODE UNION ALL
	SELECT 'Gaurishankar Development Bank Ltd' BANK_NAME, '977048' BANK_CODE UNION ALL
	SELECT 'Global IME Bank Limited' BANK_NAME, '977049' BANK_CODE UNION ALL
	SELECT 'Grand Bank Nepal Ltd' BANK_NAME, '977050' BANK_CODE UNION ALL
	SELECT 'GREEN DEVELOPMENT BANK' BANK_NAME, '977008' BANK_CODE UNION ALL
	SELECT 'GUHESHWARI MERCHANT BANKING AND FINANCE LTD.' BANK_NAME, '977012' BANK_CODE UNION ALL
	SELECT 'Gulmi Bikas Bank Limited' BANK_NAME, '977051' BANK_CODE UNION ALL
	SELECT 'H and B Development Bank Limited' BANK_NAME, '977052' BANK_CODE UNION ALL
	SELECT 'Hamro Bikas Bank' BANK_NAME, '977053' BANK_CODE UNION ALL
	SELECT 'Himalayan Bank Limited' BANK_NAME, '977054' BANK_CODE UNION ALL
	SELECT 'Infrastructure Development Bank Ltd' BANK_NAME, '977055' BANK_CODE UNION ALL
	SELECT 'Innovative Development Bank Ltd' BANK_NAME, '977056' BANK_CODE UNION ALL
	SELECT 'International Development Bank' BANK_NAME, '977057' BANK_CODE UNION ALL
	SELECT 'Janata Bank Nepal Ltd' BANK_NAME, '977058' BANK_CODE UNION ALL
	SELECT 'JHIMRUK BIKAS BANK' BANK_NAME, '977015' BANK_CODE UNION ALL
	SELECT 'Jyoti Bikash Bank' BANK_NAME, '977059' BANK_CODE UNION ALL
	SELECT 'Kabeli Bikas Bank Ltd' BANK_NAME, '977060' BANK_CODE UNION ALL
	SELECT 'Kailash Bikas Bank Limited' BANK_NAME, '977061' BANK_CODE UNION ALL
	SELECT 'KAMANA BIKAS BANK' BANK_NAME, '977027' BANK_CODE UNION ALL
	SELECT 'Kanchan Development Bank Ltd' BANK_NAME, '977062' BANK_CODE UNION ALL
	SELECT 'Karnali Bikash Bank' BANK_NAME, '977063' BANK_CODE UNION ALL
	SELECT 'KASTHAMANDAP DEVELOPMENT BANK' BANK_NAME, '977021' BANK_CODE UNION ALL
	SELECT 'Kist Bank Ltd.' BANK_NAME, '977064' BANK_CODE UNION ALL
	SELECT 'KUMARI BANK LTD' BANK_NAME, '977024' BANK_CODE UNION ALL
	SELECT 'Laliguraas Development Bank' BANK_NAME, '977065' BANK_CODE UNION ALL
	SELECT 'Laxmi Bank Limited.' BANK_NAME, '977066' BANK_CODE UNION ALL
	SELECT 'Lumbini Bank Limited' BANK_NAME, '977067' BANK_CODE UNION ALL
	SELECT 'Machhapucharre Bank Ltd.' BANK_NAME, '977068' BANK_CODE UNION ALL
	SELECT 'Mahakali Bikas Bank Ltd' BANK_NAME, '977069' BANK_CODE UNION ALL
	SELECT 'Malika Vikas Bank' BANK_NAME, '977070' BANK_CODE UNION ALL
	SELECT 'Manakamana Development Bank' BANK_NAME, '977071' BANK_CODE UNION ALL
	SELECT 'MANASLU BIKAS BANK' BANK_NAME, '977017' BANK_CODE UNION ALL
	SELECT 'MEGA BANK NEPAL LTD.' BANK_NAME, '977003' BANK_CODE UNION ALL
	SELECT 'MISSION DEVELOPMENT BANK.' BANK_NAME, '977105' BANK_CODE UNION ALL
	SELECT 'MUKTINATH BIKAS BANK LTD.' BANK_NAME, '977011' BANK_CODE UNION ALL
	SELECT 'Nabil Bank Limited' BANK_NAME, '977072' BANK_CODE UNION ALL
	SELECT 'NDEP Development Bank Ltd' BANK_NAME, '977073' BANK_CODE UNION ALL
	SELECT 'Nepal Bangladesh Bank Limited' BANK_NAME, '977074' BANK_CODE UNION ALL
	SELECT 'Nepal Bank Limited' BANK_NAME, '977075' BANK_CODE UNION ALL
	SELECT 'Nepal Credit & Commerce Bank Limited' BANK_NAME, '977076' BANK_CODE UNION ALL
	SELECT 'Nepal CSI Development Bank Limited' BANK_NAME, '977077' BANK_CODE UNION ALL
	SELECT 'Nepal Industrial and Commercial Bank Limited.' BANK_NAME, '977078' BANK_CODE UNION ALL
	SELECT 'Nepal Investment Bank Limited *' BANK_NAME, '977079' BANK_CODE UNION ALL
	SELECT 'Nepal SBI Bank Limited. *' BANK_NAME, '977080' BANK_CODE UNION ALL
	SELECT 'NIC ASIA BANK LTD' BANK_NAME, '977106' BANK_CODE UNION ALL
	SELECT 'Nilgiri Bikas Bank Ltd' BANK_NAME, '977081' BANK_CODE UNION ALL
	SELECT 'Nirdhan Uthhan Bank' BANK_NAME, '977082' BANK_CODE UNION ALL
	SELECT 'NMB BANK LIMITED' BANK_NAME, '977026' BANK_CODE UNION ALL
	SELECT 'OM DEVELOPMENT BANK LTD' BANK_NAME, '977107' BANK_CODE UNION ALL
	SELECT 'Paschimanchal Development Bank Ltd' BANK_NAME, '977083' BANK_CODE UNION ALL
	SELECT 'Pathibhara Bikas Bank Limited' BANK_NAME, '977084' BANK_CODE UNION ALL
	SELECT 'PRABHU BANK LTD.' BANK_NAME, '977019' BANK_CODE UNION ALL
	SELECT 'Prime Commercial Bank' BANK_NAME, '977085' BANK_CODE UNION ALL
	SELECT 'Public Development Bank Ltd' BANK_NAME, '977086' BANK_CODE UNION ALL
	SELECT 'PURNIMA BIKASH BANK' BANK_NAME, '977108' BANK_CODE UNION ALL
	SELECT 'Rapti Bheri Development Bank' BANK_NAME, '977087' BANK_CODE UNION ALL
	SELECT 'Rara Bikash Bank' BANK_NAME, '977088' BANK_CODE UNION ALL
	SELECT 'Rastriya Banijya Bank' BANK_NAME, '977089' BANK_CODE UNION ALL
	SELECT 'RELIABLE DEVELOMENT BANK' BANK_NAME, '977016' BANK_CODE UNION ALL
	SELECT 'Resunga Bikas Bank Limited' BANK_NAME, '977090' BANK_CODE UNION ALL
	SELECT 'Rising Development Bank Ltd' BANK_NAME, '977091' BANK_CODE UNION ALL
	SELECT 'Sahayogi Development Bank Limited' BANK_NAME, '977092' BANK_CODE UNION ALL
	SELECT 'SAJHA BIKAS BANK' BANK_NAME, '977109' BANK_CODE UNION ALL
	SELECT 'SANIMA BANK LTD' BANK_NAME, '977025' BANK_CODE UNION ALL
	SELECT 'SAPTAKOSHI DEVELOPMENT BANK LTD' BANK_NAME, '977020' BANK_CODE UNION ALL
	SELECT 'Sewa Bikas Bank Ltd' BANK_NAME, '977093' BANK_CODE UNION ALL
	SELECT 'SHANGRILA BIKAS BANK LIMITED' BANK_NAME, '977110' BANK_CODE UNION ALL
	SELECT 'Shangri-la Development Bank Ltd' BANK_NAME, '977094' BANK_CODE UNION ALL
	SELECT 'SHINE RESUNGA DEVELOPMENT BANK LTD.' BANK_NAME, '977010' BANK_CODE UNION ALL
	SELECT 'Siddharatha Bank Limited *' BANK_NAME, '977095' BANK_CODE UNION ALL
	SELECT 'SIDDHARTHA DEVELOPMENT BANK LTD.' BANK_NAME, '977014' BANK_CODE UNION ALL
	SELECT 'Sindhu Bikas Bank Ltd' BANK_NAME, '977096' BANK_CODE UNION ALL
	SELECT 'Standard Chartered Bank Limited *' BANK_NAME, '977097' BANK_CODE UNION ALL
	SELECT 'Sunrise Bank Limited' BANK_NAME, '977098' BANK_CODE UNION ALL
	SELECT 'Supreme Development Bank' BANK_NAME, '977099' BANK_CODE UNION ALL
	SELECT 'TINAU BIKAS BANK' BANK_NAME, '977111' BANK_CODE UNION ALL
	SELECT 'TINAU DEVLOPMENT BANK LTD.' BANK_NAME, '977005' BANK_CODE UNION ALL
	SELECT 'TOURISM DEVELOPMENT BANK LTD.' BANK_NAME, '977006' BANK_CODE UNION ALL
	SELECT 'TRIVENI BIKAS BANK LTD.' BANK_NAME, '977007' BANK_CODE UNION ALL
	SELECT 'UNITED FINANCE LTD' BANK_NAME, '977112' BANK_CODE UNION ALL
	SELECT 'VIBOR BIKAS BANK' BANK_NAME, '977023' BANK_CODE UNION ALL
	SELECT 'Western Development Bank Limited' BANK_NAME, '977100' BANK_CODE UNION ALL
	SELECT 'YETI DEVELOPMENT BANK LTD.' BANK_NAME, '977009' BANK_CODE
)x

DELETE b 
FROM #TempBankNepal b
INNER JOIN dbo.API_BANK_LIST A ON A.BANK_CODE1=b.BANK_CODE

INSERT INTO API_BANK_LIST(API_PARTNER_ID,BANK_NAME,BANK_CODE1,BANK_STATE,BANK_DISTRICT,BANK_ADDRESS,BANK_PHONE
,BANK_EMAIL,SUPPORT_CURRENCY,BANK_COUNTRY,PAYMENT_TYPE_ID,IS_ACTIVE)
SELECT 394450, BANK_NAME, BANK_CODE, NULL, NULL, NULL, NULL, NULL, NULL, 'NEPAL', 2, 1 FROM #TempBankNepal

------------ cash bank for nepal
IF NOT EXISTS(SELECT 'x' FROM dbo.API_BANK_LIST WHERE BANK_CODE1='CPHM')
BEGIN
    INSERT INTO API_BANK_LIST(API_PARTNER_ID,BANK_NAME,BANK_CODE1,BANK_STATE,BANK_DISTRICT,BANK_ADDRESS,BANK_PHONE
	,BANK_EMAIL,SUPPORT_CURRENCY,BANK_COUNTRY,PAYMENT_TYPE_ID,IS_ACTIVE)
	SELECT 394450, 'Himalayan Bank Ltd', 'CPHM', NULL, NULL, NULL, NULL, NULL, NULL, 'NEPAL', 1, 1
END
IF NOT EXISTS(SELECT 'x' FROM dbo.API_BANK_LIST WHERE BANK_CODE1='CPCE')
BEGIN
    INSERT INTO API_BANK_LIST(API_PARTNER_ID,BANK_NAME,BANK_CODE1,BANK_STATE,BANK_DISTRICT,BANK_ADDRESS,BANK_PHONE
	,BANK_EMAIL,SUPPORT_CURRENCY,BANK_COUNTRY,PAYMENT_TYPE_ID,IS_ACTIVE)
	SELECT 394450, 'Cash Pickup @ City Express', 'CPCE', NULL, NULL, NULL, NULL, NULL, NULL, 'NEPAL', 1, 1
END
IF NOT EXISTS(SELECT 'x' FROM dbo.API_BANK_LIST WHERE BANK_CODE1='CPEBL')
BEGIN
    INSERT INTO API_BANK_LIST(API_PARTNER_ID,BANK_NAME,BANK_CODE1,BANK_STATE,BANK_DISTRICT,BANK_ADDRESS,BANK_PHONE
	,BANK_EMAIL,SUPPORT_CURRENCY,BANK_COUNTRY,PAYMENT_TYPE_ID,IS_ACTIVE)
	SELECT 394450, 'EVEREST BANK LIMITED', 'CPEBL', NULL, NULL, NULL, NULL, NULL, NULL, 'NEPAL', 1, 1
END