------------bank Vietnam
IF OBJECT_ID('tempdb..#TempBankVietnam') IS NOT NULL
			DROP TABLE #TempBankVietnam

SELECT * INTO #TempBankVietnam
FROM
(
	SELECT 'NHTMCP Cong Thuong Vietnam (USD)' BANK_NAME, '840071' BANK_CODE, 'USD' Currency UNION ALL
	SELECT 'NHTMCP Dau Tu va Phat Trien Vietnam (USD)' BANK_NAME, '840072' BANK_CODE, 'USD' Currency UNION ALL
	SELECT 'NHTMCP Ngoai Thuong Vietnam (USD)' BANK_NAME, '840073' BANK_CODE, 'USD' Currency UNION ALL
	SELECT 'NH Nong Nghiep va Phat Trien Nong Thon Vietnam (USD)' BANK_NAME, '840074' BANK_CODE, 'USD' Currency UNION ALL
	SELECT 'Vietnam Maritime Commercial Stock Bank (USD)' BANK_NAME, '840075' BANK_CODE, 'USD' Currency UNION ALL
	SELECT 'NHTMCP Saigon Thuong Tin (USD)' BANK_NAME, '840076' BANK_CODE, 'USD' Currency UNION ALL
	SELECT 'NHTMCP Dong A (USD)' BANK_NAME, '840077' BANK_CODE, 'USD' Currency UNION ALL
	SELECT 'NHTMCP Xuat Nhap Khau Vietnam (USD)' BANK_NAME, '840078' BANK_CODE, 'USD' Currency UNION ALL
	SELECT 'Nam A Commercial Join Stock Bank (USD)' BANK_NAME, '840079' BANK_CODE, 'USD' Currency UNION ALL
	SELECT 'NHTMCP Saigon Cong Thuong (USD)' BANK_NAME, '840080' BANK_CODE, 'USD' Currency UNION ALL
	SELECT 'NHTMCP Vietnam Thinh Vuong (USD)' BANK_NAME, '840081' BANK_CODE, 'USD' Currency UNION ALL
	SELECT 'NHTMCP Ky Thuong Vietnam (USD)' BANK_NAME, '840082' BANK_CODE, 'USD' Currency UNION ALL
	SELECT 'NHTMCP Quoc Te Vietnam (USD)' BANK_NAME, '840083' BANK_CODE, 'USD' Currency UNION ALL
	SELECT 'NHTMCP Dong Nam A (USD)' BANK_NAME, '840084' BANK_CODE, 'USD' Currency UNION ALL
	SELECT 'NHTMCP Dai Duong (USD)' BANK_NAME, '840085' BANK_CODE, 'USD' Currency UNION ALL
	SELECT 'NHTMCP Dau Khi Toan Cau (USD)' BANK_NAME, '840086' BANK_CODE, 'USD' Currency UNION ALL
	SELECT 'NHTMCP Phat Trien Thanh Pho HCM (USD)' BANK_NAME, '840087' BANK_CODE, 'USD' Currency UNION ALL
	SELECT 'NHTMCP An Binh (USD)' BANK_NAME, '840088' BANK_CODE, 'USD' Currency UNION ALL
	SELECT 'NHTMCP Ban Viet (USD)' BANK_NAME, '840089' BANK_CODE, 'USD' Currency UNION ALL
	SELECT 'NHTMCP Phuong Dong (USD)' BANK_NAME, '840090' BANK_CODE, 'USD' Currency UNION ALL
	SELECT 'NHTMCP Saigon (USD)' BANK_NAME, '840091' BANK_CODE, 'USD' Currency UNION ALL
	SELECT 'NHTMCP Xang Dau Petrolimex (USD)' BANK_NAME, '840092' BANK_CODE, 'USD' Currency UNION ALL
	SELECT 'NHTMCP Sai Gon Ha Noi (USD)' BANK_NAME, '840093' BANK_CODE, 'USD' Currency UNION ALL
	SELECT 'NHTMCP Quoc Dan (USD)' BANK_NAME, '840094' BANK_CODE, 'USD' Currency UNION ALL
	SELECT 'NHTMCP Kien Long (USD)' BANK_NAME, '840095' BANK_CODE, 'USD' Currency UNION ALL
	SELECT 'Viet A Bank (USD)' BANK_NAME, '840096' BANK_CODE, 'USD' Currency UNION ALL
	SELECT 'NH Vietnam Thuong Tin (USD)' BANK_NAME, '840097' BANK_CODE, 'USD' Currency UNION ALL
	SELECT 'NHTMCP Buu Dien Lien Viet (USD)' BANK_NAME, '840098' BANK_CODE, 'USD' Currency UNION ALL
	SELECT 'NHTMCP Tien Phong (USD)' BANK_NAME, '840099' BANK_CODE, 'USD' Currency UNION ALL
	SELECT 'NHTMCP Bao Viet (USD)' BANK_NAME, '840100' BANK_CODE, 'USD' Currency UNION ALL
	SELECT 'NHTMCP Dai Chung Vietnam (USD)' BANK_NAME, '840101' BANK_CODE, 'USD' Currency UNION ALL
	SELECT 'NHTNHH MTV Public Vietnam (USD)' BANK_NAME, '840102' BANK_CODE, 'USD' Currency UNION ALL
	SELECT 'Ngân hàng TNHH Indovina (USD)' BANK_NAME, '840103' BANK_CODE, 'USD' Currency UNION ALL
	SELECT 'NH Lien Doanh Viet Nga (USD)' BANK_NAME, '840104' BANK_CODE, 'USD' Currency UNION ALL
	SELECT 'NHTNHH MTV Hongleong Vietnam (USD)' BANK_NAME, '840105' BANK_CODE, 'USD' Currency UNION ALL
	SELECT 'NHTNHH MTV Shinhan Vietnam (USD)' BANK_NAME, '840106' BANK_CODE, 'USD' Currency UNION ALL
	SELECT 'NHTMCP Quan Doi (USD)' BANK_NAME, '840107' BANK_CODE, 'USD' Currency UNION ALL
	SELECT 'NHTMCP A Chau (USD)' BANK_NAME, '840108' BANK_CODE, 'USD' Currency UNION ALL
	SELECT 'NHTMCP Bac A (USD)' BANK_NAME, '840109' BANK_CODE, 'USD' Currency UNION ALL
	SELECT 'Cooperative Bank of Vietnam (USD)' BANK_NAME, '840110' BANK_CODE, 'USD' Currency UNION ALL
	SELECT 'NH Chinh Sach XHVN (USD)' BANK_NAME, '840111' BANK_CODE, 'USD' Currency UNION ALL
	SELECT 'NH Phat Trien VN (USD)' BANK_NAME, '840112' BANK_CODE, 'USD' Currency UNION ALL
	SELECT 'WOORI BANK TP HA NOI (USD)' BANK_NAME, '840113' BANK_CODE, 'USD' Currency UNION ALL
	SELECT 'WOORI BANK TP HO CHI MINH (USD)' BANK_NAME, '840114' BANK_CODE, 'USD' Currency UNION ALL
	SELECT 'NHTMCP Saigon Thuong Tin' BANK_NAME, '840001' BANK_CODE, 'USD' Currency UNION ALL
	SELECT 'Australia and New Zealand Banking Group' BANK_NAME, '840036' BANK_CODE, 'VND' Currency UNION ALL
	SELECT 'HSBC Bank Vietnam' BANK_NAME, '840037' BANK_CODE, 'VND' Currency UNION ALL
	SELECT 'Vietnam Maritime Commercial Stock Bank' BANK_NAME, '840038' BANK_CODE, 'VND' Currency UNION ALL
	SELECT 'Nam A Commercial Join Stock Bank' BANK_NAME, '840040' BANK_CODE, 'VND' Currency UNION ALL
	SELECT 'NH Moneygram' BANK_NAME, '840042' BANK_CODE, 'VND' Currency UNION ALL
	SELECT 'NH Chinh Sach XHVN' BANK_NAME, '840043' BANK_CODE, 'VND' Currency UNION ALL
	SELECT 'NH Phat Trien VN' BANK_NAME, '840044' BANK_CODE, 'VND' Currency UNION ALL
	SELECT 'Cooperative Bank of Vietnam' BANK_NAME, '840045' BANK_CODE, 'VND' Currency UNION ALL
	SELECT 'Viet A Bank' BANK_NAME, '840046' BANK_CODE, 'VND' Currency UNION ALL
	SELECT 'NH Xay Dung VN' BANK_NAME, '840047' BANK_CODE, 'VND' Currency UNION ALL
	SELECT 'Ngn hng TNHH Indovina' BANK_NAME, '840049' BANK_CODE, 'VND' Currency UNION ALL
	SELECT 'Industrial Bank of Korea  Ha Noi branch' BANK_NAME, '840050' BANK_CODE, 'VND' Currency UNION ALL
	SELECT 'Woori Bank Vietnam' BANK_NAME, '840051' BANK_CODE, 'VND' Currency UNION ALL
	SELECT 'Citibank Bank Viet Nam' BANK_NAME, '840063' BANK_CODE, 'VND' Currency UNION ALL
	SELECT 'Standard Chartered Bank Viet Nam Limited' BANK_NAME, '840064' BANK_CODE, 'VND' Currency UNION ALL
	SELECT 'United Overseas Bank Viet Nam' BANK_NAME, '840066' BANK_CODE, 'VND' Currency UNION ALL
	SELECT 'NHTMCP Saigon Thuong Tin' BANK_NAME, '840001' BANK_CODE, 'VND' Currency UNION ALL
	SELECT 'NHTMCP Cong Thuong Vietnam' BANK_NAME, '840002' BANK_CODE, 'VND' Currency UNION ALL
	SELECT 'NHTMCP Saigon Cong Thuong' BANK_NAME, '840003' BANK_CODE, 'VND' Currency UNION ALL
	SELECT 'NHTMCP An Binh' BANK_NAME, '840004' BANK_CODE, 'VND' Currency UNION ALL
	SELECT 'NHTMCP Dai Duong' BANK_NAME, '840005' BANK_CODE, 'VND' Currency UNION ALL
	SELECT 'NHTMCP Dong Nam A' BANK_NAME, '840006' BANK_CODE, 'VND' Currency UNION ALL
	SELECT 'NHTMCP Dai Chung Vietnam' BANK_NAME, '840007' BANK_CODE, 'VND' Currency UNION ALL
	SELECT 'NHTMCP Xang Dau Petrolimex' BANK_NAME, '840008' BANK_CODE, 'VND' Currency UNION ALL
	SELECT 'NHTMCP Dau Khi Toan Cau' BANK_NAME, '840009' BANK_CODE, 'VND' Currency UNION ALL
	SELECT 'NHTMCP Dong A' BANK_NAME, '840010' BANK_CODE, 'VND' Currency UNION ALL
	SELECT 'NHTMCP Dau Tu va Phat Trien Vietnam' BANK_NAME, '840011' BANK_CODE, 'VND' Currency UNION ALL
	SELECT 'NHTMCP Kien Long' BANK_NAME, '840012' BANK_CODE, 'VND' Currency UNION ALL
	SELECT 'NH Nong Nghiep va Phat Trien Nong Thon Vietnam' BANK_NAME, '840013' BANK_CODE, 'VND' Currency UNION ALL
	SELECT 'NHTMCP Ban Viet' BANK_NAME, '840014' BANK_CODE, 'VND' Currency UNION ALL
	SELECT 'NH Vietnam Thuong Tin' BANK_NAME, '840015' BANK_CODE, 'VND' Currency UNION ALL
	SELECT 'NH Lien Doanh Viet Nga' BANK_NAME, '840016' BANK_CODE, 'VND' Currency UNION ALL
	SELECT 'NHTMCP Ngoai Thuong Vietnam' BANK_NAME, '840017' BANK_CODE, 'VND' Currency UNION ALL
	SELECT 'NHTMCP A Chau' BANK_NAME, '840018' BANK_CODE, 'VND' Currency UNION ALL
	SELECT 'NHTMCP Xuat Nhap Khau Vietnam' BANK_NAME, '840019' BANK_CODE, 'VND' Currency UNION ALL
	SELECT 'NHTMCP Tien Phong' BANK_NAME, '840020' BANK_CODE, 'VND' Currency UNION ALL
	SELECT 'NHTMCP Sai Gon Ha Noi' BANK_NAME, '840021' BANK_CODE, 'VND' Currency UNION ALL
	SELECT 'NHTMCP Phat Trien Thanh Pho HCM' BANK_NAME, '840022' BANK_CODE, 'VND' Currency UNION ALL
	SELECT 'NHTMCP Quan Doi' BANK_NAME, '840023' BANK_CODE, 'VND' Currency UNION ALL
	SELECT 'NHTMCP Vietnam Thinh Vuong' BANK_NAME, '840024' BANK_CODE, 'VND' Currency UNION ALL
	SELECT 'NHTMCP Quoc Te Vietnam' BANK_NAME, '840025' BANK_CODE, 'VND' Currency UNION ALL
	SELECT 'NHTMCP Ky Thuong Vietnam' BANK_NAME, '840026' BANK_CODE, 'VND' Currency UNION ALL
	SELECT 'NHTMCP Phuong Dong' BANK_NAME, '840027' BANK_CODE, 'VND' Currency UNION ALL
	SELECT 'NHTMCP Quoc Dan' BANK_NAME, '840028' BANK_CODE, 'VND' Currency UNION ALL
	SELECT 'NHTNHH MTV Hongleong Vietnam' BANK_NAME, '840029' BANK_CODE, 'VND' Currency UNION ALL
	SELECT 'NHTMCP Buu Dien Lien Viet' BANK_NAME, '840030' BANK_CODE, 'VND' Currency UNION ALL
	SELECT 'NHTMCP Bac A' BANK_NAME, '840031' BANK_CODE, 'VND' Currency UNION ALL
	SELECT 'NHTMCP Bao Viet' BANK_NAME, '840032' BANK_CODE, 'VND' Currency UNION ALL
	SELECT 'NHTNHH MTV Shinhan Vietnam' BANK_NAME, '840033' BANK_CODE, 'VND' Currency UNION ALL
	SELECT 'NHTNHH MTV Public Vietnam' BANK_NAME, '840034' BANK_CODE, 'VND' Currency UNION ALL
	SELECT 'NHTMCP Saigon' BANK_NAME, '840035' BANK_CODE, 'VND' Currency
)x
DELETE b 
FROM #TempBankVietnam b
INNER JOIN dbo.API_BANK_LIST A ON A.BANK_CODE1=b.BANK_CODE

INSERT INTO API_BANK_LIST(API_PARTNER_ID,BANK_NAME,BANK_CODE1,BANK_STATE,BANK_DISTRICT,BANK_ADDRESS,BANK_PHONE
,BANK_EMAIL,SUPPORT_CURRENCY,BANK_COUNTRY,PAYMENT_TYPE_ID,IS_ACTIVE)
SELECT 394450, BANK_NAME, BANK_CODE, NULL, NULL, NULL, NULL, NULL, Currency, 'VIETNAM', 2, 1 FROM #TempBankVietnam

---------- cash
IF OBJECT_ID('tempdb..#TempCashVietnam') IS NOT NULL
			DROP TABLE #TempCashVietnam

SELECT * INTO #TempCashVietnam
FROM
(
	SELECT 'Cash Pickup @ Sacombank' BANK_NAME, 'CPSACO' BANK_CODE, 'VND' Currency UNION ALL
	SELECT 'Cash Pickup @Sacombank USD' BANK_NAME, 'CPSACOUSD' BANK_CODE, 'USD' Currency UNION ALL
	SELECT 'Cash Pickup @ DongA' BANK_NAME, 'CPDONA' BANK_CODE, 'VND' Currency UNION ALL
	SELECT 'Cash Pickup @ DongA' BANK_NAME, 'CPDONAUSD' BANK_CODE, 'USD' Currency UNION ALL
	SELECT 'Cash Pickup @ MB Bank' BANK_NAME, 'CPMBVND' BANK_CODE, 'VND' Currency UNION ALL
	SELECT 'Cash Pickup @ MB Bank USD' BANK_NAME, 'CPMBUSD' BANK_CODE, 'USD' Currency
)x
DELETE b 
FROM #TempCashVietnam b
INNER JOIN dbo.API_BANK_LIST A ON A.BANK_CODE1=b.BANK_CODE

INSERT INTO API_BANK_LIST(API_PARTNER_ID,BANK_NAME,BANK_CODE1,BANK_STATE,BANK_DISTRICT,BANK_ADDRESS,BANK_PHONE
,BANK_EMAIL,SUPPORT_CURRENCY,BANK_COUNTRY,PAYMENT_TYPE_ID,IS_ACTIVE)
SELECT 394450, BANK_NAME, BANK_CODE, NULL, NULL, NULL, NULL, NULL, Currency, 'VIETNAM', 1, 1 FROM #TempCashVietnam
