------------bank Singapore
IF OBJECT_ID('tempdb..#TempBankBrazil') IS NOT NULL
			DROP TABLE #TempBankBrazil

SELECT * INTO #TempBankBrazil
FROM
(
	SELECT '550001' BANK_CODE ,'BANCO DO BRASIL S.A. - BB' BANK_NAME
)x
DELETE b 
FROM #TempBankBrazil b
INNER JOIN dbo.API_BANK_LIST A ON A.BANK_CODE1=b.BANK_CODE

INSERT INTO API_BANK_LIST(API_PARTNER_ID,BANK_NAME,BANK_CODE1,BANK_STATE,BANK_DISTRICT,BANK_ADDRESS,BANK_PHONE
,BANK_EMAIL,SUPPORT_CURRENCY,BANK_COUNTRY,PAYMENT_TYPE_ID,IS_ACTIVE)
SELECT 394450, BANK_NAME, BANK_CODE, NULL, NULL, NULL, NULL, NULL, NULL, 'Brazil', 2, 1 FROM #TempBankBrazil



---------------- cash 
IF OBJECT_ID('tempdb..#TempCashBrazil') IS NOT NULL
			DROP TABLE #TempCashBrazil

SELECT * INTO #TempCashBrazil
FROM
(
	SELECT 'Brazil Sicoob' BANK_NAME, 'CPSIC' BANK_CODE
)x

DELETE b 
FROM #TempCashBrazil b
INNER JOIN dbo.API_BANK_LIST A ON A.BANK_CODE1=b.BANK_CODE AND A.PAYMENT_TYPE_ID=1

INSERT INTO API_BANK_LIST(API_PARTNER_ID,BANK_NAME,BANK_CODE1,BANK_STATE,BANK_DISTRICT,BANK_ADDRESS,BANK_PHONE
,BANK_EMAIL,SUPPORT_CURRENCY,BANK_COUNTRY,PAYMENT_TYPE_ID,IS_ACTIVE)
SELECT 394450, BANK_NAME, BANK_CODE, NULL, NULL, NULL, NULL, NULL, NULL, 'Brazil', 1, 1 FROM #TempCashBrazil
