------------bank Philippines
IF OBJECT_ID('tempdb..#TempBankPhilippines') IS NOT NULL
			DROP TABLE #TempBankPhilippines

SELECT * INTO #TempBankPhilippines
FROM
(
	SELECT 'BDO UNIBANK' BANK_NAME, '63053' BANK_CODE UNION ALL
	SELECT 'Pacific Ace Savings Bank' BANK_NAME, '63067' BANK_CODE UNION ALL
	SELECT 'Queen City Dev Bank' BANK_NAME, '63023' BANK_CODE UNION ALL
	SELECT 'UNION BANK OF THE PHILIPPINES' BANK_NAME, '63041' BANK_CODE UNION ALL
	SELECT 'UCPB - UNITED COCONUT PLANTERS BANK' BANK_NAME, '63029' BANK_CODE UNION ALL
	SELECT 'Allied Savings Bank' BANK_NAME, '63101' BANK_CODE UNION ALL
	SELECT 'ASIA UNITED BANK' BANK_NAME, '63102' BANK_CODE UNION ALL
	SELECT 'Banco Filipino' BANK_NAME, '63103' BANK_CODE UNION ALL
	SELECT 'CHINA BANK' BANK_NAME, '63106' BANK_CODE UNION ALL
	SELECT 'CHINA BANK SAVINGS' BANK_NAME, '63107' BANK_CODE UNION ALL
	SELECT 'CHINA TRUST (CTBC)' BANK_NAME, '63108' BANK_CODE UNION ALL
	SELECT 'CITIBANK' BANK_NAME, '63109' BANK_CODE UNION ALL
	SELECT 'CITY STATE SAVINGS BANK' BANK_NAME, '63111' BANK_CODE UNION ALL
	SELECT 'EAST WEST BANK' BANK_NAME, '63112' BANK_CODE UNION ALL
	SELECT 'Export and Industry Bank' BANK_NAME, '63113' BANK_CODE UNION ALL
	SELECT 'Malayan Bank' BANK_NAME, '63114' BANK_CODE UNION ALL
	SELECT 'METROBANK' BANK_NAME, '63116' BANK_CODE UNION ALL
	SELECT 'PHILTRUST CO' BANK_NAME, '63117' BANK_CODE UNION ALL
	SELECT 'PBCOM - PHILIPPINE BANK OF COMMUNICATIONS' BANK_NAME, '63118' BANK_CODE UNION ALL
	SELECT 'PHIL BUSINESS BANK' BANK_NAME, '63119' BANK_CODE UNION ALL
	SELECT 'OVERSEAS FILIPINO BANK' BANK_NAME, '63120' BANK_CODE UNION ALL
	SELECT 'PSBANK - PHILIPPINE SAVINGS BANK' BANK_NAME, '63121' BANK_CODE UNION ALL
	SELECT 'QCRB' BANK_NAME, '63122' BANK_CODE UNION ALL
	SELECT 'RCBC' BANK_NAME, '63124' BANK_CODE UNION ALL
	SELECT 'RCBC SAVINGS BANK' BANK_NAME, '63125' BANK_CODE UNION ALL
	SELECT 'ROBINSONS BANK CORPORATION' BANK_NAME, '63126' BANK_CODE UNION ALL
	SELECT 'SECURITY BANK CORPORATION' BANK_NAME, '63127' BANK_CODE UNION ALL
	SELECT 'Standard Chartered Bank' BANK_NAME, '63128' BANK_CODE UNION ALL
	SELECT 'Sterling Bank' BANK_NAME, '63129' BANK_CODE UNION ALL
	SELECT 'TongYang Bank' BANK_NAME, '63130' BANK_CODE UNION ALL
	SELECT 'World Partners Bank' BANK_NAME, '63131' BANK_CODE UNION ALL
	SELECT 'PHILIPPINE NATIONAL BANK' BANK_NAME, '63132' BANK_CODE UNION ALL
	SELECT 'MayBank' BANK_NAME, '63133' BANK_CODE UNION ALL
	SELECT 'HSBC - HONGKONG AND SHANGHAI BANKING CORPORATION' BANK_NAME, '63134' BANK_CODE UNION ALL
	SELECT 'HSBC SAVINGS BANK' BANK_NAME, '63135' BANK_CODE UNION ALL
	SELECT 'Wealth Bank' BANK_NAME, '63137' BANK_CODE UNION ALL
	SELECT 'CARD Bank' BANK_NAME, '63138' BANK_CODE UNION ALL
	SELECT 'EQUICOM SAVINGS BANK INC' BANK_NAME, '63140' BANK_CODE UNION ALL
	SELECT 'Enterprise Bank' BANK_NAME, '63141' BANK_CODE UNION ALL
	SELECT 'Green Bank' BANK_NAME, '63142' BANK_CODE UNION ALL
	SELECT 'ISLA Bank' BANK_NAME, '63143' BANK_CODE UNION ALL
	SELECT 'LAND BANK' BANK_NAME, '63144' BANK_CODE UNION ALL
	SELECT 'PHILIPPINE VETERANS BANK' BANK_NAME, '63145' BANK_CODE UNION ALL
	SELECT 'Plan Bank' BANK_NAME, '63146' BANK_CODE UNION ALL
	SELECT 'PVBCC' BANK_NAME, '63147' BANK_CODE UNION ALL
	SELECT 'Producers Bank' BANK_NAME, '63148' BANK_CODE UNION ALL
	SELECT 'Security Bank Savings' BANK_NAME, '63149' BANK_CODE UNION ALL
	SELECT 'UCPB Savings Bank' BANK_NAME, '63150' BANK_CODE UNION ALL
	SELECT 'BOC - BANK OF COMMERCE' BANK_NAME, '63152' BANK_CODE UNION ALL
	SELECT 'BPI' BANK_NAME, '63153' BANK_CODE UNION ALL
	SELECT 'BPI FAMILY' BANK_NAME, '63154' BANK_CODE UNION ALL
	SELECT 'City Savings Bank' BANK_NAME, '63155' BANK_CODE UNION ALL
	SELECT 'Malayan Savings Bank' BANK_NAME, '63156' BANK_CODE UNION ALL
	SELECT 'MAYBANK PHILIPPINES INC (PNB Republic)' BANK_NAME, '63157' BANK_CODE UNION ALL
	SELECT 'Nationlink' BANK_NAME, '63158' BANK_CODE UNION ALL
	SELECT 'BDO NETWORK BANK' BANK_NAME, '63159' BANK_CODE UNION ALL
	SELECT 'STERLING BANK OF ASIA' BANK_NAME, '63161' BANK_CODE UNION ALL
	SELECT 'Sugbuanon Bank' BANK_NAME, '63162' BANK_CODE UNION ALL
	SELECT 'Tong Yang Savings Bank' BANK_NAME, '63163' BANK_CODE UNION ALL
	SELECT 'EQUITABLE SAVINGS BANK' BANK_NAME, '63164' BANK_CODE UNION ALL
	SELECT 'INTERNATIONAL EXCHANGE BANK' BANK_NAME, '63166' BANK_CODE UNION ALL
	SELECT 'EQUITABLE PCI BANK' BANK_NAME, '63172' BANK_CODE UNION ALL
	SELECT 'IBANK-UNIONBANK' BANK_NAME, '63174' BANK_CODE UNION ALL
	SELECT 'AMA Bank' BANK_NAME, '63173' BANK_CODE UNION ALL
	SELECT 'AL AMANAH ISLAMIC INVESTMENT BANK' BANK_NAME, '63175' BANK_CODE UNION ALL
	SELECT 'PRODUCERS SAVINGS BANK CORP' BANK_NAME, '63178' BANK_CODE UNION ALL
	SELECT 'PSBANK (USD)' BANK_NAME, '63181' BANK_CODE UNION ALL
	SELECT 'METROBANK (USD)' BANK_NAME, '63182' BANK_CODE UNION ALL
	SELECT 'Philippine National Saving Bank' BANK_NAME, '63183' BANK_CODE UNION ALL
	SELECT 'ANZ BANK' BANK_NAME, '63184' BANK_CODE UNION ALL
	SELECT 'BANK OF AMERICA' BANK_NAME, '63185' BANK_CODE UNION ALL
	SELECT 'BANK OF CHINA' BANK_NAME, '63186' BANK_CODE UNION ALL
	SELECT 'BANGKOK BANK PUBLIC CO LTD' BANK_NAME, '63187' BANK_CODE UNION ALL
	SELECT 'BDO PRIVATE BANK' BANK_NAME, '63188' BANK_CODE UNION ALL
	SELECT 'DBP - DEVELOPMENT BANK OF THE PHILIPPINES' BANK_NAME, '63189' BANK_CODE UNION ALL
	SELECT 'DEUTSCHE BANK' BANK_NAME, '63190' BANK_CODE UNION ALL
	SELECT 'FIRST CONSOLIDATED BANK' BANK_NAME, '63191' BANK_CODE UNION ALL
	SELECT 'G-XHANGE INC' BANK_NAME, '63192' BANK_CODE UNION ALL
	SELECT 'INDUSTRIAL BANK OF KOREA' BANK_NAME, '63193' BANK_CODE UNION ALL
	SELECT 'ISLA BANK INC.' BANK_NAME, '63194' BANK_CODE UNION ALL
	SELECT 'KEB HANA' BANK_NAME, '63195' BANK_CODE UNION ALL
	SELECT 'JP MORGAN CHASE BANK' BANK_NAME, '63196' BANK_CODE UNION ALL
	SELECT 'MALAYAN BANK SAVINGS AND MORTGAGE BANK INC (MALAYAN SVGS)' BANK_NAME, '63197' BANK_CODE UNION ALL
	SELECT 'MEGA INTL COMML BANK CO LTD (ICBC)' BANK_NAME, '63198' BANK_CODE UNION ALL
	SELECT 'MIZUHO BANK LTD  (FUJI BANK)' BANK_NAME, '63199' BANK_CODE UNION ALL
	SELECT 'OMNIPAY INC' BANK_NAME, '63200' BANK_CODE UNION ALL
	SELECT 'PAYMAYA PHILS INC' BANK_NAME, '63201' BANK_CODE UNION ALL
	SELECT 'PARTNER RURAL BANK (COTABATO) INC' BANK_NAME, '63202' BANK_CODE UNION ALL
	SELECT 'SHINHAN BANK' BANK_NAME, '63203' BANK_CODE UNION ALL
	SELECT 'SUN SAVINGS BANK INC' BANK_NAME, '63204' BANK_CODE UNION ALL
	SELECT 'THE STANDARD CHARTERED BANK' BANK_NAME, '63205' BANK_CODE UNION ALL
	SELECT 'UNITED OVERSEAS BANK PHILIPPINES' BANK_NAME, '63207' BANK_CODE UNION ALL
	SELECT 'WEALTH DEVELOPMENT BANK' BANK_NAME, '63208' BANK_CODE UNION ALL
	SELECT 'YUANTA SAVINGS BANK PHILS INC (Tongyang)' BANK_NAME, '63209' BANK_CODE UNION ALL
	SELECT 'BDO UNIBANK (USD)' BANK_NAME, '63210' BANK_CODE UNION ALL
	SELECT 'ASIA UNITED BANK (USD)' BANK_NAME, '63211' BANK_CODE UNION ALL
	SELECT 'ANZ BANK (USD)' BANK_NAME, '63212' BANK_CODE UNION ALL
	SELECT 'BANGKOK BANK PUBLIC CO LTD (USD)' BANK_NAME, '63213' BANK_CODE UNION ALL
	SELECT 'BANK OF CHINA (USD)' BANK_NAME, '63214' BANK_CODE UNION ALL
	SELECT 'BANK OF COMMERCE (USD)' BANK_NAME, '63215' BANK_CODE UNION ALL
	SELECT 'CITIBANK (PHILIPPINES) (USD)' BANK_NAME, '63216' BANK_CODE UNION ALL
	SELECT 'CHINATRUST BANK (USD)' BANK_NAME, '63217' BANK_CODE UNION ALL
	SELECT 'DEVELOPMENT BANK OF PHILIPPINES (USD)' BANK_NAME, '63218' BANK_CODE UNION ALL
	SELECT 'EAST WEST BANK (USD)' BANK_NAME, '63219' BANK_CODE UNION ALL
	SELECT 'HSBC (USD)' BANK_NAME, '63220' BANK_CODE UNION ALL
	SELECT 'INDUSTRIAL BANK OF KOREA (USD)' BANK_NAME, '63221' BANK_CODE UNION ALL
	SELECT 'KEB HANA (USD)' BANK_NAME, '63222' BANK_CODE UNION ALL
	SELECT 'LAND BANK (USD)' BANK_NAME, '63223' BANK_CODE UNION ALL
	SELECT 'MALAYAN SAVINGS BANK (USD)' BANK_NAME, '63224' BANK_CODE UNION ALL
	SELECT 'MAYBANK PHILIPPINES (USD)' BANK_NAME, '63225' BANK_CODE UNION ALL
	SELECT 'MEGA INTL COMML BANK CO LTD (USD)' BANK_NAME, '63226' BANK_CODE UNION ALL
	SELECT 'MIZUHO BANK LTD (USD)' BANK_NAME, '63227' BANK_CODE UNION ALL
	SELECT 'PHILIPPINE BANK OF COMMUNICATIONS (USD)' BANK_NAME, '63228' BANK_CODE UNION ALL
	SELECT 'PHILIPPINE VETERANS BANK (USD)' BANK_NAME, '63229' BANK_CODE UNION ALL
	SELECT 'RIZAL COMMERCIAL BANKING CORPORATION (USD)' BANK_NAME, '63230' BANK_CODE UNION ALL
	SELECT 'RIZAL COMMERCIAL BANKING CORPORATION SAVINGS BANK (USD)' BANK_NAME, '63231' BANK_CODE UNION ALL
	SELECT 'SECURITY BANK (USD)' BANK_NAME, '63232' BANK_CODE UNION ALL
	SELECT 'SHINHAN BANK (USD)' BANK_NAME, '63233' BANK_CODE UNION ALL
	SELECT 'STANDARD CHARTERED BANK (USD)' BANK_NAME, '63234' BANK_CODE UNION ALL
	SELECT 'UNION BANK OF THE PHILIPPINES (USD)' BANK_NAME, '63235' BANK_CODE UNION ALL
	SELECT 'UNITED COCONUT PLANTERS BANK (USD)' BANK_NAME, '63236' BANK_CODE UNION ALL
	SELECT 'UNITED OVERSEAS BANK PHILIPPINES (USD)' BANK_NAME, '63237' BANK_CODE UNION ALL
	SELECT 'BANK OF PHILIPPINE ISLAND (USD)' BANK_NAME, '63238' BANK_CODE
)x

DELETE b 
FROM #TempBankPhilippines b
INNER JOIN dbo.API_BANK_LIST A ON A.BANK_CODE1=b.BANK_CODE

INSERT INTO API_BANK_LIST(API_PARTNER_ID,BANK_NAME,BANK_CODE1,BANK_STATE,BANK_DISTRICT,BANK_ADDRESS,BANK_PHONE
,BANK_EMAIL,SUPPORT_CURRENCY,BANK_COUNTRY,PAYMENT_TYPE_ID,IS_ACTIVE)
SELECT 394450, BANK_NAME, BANK_CODE, NULL, NULL, NULL, NULL, NULL, NULL, 'PHILIPPINES', 2, 1 FROM #TempBankPhilippines

---------------- cash 
IF OBJECT_ID('tempdb..#TempCashPhilippines') IS NOT NULL
			DROP TABLE #TempCashPhilippines

SELECT * INTO #TempCashPhilippines
FROM
(
	SELECT 'BDO' BANK_NAME, 'CPAW' BANK_CODE,'PHP' Currency UNION ALL
	SELECT 'M Lhuillier' BANK_NAME, 'CPMLKP' BANK_CODE,'PHP' Currency UNION ALL
	SELECT 'Cebuana Lhuillier' BANK_NAME, 'CPCL' BANK_CODE,'PHP' Currency UNION ALL
	SELECT 'LBC Express' BANK_NAME, 'CPLBC' BANK_CODE,'PHP' Currency UNION ALL
	SELECT 'SM Counters' BANK_NAME, 'CPSFC' BANK_CODE,'PHP' Currency UNION ALL
	SELECT 'Palawan Pawnshop' BANK_NAME, 'CPPPS' BANK_CODE,'PHP' Currency UNION ALL
	SELECT 'Pickup Anywhere' BANK_NAME, 'CPALL' BANK_CODE,'PHP' Currency UNION ALL
	SELECT 'Metrobank' BANK_NAME, 'CPMTPHP' BANK_CODE,'PHP' Currency UNION ALL
	SELECT 'Metrobank USD' BANK_NAME, 'CPMTUSD' BANK_CODE,'USD' Currency UNION ALL
	SELECT 'BPI' BANK_NAME, 'CPBPI' BANK_CODE,'PHP' Currency UNION ALL
	SELECT 'Cebuana Lhuillier USD' BANK_NAME, 'CPCLUSD' BANK_CODE,'USD' Currency UNION ALL
	SELECT 'BDO USD' BANK_NAME, 'CPBDOUSD' BANK_CODE,'USD' Currency
)x

DELETE b 
FROM #TempCashPhilippines b
INNER JOIN dbo.API_BANK_LIST A ON A.BANK_CODE1=b.BANK_CODE AND A.PAYMENT_TYPE_ID=1

INSERT INTO API_BANK_LIST(API_PARTNER_ID,BANK_NAME,BANK_CODE1,BANK_STATE,BANK_DISTRICT,BANK_ADDRESS,BANK_PHONE
,BANK_EMAIL,SUPPORT_CURRENCY,BANK_COUNTRY,PAYMENT_TYPE_ID,IS_ACTIVE)
SELECT 394450, BANK_NAME, BANK_CODE, NULL, NULL, NULL, NULL, NULL, NULL, 'PHILIPPINES', 1, 1 FROM #TempCashPhilippines


RETURN
-------- wallet

IF NOT EXISTS(SELECT 'x' FROM dbo.API_BANK_LIST WHERE BANK_CODE1='EWGCH')
BEGIN
    INSERT INTO API_BANK_LIST(API_PARTNER_ID,BANK_NAME,BANK_CODE1,BANK_STATE,BANK_DISTRICT,BANK_ADDRESS,BANK_PHONE
	,BANK_EMAIL,SUPPORT_CURRENCY,BANK_COUNTRY,PAYMENT_TYPE_ID,IS_ACTIVE)
	SELECT 394450, 'G-XHANGE INC / GCash', 'EWGCH', NULL, NULL, NULL, NULL, NULL, NULL, 'PHILIPPINES', 1, 1
END

IF NOT EXISTS(SELECT 'x' FROM dbo.API_BANK_LIST WHERE BANK_CODE1='EWPMY')
BEGIN
    INSERT INTO API_BANK_LIST(API_PARTNER_ID,BANK_NAME,BANK_CODE1,BANK_STATE,BANK_DISTRICT,BANK_ADDRESS,BANK_PHONE
	,BANK_EMAIL,SUPPORT_CURRENCY,BANK_COUNTRY,PAYMENT_TYPE_ID,IS_ACTIVE)
	SELECT 394450, 'PAYMAYA PHILS INC', NULL, NULL, NULL, NULL, NULL, NULL, 'PHILIPPINES', 1, 1
END