------------bank Thailand
IF OBJECT_ID('tempdb..#TempBankThailand') IS NOT NULL
			DROP TABLE #TempBankThailand

SELECT * INTO #TempBankThailand
FROM
(
	SELECT '6600001' BANK_CODE , 'AGRICULTURE & AGRICULTL COOP' BANK_NAME UNION ALL
	SELECT '6600002' BANK_CODE , 'BANGKOK BANK' BANK_NAME UNION ALL
	SELECT '6600003' BANK_CODE , 'BANK OF AYUDHYA' BANK_NAME UNION ALL
	SELECT '6600004' BANK_CODE , 'CIMB Thai Bank Public Company Ltd' BANK_NAME UNION ALL
	SELECT '6600005' BANK_CODE , 'GOVERNMENT HOUSING BANK' BANK_NAME UNION ALL
	SELECT '6600006' BANK_CODE , 'GOVERNMENT SAVING BANK' BANK_NAME UNION ALL
	SELECT '6600007' BANK_CODE , 'KASIKORN BANK' BANK_NAME UNION ALL
	SELECT '6600008' BANK_CODE , 'KRUNG THAI BANK' BANK_NAME UNION ALL
	SELECT '6600009' BANK_CODE , 'SIAM COMMERCIAL BANK' BANK_NAME UNION ALL
	SELECT '6600010' BANK_CODE , 'Thai Military Bank' BANK_NAME UNION ALL
	SELECT '6600011' BANK_CODE , 'THANACHART BANK' BANK_NAME UNION ALL
	SELECT '6600012' BANK_CODE , 'UNITED OVERSEA BANK (Thai) LTD' BANK_NAME UNION ALL
	SELECT '6600016' BANK_CODE , 'CITIBANK' BANK_NAME UNION ALL
	SELECT '6600017' BANK_CODE , 'SUMITOMO MITSUI BANKING CORPORATION' BANK_NAME UNION ALL
	SELECT '6600018' BANK_CODE , 'STANDARD CHARTERED BANK (THAI)' BANK_NAME UNION ALL
	SELECT '6600019' BANK_CODE , 'MEGA INTERNATIONAL COMMERCIAL BANK PCL' BANK_NAME UNION ALL
	SELECT '6600020' BANK_CODE , 'BANK OF AMERICA NATIONAL ASSOCIATION' BANK_NAME UNION ALL
	SELECT '6600022' BANK_CODE , 'HONG KONG & SHANGHAI CORPORATION LIMITED' BANK_NAME UNION ALL
	SELECT '6600023' BANK_CODE , 'DEUTSCHE BANK' BANK_NAME UNION ALL
	SELECT '6600024' BANK_CODE , 'MIZUHO CORPORATE BANK LIMITED' BANK_NAME UNION ALL
	SELECT '6600025' BANK_CODE , 'ISLAMIC BANK OF THAILAND' BANK_NAME UNION ALL
	SELECT '6600026' BANK_CODE , 'TISCO BANK PUBLIC COMPANY LIMITED' BANK_NAME UNION ALL
	SELECT '6600028' BANK_CODE , 'KIATNAKIN BANK PUBLIC COMPANY LIMITED' BANK_NAME UNION ALL
	SELECT '6600030' BANK_CODE , 'THE THAI CREDIT RETAIL BANK PUBLIC COMPANY LIMITED' BANK_NAME UNION ALL
	SELECT '6600031' BANK_CODE , 'LAND AND HOUSES BANK PUBLIC COMPANY LIMITED' BANK_NAME UNION ALL
	SELECT '6600032' BANK_CODE , 'Industrial and Commercial Bank of China (THAI) Public Company Limited (ICBC THAI)' BANK_NAME 
)x
DELETE b 
FROM #TempBankThailand b
INNER JOIN dbo.API_BANK_LIST A ON A.BANK_CODE1=b.BANK_CODE

INSERT INTO API_BANK_LIST(API_PARTNER_ID,BANK_NAME,BANK_CODE1,BANK_STATE,BANK_DISTRICT,BANK_ADDRESS,BANK_PHONE
,BANK_EMAIL,SUPPORT_CURRENCY,BANK_COUNTRY,PAYMENT_TYPE_ID,IS_ACTIVE)
SELECT 394450, BANK_NAME, BANK_CODE, NULL, NULL, NULL, NULL, NULL, NULL, 'THAILAND', 2, 1 FROM #TempBankThailand