--------- china e-wallet

IF NOT EXISTS(SELECT 'x' FROM dbo.API_BANK_LIST WHERE BANK_CODE1='EWALIPAY')
BEGIN
    INSERT INTO dbo.API_BANK_LIST
				( API_PARTNER_ID ,BANK_NAME ,BANK_CODE1 ,BANK_COUNTRY ,PAYMENT_TYPE_ID ,IS_ACTIVE)
		SELECT 394450,'Alipay','EWALIPAY','CHINA',13,1
END

----- Bank Of CHINA bAccType=1
IF OBJECT_ID('tempdb..#TempBankChina') IS NOT NULL
			DROP TABLE #TempBankChina


SELECT * INTO #TempBankChina
FROM(
	SELECT '8600001' BANK_CODE ,'Bank of Nanjing (南京银行)' BANK_NAME UNION ALL
	SELECT '8600002' BANK_CODE ,'Baoshang Bank (包商银行)' BANK_NAME UNION ALL
	SELECT '8600003' BANK_CODE ,'Agricultural Bank of China (中国农业银行)' BANK_NAME UNION ALL
	SELECT '8600004' BANK_CODE ,'China Construction Bank (中国建设银行)' BANK_NAME UNION ALL
	SELECT '8600005' BANK_CODE ,'China Everbright Bank (光大银行)' BANK_NAME UNION ALL
	SELECT '8600006' BANK_CODE ,'China Minsheng Bank (中国民生银行)' BANK_NAME UNION ALL
	SELECT '8600007' BANK_CODE ,'Industrial Bank Co., Ltd. (兴业银行)' BANK_NAME UNION ALL
	SELECT '8600009' BANK_CODE ,'Hana Bank (China) (韩亚银行（中国）)' BANK_NAME UNION ALL
	SELECT '8600010' BANK_CODE ,'China Bohai Bank (渤海银行)' BANK_NAME UNION ALL
	SELECT '8600011' BANK_CODE ,'Tianjin Bank (天津银行)' BANK_NAME UNION ALL
	SELECT '8600012' BANK_CODE ,'Tianjin Rural Cooperative Bank (Tianjin Rural Credit Union, Tianjin Rural Commercial Bank) (天津农村合作银行（天津农村信用联社、天津农村商业银行）)' BANK_NAME UNION ALL
	SELECT '8600014' BANK_CODE ,'Shenzhen Rural Commercial Bank (深圳农村商业银行)' BANK_NAME UNION ALL
	SELECT '8600015' BANK_CODE ,'Ping An Bank (平安银行)' BANK_NAME UNION ALL
	SELECT '8600016' BANK_CODE ,'Dongguan Rural Commercial Bank (东莞农村商业银行)' BANK_NAME UNION ALL
	SELECT '8600017' BANK_CODE ,'Bank of Guangzhou (广州银行)' BANK_NAME UNION ALL
	SELECT '8600018' BANK_CODE ,'Guangzhou Rural Commercial Bank (广州农村商业银行)' BANK_NAME UNION ALL
	SELECT '8600019' BANK_CODE ,'Industrial and Commercial Bank of China (中国工商银行)' BANK_NAME UNION ALL
	SELECT '8600020' BANK_CODE ,'Bank of Communications (交通银行)' BANK_NAME UNION ALL
	SELECT '8600021' BANK_CODE ,'China Citic Bank (中信银行)' BANK_NAME UNION ALL
	SELECT '8600024' BANK_CODE ,'Guangdong Development Bank (广发银行)' BANK_NAME UNION ALL
	SELECT '8600025' BANK_CODE ,'Postal Savings Bank of China (中国邮政储蓄银行)' BANK_NAME UNION ALL
	SELECT '8600028' BANK_CODE ,'Bank of Dongguan (Dongguan Commercial Bank) (东莞银行（东莞市商业银行）)' BANK_NAME UNION ALL
	SELECT '8600030' BANK_CODE ,'Shanghai Pudong Development Bank (上海浦东发展银行)' BANK_NAME UNION ALL
	SELECT '8600031' BANK_CODE ,'Anhui Province Rural Credit Union (安徽省农村信用联社)' BANK_NAME UNION ALL
	SELECT '8600032' BANK_CODE ,'Xiamen Bank (厦门银行)' BANK_NAME UNION ALL
	SELECT '8600033' BANK_CODE ,'Guangxi Beibu Gulf Bank (广西北部湾银行)' BANK_NAME UNION ALL
	SELECT '8600034' BANK_CODE ,'Bank of Changsha (长沙银行)' BANK_NAME UNION ALL
	SELECT '8600036' BANK_CODE ,'Suzhou Bank (苏州银行)' BANK_NAME UNION ALL
	SELECT '8600037' BANK_CODE ,'Rural Commercial Bank of Zhangjiagang (张家港农村商业银行)' BANK_NAME UNION ALL
	SELECT '8600038' BANK_CODE ,'Nanchang Bank (南昌银行)' BANK_NAME UNION ALL
	SELECT '8600039' BANK_CODE ,'Bank of Shangrao (上饶银行)' BANK_NAME UNION ALL
	SELECT '8600040' BANK_CODE ,'Dongying City Commercial Bank (东营市商业银行)' BANK_NAME UNION ALL
	SELECT '8600041' BANK_CODE ,'Bank of Jining (济宁银行)' BANK_NAME UNION ALL
	SELECT '8600042' BANK_CODE ,'Laishang Bank (莱商银行)' BANK_NAME UNION ALL
	SELECT '8600043' BANK_CODE ,'Linshang Bank (临商银行)' BANK_NAME UNION ALL
	SELECT '8600044' BANK_CODE ,'Qishang Bank (齐商银行)' BANK_NAME UNION ALL
	SELECT '8600045' BANK_CODE ,'Bank of Qingdao (青岛银行)' BANK_NAME UNION ALL
	SELECT '8600046' BANK_CODE ,'Bank of Rizhao (日照银行)' BANK_NAME UNION ALL
	SELECT '8600047' BANK_CODE ,'Taian City Commercial Bank (泰安市商业银行)' BANK_NAME UNION ALL
	SELECT '8600048' BANK_CODE ,'Weihai City Commercial Bank (威海市商业银行)' BANK_NAME UNION ALL
	SELECT '8600049' BANK_CODE ,'Yantai Bank (烟台银行)' BANK_NAME UNION ALL
	SELECT '8600050' BANK_CODE ,'Bank of Dalian (大连银行)' BANK_NAME UNION ALL
	SELECT '8600051' BANK_CODE ,'Bank of Jinzhou (锦州银行)' BANK_NAME UNION ALL
	SELECT '8600052' BANK_CODE ,'Anshan City Commercial Bank (鞍山市商业银行)' BANK_NAME UNION ALL
	SELECT '8600053' BANK_CODE ,'Bank of Huludao (葫芦岛银行)' BANK_NAME UNION ALL
	SELECT '8600055' BANK_CODE ,'Bank of Shanghai (上海银行)' BANK_NAME UNION ALL
	SELECT '8600056' BANK_CODE ,'Zhejiang Chouzhou Commercial Bank (浙江稠州商业银行)' BANK_NAME UNION ALL
	SELECT '8600057' BANK_CODE ,'Hangzhou Bank (Hangzhou Commercial Bank) (杭州银行（杭州市商业银行）)' BANK_NAME UNION ALL
	SELECT '8600059' BANK_CODE ,'Bank of Ningbo (宁波银行)' BANK_NAME UNION ALL
	SELECT '8600061' BANK_CODE ,'Bank of Wenzhou (温州银行)' BANK_NAME UNION ALL
	SELECT '8600063' BANK_CODE ,'China Zheshang Bank (浙商银行)' BANK_NAME UNION ALL
	SELECT '8600065' BANK_CODE ,'Shanghai Rural Commercial Bank (上海农村商业银行)' BANK_NAME UNION ALL
	SELECT '8600066' BANK_CODE ,'Bank of China (中国银行)' BANK_NAME UNION ALL
	SELECT '8600069' BANK_CODE ,'Chongqing Rural Commercial Bank (重庆农村商业银行)' BANK_NAME UNION ALL
	SELECT '8600070' BANK_CODE ,'Jiangsu Bank (江苏银行)' BANK_NAME UNION ALL
	SELECT '8600071' BANK_CODE ,'Hubei Province Rural Credit Union (湖北省农村信用社联合社)' BANK_NAME UNION ALL
	SELECT '8600072' BANK_CODE ,'Guangdong Nanyue Bank (广东南粤银行)' BANK_NAME UNION ALL
	SELECT '8600073' BANK_CODE ,'Zhejiang Province Rural Credit Union (浙江省农村信用社联合社)' BANK_NAME UNION ALL
	SELECT '8600074' BANK_CODE ,'Fujian Province Rural Credit Union (福建省农村信用社联合社)' BANK_NAME UNION ALL
	SELECT '8600075' BANK_CODE ,'Lanzhou Bank (兰州银行)' BANK_NAME UNION ALL
	SELECT '8600076' BANK_CODE ,'Guilin Bank (桂林银行)' BANK_NAME UNION ALL
	SELECT '8600077' BANK_CODE ,'Jiangsu Province Rural Credit Union (江苏省农村信用社联合社)' BANK_NAME UNION ALL
	SELECT '8600078' BANK_CODE ,'Harbin Bank (哈尔滨银行)' BANK_NAME UNION ALL
	SELECT '8600079' BANK_CODE ,'Foshan Shunde Rural Commercial Bank (佛山顺德农村商业银行)' BANK_NAME UNION ALL
	SELECT '8600080' BANK_CODE ,'Rural Credit Union of Guangxi Zhuang Autonomous Region (广西壮族自治区农村信用社联合社)' BANK_NAME UNION ALL
	SELECT '8600081' BANK_CODE ,'Panzhihua Commercial Bank (攀枝花市商业银行)' BANK_NAME UNION ALL
	SELECT '8600082' BANK_CODE ,'Zhengzhou Bank (郑州银行)' BANK_NAME UNION ALL
	SELECT '8600083' BANK_CODE ,'Handan Commercial Bank (邯郸市商业银行)' BANK_NAME UNION ALL
	SELECT '8600084' BANK_CODE ,'Shandong Province Rural Credit Union (山东省农村信用社联合社)' BANK_NAME UNION ALL
	SELECT '8600085' BANK_CODE ,'Qilu Bank (齐鲁银行)' BANK_NAME UNION ALL
	SELECT '8600086' BANK_CODE ,'Taizhou Bank (台州银行)' BANK_NAME UNION ALL
	SELECT '8600087' BANK_CODE ,'Inner Mongolia Bank (内蒙古银行)' BANK_NAME UNION ALL
	SELECT '8600088' BANK_CODE ,'Guangdong Huaxing Bank (广东华兴银行)' BANK_NAME UNION ALL
	SELECT '8600089' BANK_CODE ,'Bank of Deyang (Great Wall Western China Bank) (德阳银行(长城华西银行）)' BANK_NAME UNION ALL
	SELECT '8600090' BANK_CODE ,'Chang’an Bank (长安银行)' BANK_NAME UNION ALL
	SELECT '8600091' BANK_CODE ,'Urumqi City Commercial Bank (乌鲁木齐市商业银行)' BANK_NAME UNION ALL
	SELECT '8600092' BANK_CODE ,'Weifang Bank (潍坊银行)' BANK_NAME UNION ALL
	SELECT '8600093' BANK_CODE ,'Jilin Bank (吉林银行)' BANK_NAME UNION ALL
	SELECT '8600094' BANK_CODE ,'Hengfeng Bank (恒丰银行)' BANK_NAME UNION ALL
	SELECT '8600095' BANK_CODE ,'Erdos Bank (鄂尔多斯银行)' BANK_NAME UNION ALL
	SELECT '8600096' BANK_CODE ,'Jiangsu Changshu Rural Commercial Bank (江苏常熟农村商业银行)' BANK_NAME UNION ALL
	SELECT '8600097' BANK_CODE ,'Hankou Bank (汉口银行)' BANK_NAME UNION ALL
	SELECT '8600098' BANK_CODE ,'Zhangjiakou Commercial bank (张家口市商业银行)' BANK_NAME UNION ALL
	SELECT '8600099' BANK_CODE ,'Huishang Bank (徽商银行)' BANK_NAME UNION ALL
	SELECT '8600100' BANK_CODE ,'Bank of Hebei (河北银行)' BANK_NAME UNION ALL
	SELECT '8600101' BANK_CODE ,'Jilin Rural Credit Cooperative Union (吉林省农村信用社联合社)' BANK_NAME UNION ALL
	SELECT '8600102' BANK_CODE ,'Zigong Commercial Bank (自贡市商业银行)' BANK_NAME UNION ALL
	SELECT '8600103' BANK_CODE ,'Guiyang Commercial Bank (Guiyang Bank) (贵阳市商业银行（贵阳银行）)' BANK_NAME UNION ALL
	SELECT '8600104' BANK_CODE ,'Bank of Kunlun (昆仑银行)' BANK_NAME UNION ALL
	SELECT '8600105' BANK_CODE ,'Bank of Liuzhou (柳州银行)' BANK_NAME UNION ALL
	SELECT '8600106' BANK_CODE ,'Ningxia Huanghe Rural Commercial Bank (宁夏黄河农村商业银行)' BANK_NAME UNION ALL
	SELECT '8600107' BANK_CODE ,'Jiangxi Ganzhou Rural Bank (江西赣州银座村镇银行)' BANK_NAME UNION ALL
	SELECT '8600108' BANK_CODE ,'Jincheng bank (晋城银行)' BANK_NAME UNION ALL
	SELECT '8600109' BANK_CODE ,'Longjiang Bank (龙江银行)' BANK_NAME UNION ALL
	SELECT '8600110' BANK_CODE ,'Zhuhai China Resources Bank (珠海华润银行)' BANK_NAME UNION ALL
	SELECT '8600111' BANK_CODE ,'Ganzhou Bank (赣州银行)' BANK_NAME UNION ALL
	SELECT '8600112' BANK_CODE ,'Chongqing Bank (重庆银行)' BANK_NAME UNION ALL
	SELECT '8600113' BANK_CODE ,'Jinshang Bank (晋商银行)' BANK_NAME UNION ALL
	SELECT '8600114' BANK_CODE ,'Hainan Rural Credit Union (海南省农村信用社联合社)' BANK_NAME UNION ALL
	SELECT '8600115' BANK_CODE ,'Fujian Haixia Bank (福建海峡银行)' BANK_NAME UNION ALL
	SELECT '8600116' BANK_CODE ,'Dezhou Bank (德州银行)' BANK_NAME UNION ALL
	SELECT '8600117' BANK_CODE ,'Bank of Luoyang (洛阳银行)' BANK_NAME UNION ALL
	SELECT '8600118' BANK_CODE ,'Bank of Xingtai (邢台银行)' BANK_NAME UNION ALL
	SELECT '8600119' BANK_CODE ,'Bank of Yingkou (营口银行)' BANK_NAME UNION ALL
	SELECT '8600120' BANK_CODE ,'Bank of Jiaxing (嘉兴银行)' BANK_NAME UNION ALL
	SELECT '8600121' BANK_CODE ,'Bank of Ningxia (宁夏银行)' BANK_NAME UNION ALL
	SELECT '8600122' BANK_CODE ,'Ningbo Yinzhou Rural Cooperative bank (宁波鄞州农村合作银行)' BANK_NAME UNION ALL
	SELECT '8600123' BANK_CODE ,'Bank of Cangzhou (沧州银行)' BANK_NAME UNION ALL
	SELECT '8600124' BANK_CODE ,'Bank of Langfang (廊坊银行)' BANK_NAME UNION ALL
	SELECT '8600125' BANK_CODE ,'Wujiang Rural Commercial Bank (吴江农村商业银行)' BANK_NAME UNION ALL
	SELECT '8600126' BANK_CODE ,'Bank of Chengde (承德银行)' BANK_NAME UNION ALL
	SELECT '8600127' BANK_CODE ,'Bank of Qinghai (青海银行)' BANK_NAME UNION ALL
	SELECT '8600128' BANK_CODE ,'Bank of Shaoxing (绍兴银行)' BANK_NAME UNION ALL
	SELECT '8600129' BANK_CODE ,'Xinhan Bank (新韩银行（中国）)' BANK_NAME UNION ALL
	SELECT '8600130' BANK_CODE ,'Mianyang City Commercial Bank (绵阳市商业银行)' BANK_NAME UNION ALL
	SELECT '8600131' BANK_CODE ,'Bank of Shangqiu (商丘市商业银行)' BANK_NAME UNION ALL
	SELECT '8600132' BANK_CODE ,'Bank of Fuxin (阜新银行)' BANK_NAME UNION ALL
	SELECT '8600133' BANK_CODE ,'Shenzhen Futian Yinzuo Rural Bank (深圳福田银座村镇银行)' BANK_NAME UNION ALL
	SELECT '8600134' BANK_CODE ,'Luohe City Commercial Bank (漯河市商业银行)' BANK_NAME UNION ALL
	SELECT '8600135' BANK_CODE ,'Beijing Shunyi Yinzuo Rural Bank (北京顺义银座村镇银行)' BANK_NAME UNION ALL
	SELECT '8600136' BANK_CODE ,'Industrial Bank of Korea (企业银行（中国）)' BANK_NAME UNION ALL
	SELECT '8600137' BANK_CODE ,'Woori Bank (友利银行(中国))' BANK_NAME UNION ALL
	SELECT '8600138' BANK_CODE ,'Chongqing Yubei Yinzuo Rural Bank (重庆渝北银座村镇银行)' BANK_NAME UNION ALL
	SELECT '8600139' BANK_CODE ,'Zhejiang Sanmen Yinzuo Rural Bank (浙江三门银座村镇银行)' BANK_NAME UNION ALL
	SELECT '8600023' BANK_CODE ,'China Merchants Bank (招商银行)' BANK_NAME
)x



DELETE b 
FROM #TempBankChina b
INNER JOIN dbo.API_BANK_LIST A ON A.BANK_CODE1=b.BANK_CODE

INSERT INTO API_BANK_LIST(API_PARTNER_ID,BANK_NAME,BANK_CODE1,BANK_STATE,BANK_DISTRICT,BANK_ADDRESS,BANK_PHONE
,BANK_EMAIL,SUPPORT_CURRENCY,BANK_COUNTRY,PAYMENT_TYPE_ID,IS_ACTIVE)
SELECT 394450, BANK_NAME, BANK_CODE, NULL, NULL, NULL, NULL, NULL, NULL, 'CHINA', 2, 1 FROM #TempBankChina

RETURN

------- Bank Of CHINA bAccType=7
--IF OBJECT_ID('tempdb..#TempBankChina7') IS NOT NULL
--			DROP TABLE #TempBankChina7


--SELECT * INTO #TempBankChina7
--FROM(
--	SELECT '8600001' BANK_CODE ,'BANK OF NANJING' BANK_NAME UNION ALL
--	SELECT '8600002' BANK_CODE ,'BAOSHANG BANK' BANK_NAME UNION ALL
--	SELECT '8600003' BANK_CODE ,'AGRICULTURAL BANK OF CHINA' BANK_NAME UNION ALL
--	SELECT '8600004' BANK_CODE ,'CHINA CONSTRUCTION BANK' BANK_NAME UNION ALL
--	SELECT '8600005' BANK_CODE ,'CHINA EVERBRIGHT BANK' BANK_NAME UNION ALL
--	SELECT '8600006' BANK_CODE ,'CHINA MINSHENG BANK' BANK_NAME UNION ALL
--	SELECT '8600007' BANK_CODE ,'INDUSTRIAL BANK CO LTD' BANK_NAME UNION ALL
--	SELECT '8600008' BANK_CODE ,'BEIJING RURAL COMMERCIAL BANK' BANK_NAME UNION ALL
--	SELECT '8600009' BANK_CODE ,'HANA BANK CHINA' BANK_NAME UNION ALL
--	SELECT '8600010' BANK_CODE ,'CHINA BOHAI BANK' BANK_NAME UNION ALL
--	SELECT '8600011' BANK_CODE ,'BANK OF TIANJIN' BANK_NAME UNION ALL
--	SELECT '8600012' BANK_CODE ,'TIANJIN RURAL COMMERCIAL BANK' BANK_NAME UNION ALL
--	SELECT '8600013' BANK_CODE ,'KOREA EXCHANGE BANK' BANK_NAME UNION ALL
--	SELECT '8600014' BANK_CODE ,'SHENZHEN RURAL COMMERCIAL BANK' BANK_NAME UNION ALL
--	SELECT '8600015' BANK_CODE ,'PING AN BANK' BANK_NAME UNION ALL
--	SELECT '8600016' BANK_CODE ,'DONGGUAN RURAL COMMERCIAL BANK' BANK_NAME UNION ALL
--	SELECT '8600017' BANK_CODE ,'BANK GUANGZHOU' BANK_NAME UNION ALL
--	SELECT '8600018' BANK_CODE ,'GUANGZHOU RURAL COMMERCIAL BANK' BANK_NAME UNION ALL
--	SELECT '8600019' BANK_CODE ,'INDUSTRIAL AND COMMERCIAL BANK CHINA' BANK_NAME UNION ALL
--	SELECT '8600020' BANK_CODE ,'BANK OF COMMUNICATIONS' BANK_NAME UNION ALL
--	SELECT '8600021' BANK_CODE ,'CHINA CITIC BANK' BANK_NAME UNION ALL
--	SELECT '8600022' BANK_CODE ,'HUA XIA BANK' BANK_NAME UNION ALL
--	SELECT '8600023' BANK_CODE ,'CHINA MERCHANTS BANK' BANK_NAME UNION ALL
--	SELECT '8600024' BANK_CODE ,'CHINA GUANGFA BANK' BANK_NAME UNION ALL
--	SELECT '8600025' BANK_CODE ,'POSTAL SAVINGS BANK OF CHINA' BANK_NAME UNION ALL
--	SELECT '8600026' BANK_CODE ,'BANK OF BEIJING' BANK_NAME UNION ALL
--	SELECT '8600027' BANK_CODE ,'SHINHAN BANK (CHINA)' BANK_NAME UNION ALL
--	SELECT '8600028' BANK_CODE ,'BANK OF DONGGUAN' BANK_NAME UNION ALL
--	SELECT '8600029' BANK_CODE ,'SHUNDE RURAL COMMERCIAL BANK' BANK_NAME UNION ALL
--	SELECT '8600030' BANK_CODE ,'SHANGHAI PUDONG DEVELOPMENT BANK' BANK_NAME UNION ALL
--	SELECT '8600031' BANK_CODE ,'ANHUI RURAL CREDIT UNION' BANK_NAME UNION ALL
--	SELECT '8600032' BANK_CODE ,'XIAMEN BANK' BANK_NAME UNION ALL
--	SELECT '8600033' BANK_CODE ,'GUANGXI BEIBU GULF BANK' BANK_NAME UNION ALL
--	SELECT '8600034' BANK_CODE ,'BANK OF CHANGSHA' BANK_NAME UNION ALL
--	SELECT '8600035' BANK_CODE ,'KUNSHAN RURAL COMMERCIAL BANK' BANK_NAME UNION ALL
--	SELECT '8600036' BANK_CODE ,'BANK OF SUZHOU' BANK_NAME UNION ALL
--	SELECT '8600037' BANK_CODE ,'RURAL COMMERCIAL BANK OF ZHANGJIAGANG' BANK_NAME UNION ALL
--	SELECT '8600038' BANK_CODE ,'BANK OF NANCHANG' BANK_NAME UNION ALL
--	SELECT '8600039' BANK_CODE ,'BANK OF SHANGRAO' BANK_NAME UNION ALL
--	SELECT '8600041' BANK_CODE ,'BANK OF JINING' BANK_NAME UNION ALL
--	SELECT '8600042' BANK_CODE ,'LAISHANG BANK' BANK_NAME UNION ALL
--	SELECT '8600043' BANK_CODE ,'LINSHANG BANK' BANK_NAME UNION ALL
--	SELECT '8600044' BANK_CODE ,'QISHANG BANK' BANK_NAME UNION ALL
--	SELECT '8600045' BANK_CODE ,'BANK OF QINGDAO' BANK_NAME UNION ALL
--	SELECT '8600046' BANK_CODE ,'BANK OF RIZHAO' BANK_NAME UNION ALL
--	SELECT '8600047' BANK_CODE ,'TAIAN CITY COMMERCIAL BANK' BANK_NAME UNION ALL
--	SELECT '8600048' BANK_CODE ,'WEIHAI CITY COMMERCIAL BANK' BANK_NAME UNION ALL
--	SELECT '8600049' BANK_CODE ,'YANTAI BANK' BANK_NAME UNION ALL
--	SELECT '8600050' BANK_CODE ,'BANK OF DALIAN' BANK_NAME UNION ALL
--	SELECT '8600051' BANK_CODE ,'BANK OF JINZHOU' BANK_NAME UNION ALL
--	SELECT '8600053' BANK_CODE ,'BANK OF HULUDAO' BANK_NAME UNION ALL
--	SELECT '8600055' BANK_CODE ,'BANK OF SHANGHAI' BANK_NAME UNION ALL
--	SELECT '8600056' BANK_CODE ,'ZHEJIANG CHOUZHOU COMMERCIAL BANK' BANK_NAME UNION ALL
--	SELECT '8600057' BANK_CODE ,'BANK OF HANGZHOU' BANK_NAME UNION ALL
--	SELECT '8600058' BANK_CODE ,'BANK OF HUZHOU' BANK_NAME UNION ALL
--	SELECT '8600059' BANK_CODE ,'BANK OF NINGBO' BANK_NAME UNION ALL
--	SELECT '8600060' BANK_CODE ,'ZHEJIANG TAILONG COMMERCIAL BANK' BANK_NAME UNION ALL
--	SELECT '8600061' BANK_CODE ,'BANK OF WENZHOU' BANK_NAME UNION ALL
--	SELECT '8600062' BANK_CODE ,'YINZHOU BANK' BANK_NAME UNION ALL
--	SELECT '8600063' BANK_CODE ,'CHINA ZHESHANG BANK' BANK_NAME UNION ALL
--	SELECT '8600064' BANK_CODE ,'YELLOW RIVER RURAL COMMERCIAL BANK' BANK_NAME UNION ALL
--	SELECT '8600065' BANK_CODE ,'SHANGHAI RURAL COMMERCIAL BANK' BANK_NAME UNION ALL
--	SELECT '8600066' BANK_CODE ,'Bank of China' BANK_NAME
--)x

--DELETE b 
--FROM #TempBankChina7 b
--INNER JOIN dbo.API_BANK_LIST A ON A.BANK_CODE1=b.BANK_CODE

--INSERT INTO API_BANK_LIST(API_PARTNER_ID,BANK_NAME,BANK_CODE1,BANK_STATE,BANK_DISTRICT,BANK_ADDRESS,BANK_PHONE
--,BANK_EMAIL,SUPPORT_CURRENCY,BANK_COUNTRY,PAYMENT_TYPE_ID,IS_ACTIVE)
--SELECT 394450, BANK_NAME, BANK_CODE, NULL, NULL, NULL, NULL, NULL, NULL, 'CHINA', 1, 1 FROM #TempBankChina7
