----- Bank Of Malaysia
IF OBJECT_ID('tempdb..#TempBankMalaysia') IS NOT NULL
			DROP TABLE #TempBankMalaysia

SELECT * INTO #TempBankMalaysia
FROM
(
	SELECT 'Affin Bank Berhad' BANK_NAME, '6000001' BANK_CODE UNION ALL
	SELECT 'Affin Islamic Bank Berhad' BANK_NAME, '6000002' BANK_CODE UNION ALL
	SELECT 'Agro Bank' BANK_NAME, '6000003' BANK_CODE UNION ALL
	SELECT 'Alliance Bank Berhad' BANK_NAME, '6000004' BANK_CODE UNION ALL
	SELECT 'Alliance Islamic Bank Berhad' BANK_NAME, '6000005' BANK_CODE UNION ALL
	SELECT 'Al-Rajhi Banking and Investment Corporation (M)' BANK_NAME, '6000006' BANK_CODE UNION ALL
	SELECT 'AmIslamic Bank' BANK_NAME, '6000007' BANK_CODE UNION ALL
	SELECT 'Arab-Malaysian Bank Berhad' BANK_NAME, '6000008' BANK_CODE UNION ALL
	SELECT 'Bank Islam Malaysia Berhad' BANK_NAME, '6000009' BANK_CODE UNION ALL
	SELECT 'Bank Kerjasama Rakyat Berhad' BANK_NAME, '6000010' BANK_CODE UNION ALL
	SELECT 'Bank Muamalat Malaysia Berhad' BANK_NAME, '6000011' BANK_CODE UNION ALL
	SELECT 'Bank of America Malaysia Berhad' BANK_NAME, '6000012' BANK_CODE UNION ALL
	SELECT 'Bank Simpanan Nasional Berhad' BANK_NAME, '6000014' BANK_CODE UNION ALL
	SELECT 'BNP Paribas (M) Bhd' BANK_NAME, '6000015' BANK_CODE UNION ALL
	SELECT 'BNP Paribas (M) Bhd (Islamic)' BANK_NAME, '6000016' BANK_CODE UNION ALL
	SELECT 'CIMB Bank Berhad' BANK_NAME, '6000017' BANK_CODE UNION ALL
	SELECT 'CIMB Islamic Bank' BANK_NAME, '6000018' BANK_CODE UNION ALL
	SELECT 'Citibank' BANK_NAME, '6000019' BANK_CODE UNION ALL
	SELECT 'Deutsche Bank (M) Bhd' BANK_NAME, '6000021' BANK_CODE UNION ALL
	SELECT 'Hong Leong Bank Bhd' BANK_NAME, '6000022' BANK_CODE UNION ALL
	SELECT 'Hong Leong Islamic Bank Bhd' BANK_NAME, '6000023' BANK_CODE UNION ALL
	SELECT 'HSBC Amanah Malaysia' BANK_NAME, '6000024' BANK_CODE UNION ALL
	SELECT 'HSBC Bank Berhad' BANK_NAME, '6000025' BANK_CODE UNION ALL
	SELECT 'Indust & Comm Bank of China (M) Berhad' BANK_NAME, '6000026' BANK_CODE UNION ALL
	SELECT 'JP Morgan Chase Bank Berhad' BANK_NAME, '6000027' BANK_CODE UNION ALL
	SELECT 'Kuwait Finance House Malaysia Berhad' BANK_NAME, '6000028' BANK_CODE UNION ALL
	SELECT 'Malayan Banking Berhad' BANK_NAME, '6000029' BANK_CODE UNION ALL
	SELECT 'MayBank Islamic Berhad' BANK_NAME, '6000030' BANK_CODE UNION ALL
	SELECT 'Mizuho Bank (M) Berhad' BANK_NAME, '6000031' BANK_CODE UNION ALL
	SELECT 'OCBC AL-AMIN Bank Berhad' BANK_NAME, '6000032' BANK_CODE UNION ALL
	SELECT 'OCBC Bank Berhad' BANK_NAME, '6000033' BANK_CODE UNION ALL
	SELECT 'Public Bank Bhd' BANK_NAME, '6000034' BANK_CODE UNION ALL
	SELECT 'Public Finance Bhd' BANK_NAME, '6000035' BANK_CODE UNION ALL
	SELECT 'Public Islamic Bank Bhd' BANK_NAME, '6000036' BANK_CODE UNION ALL
	SELECT 'RHB Bank Berhad' BANK_NAME, '6000037' BANK_CODE UNION ALL
	SELECT 'RHB Islamic Bank Berhad' BANK_NAME, '6000038' BANK_CODE UNION ALL
	SELECT 'Standard Chartered Bank' BANK_NAME, '6000039' BANK_CODE UNION ALL
	SELECT 'Standard Chartered SAADIQ Bhd' BANK_NAME, '6000040' BANK_CODE UNION ALL
	SELECT 'Sumitomo Mitsui Banking Corporation (M) Bhd' BANK_NAME, '6000041' BANK_CODE UNION ALL
	SELECT 'United Overseas Bank (M) Bhd' BANK_NAME, '6000043' BANK_CODE UNION ALL
	SELECT 'Agrobank (Islamic)' BANK_NAME, '6000046' BANK_CODE UNION ALL
	SELECT 'Bank Simpanan Nasional Berhad (Islamic)' BANK_NAME, '6000048' BANK_CODE	
)x


DELETE b 
FROM #TempBankMalaysia b
INNER JOIN dbo.API_BANK_LIST A ON A.BANK_CODE1=b.BANK_CODE

INSERT INTO API_BANK_LIST(API_PARTNER_ID,BANK_NAME,BANK_CODE1,BANK_STATE,BANK_DISTRICT,BANK_ADDRESS,BANK_PHONE
,BANK_EMAIL,SUPPORT_CURRENCY,BANK_COUNTRY,PAYMENT_TYPE_ID,IS_ACTIVE)
SELECT 394450, BANK_NAME, BANK_CODE, NULL, NULL, NULL, NULL, NULL, NULL, 'MALAYSIA', 2, 1 FROM #TempBankMalaysia