---- Bank Code Of Cambodia
IF OBJECT_ID('tempdb..#TempBankCambodiaKHR') IS NOT NULL
			DROP TABLE #TempBankCambodiaKHR


SELECT * INTO #TempBankCambodiaKHR FROM 
(
SELECT 'Foreign Trade Bank of Cambodia' BANK_NAME ,'8550001' BANK_CODE ,'KHR' SUPPORT_CURRENCY UNION ALL
SELECT 'Cambodia Commercial Bank LTD' BANK_NAME ,'8550002' BANK_CODE ,'KHR' SUPPORT_CURRENCY UNION ALL
SELECT 'Cambodia Public Bank PLC' BANK_NAME ,'8550003' BANK_CODE ,'KHR' SUPPORT_CURRENCY UNION ALL
SELECT 'Canadia Bank PLC' BANK_NAME ,'8550004' BANK_CODE ,'KHR' SUPPORT_CURRENCY UNION ALL
SELECT 'Krung Thai Bank Public Co LTD PP Branch' BANK_NAME ,'8550005' BANK_CODE ,'KHR' SUPPORT_CURRENCY UNION ALL
SELECT 'Cambodia Asia Bank LTD' BANK_NAME ,'8550006' BANK_CODE ,'KHR' SUPPORT_CURRENCY UNION ALL
SELECT 'May Bank (Cambodia) PLC' BANK_NAME ,'8550007' BANK_CODE ,'KHR' SUPPORT_CURRENCY UNION ALL
SELECT 'Union Commercial Bank PLC' BANK_NAME ,'8550008' BANK_CODE ,'KHR' SUPPORT_CURRENCY UNION ALL
SELECT 'Cambodia Mekong Bank Public LTD' BANK_NAME ,'8550009' BANK_CODE ,'KHR' SUPPORT_CURRENCY UNION ALL
SELECT 'Advanced Bank of Asia LTD' BANK_NAME ,'8550010' BANK_CODE ,'KHR' SUPPORT_CURRENCY UNION ALL
SELECT 'Rural Development Bank' BANK_NAME ,'8550011' BANK_CODE ,'KHR' SUPPORT_CURRENCY UNION ALL
SELECT 'First Commercial Bank, Phnom Penh Branch' BANK_NAME ,'8550012' BANK_CODE ,'KHR' SUPPORT_CURRENCY UNION ALL
SELECT 'Acleda Bank' BANK_NAME ,'8550013' BANK_CODE ,'KHR' SUPPORT_CURRENCY UNION ALL
SELECT 'Vattanac Bank' BANK_NAME ,'8550014' BANK_CODE ,'KHR' SUPPORT_CURRENCY UNION ALL
SELECT 'J Trust Royal Bank Ltd' BANK_NAME ,'8550015' BANK_CODE ,'KHR' SUPPORT_CURRENCY UNION ALL
SELECT 'Shinhan Khmer Bank' BANK_NAME ,'8550016' BANK_CODE ,'KHR' SUPPORT_CURRENCY UNION ALL
SELECT 'SATHAPANA BANK PLC' BANK_NAME ,'8550017' BANK_CODE ,'KHR' SUPPORT_CURRENCY UNION ALL
SELECT 'Phnom Penh Commercial Bank' BANK_NAME ,'8550018' BANK_CODE ,'KHR' SUPPORT_CURRENCY UNION ALL
SELECT 'Booyong Khmer Bank' BANK_NAME ,'8550019' BANK_CODE ,'KHR' SUPPORT_CURRENCY UNION ALL
SELECT 'SACOM Bank (Cambodia) PLC' BANK_NAME ,'8550020' BANK_CODE ,'KHR' SUPPORT_CURRENCY UNION ALL
SELECT 'Kookmin Bank Cambodia PLC' BANK_NAME ,'8550021' BANK_CODE ,'KHR' SUPPORT_CURRENCY UNION ALL
SELECT 'Bank for Investment and Development of Cambodia Plc' BANK_NAME ,'8550022' BANK_CODE ,'KHR' SUPPORT_CURRENCY UNION ALL
SELECT 'ICBC Limited Phnom Penh Branch' BANK_NAME ,'8550023' BANK_CODE ,'KHR' SUPPORT_CURRENCY UNION ALL
SELECT 'Agri Bank of Cambodia (Vietnam Bank)' BANK_NAME ,'8550024' BANK_CODE ,'KHR' SUPPORT_CURRENCY UNION ALL
SELECT 'Bank of China Limted Phnom Penh Branch' BANK_NAME ,'8550025' BANK_CODE ,'KHR' SUPPORT_CURRENCY UNION ALL
SELECT 'CIMB Bank PLC' BANK_NAME ,'8550026' BANK_CODE ,'KHR' SUPPORT_CURRENCY UNION ALL
SELECT 'Mega International Bank Co LTD PP Branch' BANK_NAME ,'8550027' BANK_CODE ,'KHR' SUPPORT_CURRENCY UNION ALL
SELECT 'MB Bank PLC Phnom Penh Branch' BANK_NAME ,'8550028' BANK_CODE ,'KHR' SUPPORT_CURRENCY UNION ALL
SELECT 'SHB PLC Phnom Penh Branch' BANK_NAME ,'8550029' BANK_CODE ,'KHR' SUPPORT_CURRENCY UNION ALL
SELECT 'Taiwan Cooperative Bank PP Branch' BANK_NAME ,'8550030' BANK_CODE ,'KHR' SUPPORT_CURRENCY UNION ALL
SELECT 'Hong Leong Bank (Cambodia) PLC' BANK_NAME ,'8550031' BANK_CODE ,'KHR' SUPPORT_CURRENCY UNION ALL
SELECT 'RHB Indochina (Cambodia) PLC' BANK_NAME ,'8550032' BANK_CODE ,'KHR' SUPPORT_CURRENCY UNION ALL
SELECT 'Cambodia Post Bank PLC' BANK_NAME ,'8550033' BANK_CODE ,'KHR' SUPPORT_CURRENCY UNION ALL
SELECT 'Cathay United Bank (Cambodia) Corporation Bank' BANK_NAME ,'8550034' BANK_CODE ,'KHR' SUPPORT_CURRENCY UNION ALL
SELECT 'Phillip Bank PLC' BANK_NAME ,'8550035' BANK_CODE ,'KHR' SUPPORT_CURRENCY UNION ALL
SELECT 'Bangkok Bank Plc Cambodia Branch' BANK_NAME ,'8550036' BANK_CODE ,'KHR' SUPPORT_CURRENCY UNION ALL
SELECT 'KASIKORN BANK' BANK_NAME ,'8550037' BANK_CODE ,'KHR' SUPPORT_CURRENCY UNION ALL
SELECT 'Bred Bank PLC' BANK_NAME ,'8550038' BANK_CODE ,'KHR' SUPPORT_CURRENCY UNION ALL
SELECT 'National Bank of Cambodia' BANK_NAME ,'8550039' BANK_CODE ,'KHR' SUPPORT_CURRENCY UNION ALL
SELECT 'Chief (Cambodia) Commercial Bank Plc.' BANK_NAME ,'8550040' BANK_CODE ,'KHR' SUPPORT_CURRENCY UNION ALL
SELECT 'Prince Bank Plc.' BANK_NAME ,'8550041' BANK_CODE ,'KHR' SUPPORT_CURRENCY UNION ALL
SELECT 'Industrial Bank of Korea Phnom Penh Branch.' BANK_NAME ,'8550042' BANK_CODE ,'KHR' SUPPORT_CURRENCY UNION ALL
SELECT 'BIC (Cambodia ) Bank Plc.' BANK_NAME ,'8550043' BANK_CODE ,'KHR' SUPPORT_CURRENCY UNION ALL
SELECT 'CHIP MONG COMMERCIAL BANK PLC' BANK_NAME ,'8550044' BANK_CODE ,'KHR' SUPPORT_CURRENCY UNION ALL
SELECT 'AMK MFI' BANK_NAME ,'8550045' BANK_CODE ,'KHR' SUPPORT_CURRENCY UNION ALL
SELECT 'WB FINANCE' BANK_NAME ,'8550046' BANK_CODE ,'KHR' SUPPORT_CURRENCY UNION ALL
SELECT 'HATHAKASEKAR MFI' BANK_NAME ,'8550047' BANK_CODE ,'KHR' SUPPORT_CURRENCY UNION ALL
SELECT 'AMRET MFI' BANK_NAME ,'8550048' BANK_CODE ,'KHR' SUPPORT_CURRENCY UNION ALL
SELECT 'KREDIT MFI' BANK_NAME ,'8550049' BANK_CODE ,'KHR' SUPPORT_CURRENCY UNION ALL
SELECT 'PRASAC MFI' BANK_NAME ,'8550050' BANK_CODE ,'KHR' SUPPORT_CURRENCY UNION ALL
SELECT 'LOLC MFI' BANK_NAME ,'8550051' BANK_CODE ,'KHR' SUPPORT_CURRENCY
)x

DELETE b 
FROM #TempBankCambodiaKHR b
INNER JOIN dbo.API_BANK_LIST A ON A.BANK_CODE1=b.BANK_CODE

INSERT INTO API_BANK_LIST(API_PARTNER_ID,BANK_NAME,BANK_CODE1,SUPPORT_CURRENCY,BANK_COUNTRY,PAYMENT_TYPE_ID,IS_ACTIVE)
SELECT 394450, BANK_NAME, BANK_CODE, SUPPORT_CURRENCY, 'CAMBODIA', 2, 1 FROM #TempBankCambodiaKHR


---- Bank Code Of Cambodia USD
IF OBJECT_ID('tempdb..#TempBankCambodiaUSD') IS NOT NULL
			DROP TABLE #TempBankCambodiaUSD

SELECT * INTO #TempBankCambodiaUSD FROM 
(
SELECT 'Foreign Trade Bank of Cambodia (USD)' BANK_NAME ,'8550052' BANK_CODE , 'USD' SUPPORT_CURRENCY UNION ALL
SELECT 'Cambodia Commercial Bank LTD (USD)' BANK_NAME ,'8550053' BANK_CODE , 'USD' SUPPORT_CURRENCY UNION ALL
SELECT 'Cambodia Public Bank PLC (USD)' BANK_NAME ,'8550054' BANK_CODE , 'USD' SUPPORT_CURRENCY UNION ALL
SELECT 'Canadia Bank PLC (USD)' BANK_NAME ,'8550055' BANK_CODE , 'USD' SUPPORT_CURRENCY UNION ALL
SELECT 'Krung Thai Bank Public Co LTD PP Branch (USD)' BANK_NAME ,'8550056' BANK_CODE , 'USD' SUPPORT_CURRENCY UNION ALL
SELECT 'Cambodia Asia Bank LTD (USD)' BANK_NAME ,'8550057' BANK_CODE , 'USD' SUPPORT_CURRENCY UNION ALL
SELECT 'May Bank (Cambodia) PLC (USD)' BANK_NAME ,'8550058' BANK_CODE , 'USD' SUPPORT_CURRENCY UNION ALL
SELECT 'Union Commercial Bank PLC (USD)' BANK_NAME ,'8550059' BANK_CODE , 'USD' SUPPORT_CURRENCY UNION ALL
SELECT 'Cambodia Mekong Bank Public LTD (USD)' BANK_NAME ,'8550060' BANK_CODE , 'USD' SUPPORT_CURRENCY UNION ALL
SELECT 'Advanced Bank of Asia LTD (USD)' BANK_NAME ,'8550061' BANK_CODE , 'USD' SUPPORT_CURRENCY UNION ALL
SELECT 'Rural Development Bank (USD)' BANK_NAME ,'8550062' BANK_CODE , 'USD' SUPPORT_CURRENCY UNION ALL
SELECT 'First Commercial Bank, Phnom Penh Branch (USD)' BANK_NAME ,'8550063' BANK_CODE , 'USD' SUPPORT_CURRENCY UNION ALL
SELECT 'Acleda Bank (USD)' BANK_NAME ,'8550064' BANK_CODE , 'USD' SUPPORT_CURRENCY UNION ALL
SELECT 'Vattanac Bank (USD)' BANK_NAME ,'8550065' BANK_CODE , 'USD' SUPPORT_CURRENCY UNION ALL
SELECT 'J Trust Royal Bank Ltd (USD)' BANK_NAME ,'8550066' BANK_CODE , 'USD' SUPPORT_CURRENCY UNION ALL
SELECT 'Shinhan Khmer Bank (USD)' BANK_NAME ,'8550067' BANK_CODE , 'USD' SUPPORT_CURRENCY UNION ALL
SELECT 'SATHAPANA BANK PLC (USD)' BANK_NAME ,'8550068' BANK_CODE , 'USD' SUPPORT_CURRENCY UNION ALL
SELECT 'Phnom Penh Commercial Bank (USD)' BANK_NAME ,'8550069' BANK_CODE , 'USD' SUPPORT_CURRENCY UNION ALL
SELECT 'Booyong Khmer Bank (USD)' BANK_NAME ,'8550070' BANK_CODE , 'USD' SUPPORT_CURRENCY UNION ALL
SELECT 'SACOM Bank (Cambodia) PLC (USD)' BANK_NAME ,'8550071' BANK_CODE , 'USD' SUPPORT_CURRENCY UNION ALL
SELECT 'Kookmin Bank Cambodia PLC (USD)' BANK_NAME ,'8550072' BANK_CODE , 'USD' SUPPORT_CURRENCY UNION ALL
SELECT 'Bank for Investment and Development of Cambodia Plc (USD)' BANK_NAME ,'8550073' BANK_CODE , 'USD' SUPPORT_CURRENCY UNION ALL
SELECT 'ICBC Limited Phnom Penh Branch (USD)' BANK_NAME ,'8550074' BANK_CODE , 'USD' SUPPORT_CURRENCY UNION ALL
SELECT 'Agri Bank of Cambodia (Vietnam Bank) (USD)' BANK_NAME ,'8550075' BANK_CODE , 'USD' SUPPORT_CURRENCY UNION ALL
SELECT 'Bank of China Limted Phnom Penh Branch (USD)' BANK_NAME ,'8550076' BANK_CODE , 'USD' SUPPORT_CURRENCY UNION ALL
SELECT 'CIMB Bank PLC (USD)' BANK_NAME ,'8550077' BANK_CODE , 'USD' SUPPORT_CURRENCY UNION ALL
SELECT 'Mega International Bank Co LTD PP Branch (USD)' BANK_NAME ,'8550078' BANK_CODE , 'USD' SUPPORT_CURRENCY UNION ALL
SELECT 'MB Bank PLC Phnom Penh Branch (USD)' BANK_NAME ,'8550079' BANK_CODE , 'USD' SUPPORT_CURRENCY UNION ALL
SELECT 'SHB PLC Phnom Penh Branch (USD)' BANK_NAME ,'8550080' BANK_CODE , 'USD' SUPPORT_CURRENCY UNION ALL
SELECT 'Taiwan Cooperative Bank PP Branch (USD)' BANK_NAME ,'8550081' BANK_CODE , 'USD' SUPPORT_CURRENCY UNION ALL
SELECT 'Hong Leong Bank (Cambodia) PLC (USD)' BANK_NAME ,'8550082' BANK_CODE , 'USD' SUPPORT_CURRENCY UNION ALL
SELECT 'RHB Indochina (Cambodia) PLC (USD)' BANK_NAME ,'8550083' BANK_CODE , 'USD' SUPPORT_CURRENCY UNION ALL
SELECT 'Cambodia Post Bank PLC (USD)' BANK_NAME ,'8550084' BANK_CODE , 'USD' SUPPORT_CURRENCY UNION ALL
SELECT 'Cathay United Bank (Cambodia) Corporation Bank (USD)' BANK_NAME ,'8550085' BANK_CODE , 'USD' SUPPORT_CURRENCY UNION ALL
SELECT 'Phillip Bank PLC (USD)' BANK_NAME ,'8550086' BANK_CODE , 'USD' SUPPORT_CURRENCY UNION ALL
SELECT 'Bangkok Bank Plc Cambodia Branch (USD)' BANK_NAME ,'8550087' BANK_CODE , 'USD' SUPPORT_CURRENCY UNION ALL
SELECT 'KASIKORN BANK (USD)' BANK_NAME ,'8550088' BANK_CODE , 'USD' SUPPORT_CURRENCY UNION ALL
SELECT 'Bred Bank PLC (USD)' BANK_NAME ,'8550089' BANK_CODE , 'USD' SUPPORT_CURRENCY UNION ALL
SELECT 'National Bank of Cambodia (USD)' BANK_NAME ,'8550090' BANK_CODE , 'USD' SUPPORT_CURRENCY UNION ALL
SELECT 'Chief (Cambodia) Commercial Bank Plc. (USD)' BANK_NAME ,'8550091' BANK_CODE , 'USD' SUPPORT_CURRENCY UNION ALL
SELECT 'Prince Bank Plc. (USD)' BANK_NAME ,'8550092' BANK_CODE , 'USD' SUPPORT_CURRENCY UNION ALL
SELECT 'Industrial Bank of Korea Phnom Penh Branch. (USD)' BANK_NAME ,'8550093' BANK_CODE , 'USD' SUPPORT_CURRENCY UNION ALL
SELECT 'BIC (Cambodia ) Bank Plc. (USD)' BANK_NAME ,'8550094' BANK_CODE , 'USD' SUPPORT_CURRENCY UNION ALL
SELECT 'CHIP MONG COMMERCIAL BANK PLC (USD)' BANK_NAME ,'8550095' BANK_CODE , 'USD' SUPPORT_CURRENCY UNION ALL
SELECT 'AMK MFI (USD)' BANK_NAME ,'8550096' BANK_CODE , 'USD' SUPPORT_CURRENCY UNION ALL
SELECT 'WB FINANCE (USD)' BANK_NAME ,'8550097' BANK_CODE , 'USD' SUPPORT_CURRENCY UNION ALL
SELECT 'HATHAKASEKAR MFI (USD)' BANK_NAME ,'8550098' BANK_CODE , 'USD' SUPPORT_CURRENCY UNION ALL
SELECT 'AMRET MFI (USD)' BANK_NAME ,'8550099' BANK_CODE , 'USD' SUPPORT_CURRENCY UNION ALL
SELECT 'KREDIT MFI (USD)' BANK_NAME ,'8550100' BANK_CODE , 'USD' SUPPORT_CURRENCY UNION ALL
SELECT 'PRASAC MFI (USD)' BANK_NAME ,'8550101' BANK_CODE , 'USD' SUPPORT_CURRENCY UNION ALL
SELECT 'LOLC MFI (USD)' BANK_NAME ,'8550102' BANK_CODE , 'USD' SUPPORT_CURRENCY
)x

DELETE b 
FROM #TempBankCambodiaUSD b
INNER JOIN dbo.API_BANK_LIST A ON A.BANK_CODE1=b.BANK_CODE

INSERT INTO API_BANK_LIST(API_PARTNER_ID,BANK_NAME,BANK_CODE1,SUPPORT_CURRENCY,BANK_COUNTRY,PAYMENT_TYPE_ID,IS_ACTIVE)
SELECT 394450, BANK_NAME, BANK_CODE, SUPPORT_CURRENCY,'CAMBODIA', 2, 1 FROM #TempBankCambodiaUSD

---- Bank Code Of Cambodia For cash
IF NOT EXISTS(SELECT 'c' FROM dbo.API_BANK_LIST WHERE BANK_CODE1='CPWNG')
BEGIN
INSERT INTO dbo.API_BANK_LIST
        ( API_PARTNER_ID ,BANK_NAME ,BANK_CODE1 ,BANK_CODE2 ,BANK_COUNTRY ,PAYMENT_TYPE_ID ,IS_ACTIVE
        )
SELECT '394450','Wing (Cambodia) Limited Specialised Bank','CPWNG','56451685','CAMBODIA',1,1
END

RETURN
---- Bank Code Of Cambodia wallet
IF NOT EXISTS(SELECT 'c' FROM dbo.API_BANK_LIST WHERE BANK_CODE1='EWWNG')
BEGIN
INSERT INTO dbo.API_BANK_LIST
        ( API_PARTNER_ID ,BANK_NAME ,BANK_CODE1 ,BANK_CODE2 ,BANK_COUNTRY ,PAYMENT_TYPE_ID ,IS_ACTIVE
        )
SELECT '394450','Wing (Cambodia) Limited Specialised Bank','EWWNG','56451685','CAMBODIA',13,1
END