------------bank Republic of South Korea
IF OBJECT_ID('tempdb..#TempBankKorea') IS NOT NULL
			DROP TABLE #TempBankKorea

SELECT * INTO #TempBankKorea
FROM
(
	SELECT N'Korea Development Bank' BANK_NAME, '820001' BANK_CODE UNION ALL
	SELECT N'부산은행:Busan Bank' BANK_NAME, '820002' BANK_CODE UNION ALL
	SELECT N'IBK기업:Industrial Bank of Korea' BANK_NAME, '820003' BANK_CODE UNION ALL
	SELECT N'KB국민:Kookmin Bank' BANK_NAME, '820004' BANK_CODE UNION ALL
	SELECT N'제주은행:Jeju Bank' BANK_NAME, '820005' BANK_CODE UNION ALL
	SELECT N'수협은행:Suhyup Bank' BANK_NAME, '820006' BANK_CODE UNION ALL
	SELECT N'경남은행:Kyongnam Bank' BANK_NAME, '820007' BANK_CODE UNION ALL
	SELECT N'NH농협:National Agricultural Cooperative Federation' BANK_NAME, '820008' BANK_CODE UNION ALL
	SELECT N'우리은행:Woori Bank' BANK_NAME, '820010' BANK_CODE UNION ALL
	SELECT N'SC은행:Standard Chartered First Bank Korea' BANK_NAME, '820011' BANK_CODE UNION ALL
	SELECT N'신한은행:Shinhan Bank' BANK_NAME, '820013' BANK_CODE UNION ALL
	SELECT N'대구은행:Daegu Bank' BANK_NAME, '820014' BANK_CODE UNION ALL
	SELECT N'하나은행:Hana Bank' BANK_NAME, '820015' BANK_CODE UNION ALL
	SELECT N'Kakao Bank' BANK_NAME, '820017' BANK_CODE UNION ALL
	SELECT N'Korea Citi Bank' BANK_NAME, '820018' BANK_CODE UNION ALL
	SELECT N'K-Bank' BANK_NAME, '820020' BANK_CODE UNION ALL
	SELECT N'JeonBuk Bank' BANK_NAME, '820023' BANK_CODE
)x

DELETE b 
FROM #TempBankKorea b
INNER JOIN dbo.API_BANK_LIST A ON A.BANK_CODE1=b.BANK_CODE

INSERT INTO API_BANK_LIST(API_PARTNER_ID,BANK_NAME,BANK_CODE1,BANK_STATE,BANK_DISTRICT,BANK_ADDRESS,BANK_PHONE
,BANK_EMAIL,SUPPORT_CURRENCY,BANK_COUNTRY,PAYMENT_TYPE_ID,IS_ACTIVE)
SELECT 394450, BANK_NAME, BANK_CODE, NULL, NULL, NULL, NULL, NULL, NULL, 'SOUTH KOREA', 2, 1 FROM #TempBankKorea
