IF OBJECT_ID('tempdb..#AustraliaBANK') IS NOT NULL
			DROP TABLE #AustraliaBANK
SELECT * INTO #AustraliaBANK
FROM
(
SELECT '610002' BANK_CODE, 'AMP' BANK_CODE2, 'AMP Bank Limited' BANK_NAME UNION ALL
SELECT '610003' BANK_CODE, 'ARA' BANK_CODE2, 'Arab Bank Australia Limited' BANK_NAME UNION ALL
SELECT '610004' BANK_CODE, 'ANZ' BANK_CODE2, 'Australia and New Zealand Banking Group Limited' BANK_NAME UNION ALL
SELECT '610005' BANK_CODE, 'ADC' BANK_CODE2, 'Australian Military Bank' BANK_NAME UNION ALL
SELECT '610006' BANK_CODE, 'ASL' BANK_CODE2, 'Australian Settlements Limited (ASL)' BANK_NAME UNION ALL
SELECT '610006' BANK_CODE, 'ALX' BANK_CODE2, 'Australian Settlements Limited (ALX)' BANK_NAME UNION ALL
SELECT '610007' BANK_CODE, 'MCU' BANK_CODE2, 'Bank Australia' BANK_NAME UNION ALL
SELECT '610008' BANK_CODE, 'BCA' BANK_CODE2, 'Bank of China Australia Limited' BANK_NAME UNION ALL
SELECT '610010' BANK_CODE, 'BOM' BANK_CODE2, 'Bank of Melbourne' BANK_NAME UNION ALL
SELECT '610011' BANK_CODE, 'BQL' BANK_CODE2, 'Bank of Queensland Limited' BANK_NAME UNION ALL
SELECT '610013' BANK_CODE, 'BSA' BANK_CODE2, 'Bank SA' BANK_NAME UNION ALL
SELECT '610015' BANK_CODE, 'BBL' BANK_CODE2, 'Bendigo and Adelaide Bank Limited' BANK_NAME UNION ALL
SELECT '610016' BANK_CODE, 'BYB' BANK_CODE2, 'Beyond Bank Australia' BANK_NAME UNION ALL
SELECT '610017' BANK_CODE, 'CBA' BANK_CODE2, 'Commonwealth Bank' BANK_NAME UNION ALL
SELECT '610018' BANK_CODE, 'DBL' BANK_CODE2, 'Defence Bank' BANK_NAME UNION ALL
SELECT '610019' BANK_CODE, 'BCY' BANK_CODE2, 'Delphi Bank' BANK_NAME UNION ALL
SELECT '610021' BANK_CODE, 'HBS' BANK_CODE2, 'Heritage Bank' BANK_NAME UNION ALL
SELECT '610023' BANK_CODE, 'HBA' BANK_CODE2, 'HSBC Bank Australia Limited' BANK_NAME UNION ALL
SELECT '610024' BANK_CODE, 'HUM' BANK_CODE2, 'Hume Bank' BANK_NAME UNION ALL
SELECT '610025' BANK_CODE, 'IMB' BANK_CODE2, 'IMB Bank' BANK_NAME UNION ALL
SELECT '610026' BANK_CODE, 'ING' BANK_CODE2, 'ING Direct Australia Bank' BANK_NAME UNION ALL
SELECT '610027' BANK_CODE, 'MBL' BANK_CODE2, 'Macquarie Bank Limited' BANK_NAME UNION ALL
SELECT '610028' BANK_CODE, 'MEB' BANK_CODE2, 'Members Equity Bank Pvt Limited' BANK_NAME UNION ALL
SELECT '610030' BANK_CODE, 'NAB' BANK_CODE2, 'National Australia Bank Limited' BANK_NAME UNION ALL
SELECT '610031' BANK_CODE, 'PNB' BANK_CODE2, 'P&N Bank' BANK_NAME UNION ALL
SELECT '610036' BANK_CODE, 'STG' BANK_CODE2, 'St. George Bank Limited (STG)' BANK_NAME UNION ALL
SELECT '610037' BANK_CODE, 'MET' BANK_CODE2, 'Suncorp-Metway Limited' BANK_NAME UNION ALL
SELECT '610038' BANK_CODE, 'TCU' BANK_CODE2, 'Teachers Mutual Bank Limited' BANK_NAME UNION ALL
SELECT '610041' BANK_CODE, 'WBC' BANK_CODE2, 'Westpac Banking Corporation' BANK_NAME UNION ALL
SELECT '610043' BANK_CODE, 'MPB' BANK_CODE2, 'Auswide Bank (MPB)' BANK_NAME UNION ALL
SELECT '610044' BANK_CODE, 'CNA' BANK_CODE2, 'Citibank Australia' BANK_NAME UNION ALL
SELECT '610045' BANK_CODE, 'APO' BANK_CODE2, 'Australia Post Money Orders' BANK_NAME UNION ALL
SELECT '610046' BANK_CODE, 'PIB' BANK_CODE2, 'Rabobank' BANK_NAME UNION ALL
SELECT '610047' BANK_CODE, 'BAE' BANK_CODE2, 'B And E Limited' BANK_NAME UNION ALL
SELECT '610048' BANK_CODE, 'BAL' BANK_CODE2, 'Bank of America National Association' BANK_NAME UNION ALL
SELECT '610050' BANK_CODE, 'COM' BANK_CODE2, 'Bank of Communications Co., Ltd Sydney Branch' BANK_NAME UNION ALL
SELECT '610051' BANK_CODE, 'LBA' BANK_CODE2, 'Bank of Sydney Ltd' BANK_NAME UNION ALL
SELECT '610053' BANK_CODE, 'BWA' BANK_CODE2, 'Bankwest' BANK_NAME UNION ALL
SELECT '610054' BANK_CODE, 'SKY' BANK_CODE2, 'Big Sky Building Society Limited' BANK_NAME UNION ALL
SELECT '610055' BANK_CODE, 'BNP' BANK_CODE2, 'BNP Paribas' BANK_NAME UNION ALL
SELECT '610056' BANK_CODE, 'BPS' BANK_CODE2, 'BNP Paribas Securities Services' BANK_NAME UNION ALL
SELECT '610057' BANK_CODE, 'CAP' BANK_CODE2, 'Capricornian Limited' BANK_NAME UNION ALL
SELECT '610058' BANK_CODE, 'CFC' BANK_CODE2, 'Community First Credit Union Limited' BANK_NAME UNION ALL
SELECT '610060' BANK_CODE, 'CUA' BANK_CODE2, 'Credit Union Australia Limited' BANK_NAME UNION ALL
SELECT '610061' BANK_CODE, 'CRU' BANK_CODE2, 'Cuscal Limited (CRU)' BANK_NAME UNION ALL
SELECT '610062' BANK_CODE, 'DBA' BANK_CODE2, 'Deutsche Bank Aktiengesellschaft' BANK_NAME UNION ALL
SELECT '610065' BANK_CODE, 'GCB' BANK_CODE2, 'G And C Mutual Bank' BANK_NAME UNION ALL
SELECT '610066' BANK_CODE, 'GTW' BANK_CODE2, 'Gateway Credit Union Limited' BANK_NAME UNION ALL
SELECT '610068' BANK_CODE, 'HIC' BANK_CODE2, 'Heritage Isle Credit Union Ltd' BANK_NAME UNION ALL
SELECT '610069' BANK_CODE, 'HCC' BANK_CODE2, 'Holiday Coast Credit Union Ltd' BANK_NAME UNION ALL
SELECT '610071' BANK_CODE, 'CUS' BANK_CODE2, 'Indue Ltd' BANK_NAME UNION ALL
SELECT '610072' BANK_CODE, 'IBK' BANK_CODE2, 'Industrial and Commercial Bank of China Limited' BANK_NAME UNION ALL
SELECT '610074' BANK_CODE, 'CMB' BANK_CODE2, 'JP Morgan Chase Bank, National Association' BANK_NAME UNION ALL
SELECT '610075' BANK_CODE, 'MMB' BANK_CODE2, 'Maitland Mutual Building Society Limited' BANK_NAME UNION ALL
SELECT '610078' BANK_CODE, 'ICB' BANK_CODE2, 'Mega International Commercial Bank Co Limited' BANK_NAME UNION ALL
SELECT '610079' BANK_CODE, 'MCB' BANK_CODE2, 'Mizuho Bank Limited' BANK_NAME UNION ALL
SELECT '610080' BANK_CODE, 'NEW' BANK_CODE2, 'Newcastle Permanent Building Society Ltd' BANK_NAME UNION ALL
SELECT '610083' BANK_CODE, 'RBA' BANK_CODE2, 'Reserve Bank of Australia' BANK_NAME UNION ALL
SELECT '610087' BANK_CODE, 'SNX' BANK_CODE2, 'Southern Cross Credit Union Ltd' BANK_NAME UNION ALL
SELECT '610088' BANK_CODE, 'SSB' BANK_CODE2, 'State Street Bank and Trust Company' BANK_NAME UNION ALL
SELECT '610089' BANK_CODE, 'SMB' BANK_CODE2, 'Sumitomo Mitsui Banking Corporation' BANK_NAME UNION ALL
SELECT '610090' BANK_CODE, 'SCU' BANK_CODE2, 'Summerland Credit Union Ltd' BANK_NAME UNION ALL
SELECT '610091' BANK_CODE, 'STH' BANK_CODE2, 'Sutherland Credit Union Ltd' BANK_NAME UNION ALL
SELECT '610092' BANK_CODE, 'TBB' BANK_CODE2, 'Taiwan Business Bank Sydney Branch' BANK_NAME UNION ALL
SELECT '610093' BANK_CODE, 'MSL' BANK_CODE2, 'Tyro Payments Limited' BANK_NAME UNION ALL
SELECT '610094' BANK_CODE, 'UBS' BANK_CODE2, 'UBS AG Australia Branch' BANK_NAME UNION ALL
SELECT '610095' BANK_CODE, 'UOB' BANK_CODE2, 'United Overseas Bank Limited' BANK_NAME UNION ALL
SELECT '610096' BANK_CODE, 'UFS' BANK_CODE2, 'Uniting Financial Services' BANK_NAME UNION ALL
SELECT '610097' BANK_CODE, 'WCU' BANK_CODE2, 'Warwick Credit Union Ltd' BANK_NAME UNION ALL
SELECT '610098' BANK_CODE, 'ADV' BANK_CODE2, 'Advance Bank' BANK_NAME UNION ALL
SELECT '610099' BANK_CODE, 'INV' BANK_CODE2, 'BOQ Specialist' BANK_NAME UNION ALL
SELECT '610100' BANK_CODE, 'CBL' BANK_CODE2, 'Challenge Bank' BANK_NAME UNION ALL
SELECT '610101' BANK_CODE, 'CCB' BANK_CODE2, 'China Construction Bank' BANK_NAME UNION ALL
SELECT '610102' BANK_CODE, 'OCB' BANK_CODE2, 'OCBC Bank' BANK_NAME UNION ALL
SELECT '610103' BANK_CODE, 'QTM' BANK_CODE2, 'RACQ Bank' BANK_NAME UNION ALL
SELECT '610104' BANK_CODE, 'RAB' BANK_CODE2, 'Regional Australia Bank' BANK_NAME UNION ALL
SELECT '610105' BANK_CODE, 'MMP' BANK_CODE2, 'Unity Bank' BANK_NAME UNION ALL
SELECT '610106' BANK_CODE, 'ANZ' BANK_CODE2, 'Town And Country Bank' BANK_NAME UNION ALL
SELECT '610107' BANK_CODE, 'BTA' BANK_CODE2, 'Bankers Trust Australia' BANK_NAME UNION ALL
SELECT '610108' BANK_CODE, 'BOT' BANK_CODE2, 'MUFG Bank' BANK_NAME UNION ALL
SELECT '610109' BANK_CODE, 'VOL' BANK_CODE2, 'Volt Bank' BANK_NAME UNION ALL
SELECT '610110' BANK_CODE, 'BCC' BANK_CODE2, 'Bananacoast' BANK_NAME UNION ALL
SELECT '610111' BANK_CODE, 'SEL' BANK_CODE2, 'Endeavour Mutual Bank' BANK_NAME UNION ALL
SELECT '610112' BANK_CODE, 'HOM' BANK_CODE2, 'Home Building Society' BANK_NAME UNION ALL
SELECT '610113' BANK_CODE, 'PPB' BANK_CODE2, 'Pioneer Permanent Building Society' BANK_NAME UNION ALL
SELECT '610114' BANK_CODE, 'QCB' BANK_CODE2, 'Queensland Country Credit Union' BANK_NAME UNION ALL
SELECT '610115' BANK_CODE, 'ROK' BANK_CODE2, 'The Rock' BANK_NAME UNION ALL
SELECT '610116' BANK_CODE, 'RCU' BANK_CODE2, 'MOVE' BANK_NAME
)x

DELETE b 
FROM #AustraliaBANK b
INNER JOIN dbo.API_BANK_LIST A ON A.BANK_CODE1=b.BANK_CODE

INSERT INTO API_BANK_LIST(API_PARTNER_ID,BANK_NAME,BANK_CODE1,BANK_STATE,BANK_DISTRICT,BANK_ADDRESS,BANK_PHONE
,BANK_EMAIL,BANK_COUNTRY,PAYMENT_TYPE_ID,IS_ACTIVE)
SELECT 394450, BANK_NAME, BANK_CODE, NULL, NULL, NULL, NULL, NULL, 'AUSTRALIA', 2, 1 FROM #AustraliaBANK
