---- State Code Of AUSTRALIA
IF OBJECT_ID('tempdb..#TempStateAUSTRALIA') IS NOT NULL
			DROP TABLE #TempStateAUSTRALIA
SELECT * INTO #TempStateAUSTRALIA FROM
(
	SELECT 'NEW SOUTH WALES ' STATE_NAME,'NSW' STATE_CODE UNION ALL
	SELECT 'QUEENSLAND' STATE_NAME,'QLD' STATE_CODE UNION ALL
	SELECT 'SOUTH AUSTRALIA' STATE_NAME,'SA' STATE_CODE UNION ALL
	SELECT 'TASMANIA' STATE_NAME,'TAS' STATE_CODE UNION ALL
	SELECT 'VICTORIA' STATE_NAME, 'VIC' STATE_CODE UNION ALL
	SELECT 'WESTERN AUSTRALIA' STATE_NAME ,'WA' STATE_CODE UNION ALL
	SELECT 'AUSTRALIA CAPITAL' STATE_NAME, 'ACT' STATE_CODE UNION ALL
	SELECT 'NORTHERN TERRITORY' STATE_NAME,'NT' STATE_CODE
)X

DELETE b 
FROM #TempStateAUSTRALIA b
INNER JOIN dbo.API_STATE_LIST A ON A.STATE_CODE=b.STATE_CODE

INSERT INTO API_STATE_LIST(API_PARTNER_ID,STATE_NAME,STATE_CODE,STATE_COUNTRY,PAYMENT_TYPE_ID,IS_ACTIVE)
SELECT 394450, STATE_NAME, STATE_CODE, 'AUSTRALIA', 0, 1 FROM #TempStateAUSTRALIA
