---- State Code Of AUSTRALIA
IF OBJECT_ID('tempdb..#TempStateAUSTRALIA') IS NOT NULL
			DROP TABLE #TempStateAUSTRALIA
SELECT * INTO #TempStateAUSTRALIA FROM
(
	SELECT 'NEW SOUTH WALES ' STATE_NAME,'NSW' STATE_CODE UNION ALL
	SELECT 'QUEENSLAND' STATE_NAME,'QLD' STATE_CODE UNION ALL
	SELECT 'SOUTH AUSTRALIA' STATE_NAME,'SA' STATE_CODE UNION ALL
	SELECT 'TASMANIA' STATE_NAME,'TAS' STATE_CODE UNION ALL
	SELECT 'VICTORIA' STATE_NAME, 'VIC' STATE_CODE UNION ALL
	SELECT 'WESTERN AUSTRALIA' STATE_NAME ,'WA' STATE_CODE UNION ALL
	SELECT 'AUSTRALIA CAPITAL' STATE_NAME, 'ACT' STATE_CODE UNION ALL
	SELECT 'NORTHERN TERRITORY' STATE_NAME,'NT' STATE_CODE
)X

DELETE b 
FROM #TempStateAUSTRALIA b
INNER JOIN dbo.tblServicewiseLocation A ON A.partnerLocationId=b.STATE_CODE

INSERT INTO tblServicewiseLocation(countryId,serviceTypeId,location,partnerLocationId,createdBy,createdDate,isActive,partnerId)
SELECT 12,1,STATE_NAME, STATE_CODE, 'admin',GETDATE(),1,394450 FROM #TempStateAUSTRALIA
