USE FastMoneyPro_Remit
GO

ALTER PROC PROC_CHECK_BRANCH_USER_CASH_HOLD_LIMIT
(
	@USER VARCHAR(50)
	,@CAMT MONEY
	,@ERRORCODE INT = NULL OUT
	,@ERRORMSG VARCHAR(250) = NULL OUT
	,@RULETYPE CHAR(1) = NULL OUT
)
AS;
SET NOCOUNT ON;
SET XACT_ABORT ON;
BEGIN
	DECLARE @AVAILABLELIMIT MONEY, @RULETYPEMAIN CHAR(1)
	SELECT @AVAILABLELIMIT = availableLimit, @RULETYPEMAIN = ruleType FROM [dbo].[FNAGetUserCashLimitDetails](@USER, NULL)
	
	IF @CAMT <= ISNULL(@AVAILABLELIMIT, 0)
		SELECT @ERRORCODE = 0, @ERRORMSG = 'Success', @RULETYPE = @RULETYPEMAIN
	ELSE 
		SELECT @ERRORCODE = 1, @ERRORMSG = 'Your cash hold limit exceeded!', @RULETYPE = @RULETYPEMAIN
END;
