

CREATE TABLE INCENTIVE_SETUP_REFERRAL_WISE
(
	REFERRAL_ID INT NOT NULL
	,PARTNER_ID INT NOT NULL
	,AGENT_ID INT NULL
	,COMM_PCNT DECIMAL(5,2) NULL
	,FX_PCNT DECIMAL(5,2) NULL
	,FLAT_TXN_WISE MONEY NULL
	,NEW_CUSTOMER MONEY NULL
);

CREATE INDEX INDEX_INCENTIVE_SETUP_REFERRAL_WISE
ON INCENTIVE_SETUP_REFERRAL_WISE (REFERRAL_ID);

INSERT INTO INCENTIVE_SETUP_REFERRAL_WISE
SELECT REFERRAL_ID = 2, PARTNER_ID = 394130, AGENT_ID = 0, COMM_PCNT = 25, FX_PCNT = 20, FLAT_TXN_WISE = 0, NEW_CUSTOMER = 300 UNION ALL
SELECT REFERRAL_ID = 2, PARTNER_ID = 394132, AGENT_ID = 0, COMM_PCNT = 30, FX_PCNT = 25, FLAT_TXN_WISE = 0, NEW_CUSTOMER = 300 UNION ALL
SELECT REFERRAL_ID = 2, PARTNER_ID = 393880, AGENT_ID = 0, COMM_PCNT = 35, FX_PCNT = 30, FLAT_TXN_WISE = 0, NEW_CUSTOMER = 300 


SELECT * FROM INCENTIVE_SETUP_REFERRAL_WISE WHERE PARENTID=0

alter table FASTMONEYPRO_REMIT.DBO.INCENTIVE_SETUP_REFERRAL_WISE add EFFECTIVE_FROM DATETIME, IS_ACTIVE BIT, CREATED_BY VARCHAR(80), CREATED_DATE DATETIME




