
SELECT * FROM FASTMONEYPRO_REMIT.DBO.REFERRAL_AGENT_WISE WHERE AGENT_ID <> 0
SELECT TOP 1* FROM VOUCHER_TRANSIT_CASH_MANAGE

INSERT INTO VOUCHER_TRANSIT_CASH_MANAGE
SELECT REFERRAL_CODE, ACCT_NUM, AMT, DT, NULL FROM #TEMP T
INNER JOIN FASTMONEYPRO_REMIT.DBO.REFERRAL_AGENT_WISE M ON M.REFERRAL_NAME = T.AGENT
INNER JOIN AC_MASTER A ON A.ACCT_NAME = M.REFERRAL_CODE AND A.AGENT_ID = M.ROW_ID

SELECT DISTINCT A.AGENTNAME FROM VOUCHER_TRANSIT_CASH_MANAGE T
INNER JOIN FASTMONEYPRO_REMIT.DBO.REFERRAL_AGENT_WISE M ON M.REFERRAL_CODE = T.REFERRAL_CODE 
INNER JOIN FASTMONEYPRO_REMIT.DBO.AGENTMASTER A ON A.AGENTID = M.BRANCH_ID
WHERE IS_GEN = 3

UPDATE T SET T.RECEIVER_ACC_NUM = CASE WHEN A.AGENTNAME = 'Tokyo Main-Head Office' THEN '100139292573'
																WHEN A.AGENTNAME = 'Fukuoka Branch' THEN '100139219838'
																WHEN A.AGENTNAME = 'Chiba Funabashi Branch' THEN '100139208487'
																WHEN A.AGENTNAME = 'Nagoya Branch' THEN '100139297551'
															END
FROM VOUCHER_TRANSIT_CASH_MANAGE T
INNER JOIN FASTMONEYPRO_REMIT.DBO.REFERRAL_AGENT_WISE M ON M.REFERRAL_CODE = T.REFERRAL_CODE 
INNER JOIN FASTMONEYPRO_REMIT.DBO.AGENTMASTER A ON A.AGENTID = M.BRANCH_ID
WHERE IS_GEN = 3


SELECT * FROM AC_MASTER WHERE ACCT_RPT_CODE = 'BVA'
 
 
 
