
SELECT REF_NUM, ACC_NUM, CAST(TRAN_DATE AS DATE) TRAN_DATE, TRAN_AMT INTO #TEMP FROM tran_master 
WHERE FIELD2 = 'Vault Transfer'
AND GL_SUB_HEAD_CODE = 0
AND CAST(CREATED_DATE AS DATE) = '2019-09-11'


SELECT v.* into #insertied FROM #TEMP T
INNER JOIN AC_MASTER A(nolock) ON A.ACCT_NUM = T.ACC_NUM
INNER JOIN FastMoneyPro_Remit.DBO.REFERRAL_AGENT_WISE R(nolock) ON A.ACCT_NAME = R.REFERRAL_CODE
INNER JOIN VOUCHER_TRANSIT_CASH_MANAGE V(nolock) ON V.AMOUNT = T.TRAN_AMT AND V.DT = T.TRAN_DATE AND V.REFERRAL_CODE = A.ACCT_NAME

select * from VOUCHER_TRANSIT_CASH_MANAGE t
left join #insertied i on i.tranid = t.tranid
where i.tranid is null

SELECT * FROM VOUCHER_TRANSIT_CASH_MANAGE WHERE AGENT_ID NOT IN (102, 87)

SELECT * FROM VOUCHER_TRANSIT_CASH_MANAGE V
INNER JOIN tran_master T ON T.acc_num = V.RECEIVER_ACC_NUM
WHERE CAST(T.CREATED_DATE AS DATE) = '2019-09-11'
AND FIELD2 = 'Vault Transfer'

SELECT MIN(REF_NUM), MAX(REF_NUM) FROM tran_master 
WHERE FIELD2 = 'Vault Transfer'
AND CAST(CREATED_DATE AS DATE) = '2019-09-11'


SELECT * FROM FASTMONEYPRO_REMIT.DBO.BRANCH_CASH_IN_OUT
WHERE HEAD = 'Transit Received'

SELECT COUNT(0) FROM tran_master 
WHERE FIELD2 = 'Vault Transfer'
AND CAST(CREATED_DATE AS DATE) = '2019-09-11'
AND  CAST(REF_NUM AS NUMERIC) BETWEEN 81561 AND 86581


SELECT COUNT(0) FROM tran_masterDETAIL
WHERE CAST(REF_NUM AS NUMERIC) BETWEEN 81561 AND 86581


SELECT * FROM FASTMONEYPRO_REMIT.DBO.BRANCH_CASH_IN_OUT
WHERE HEAD = 'Transit Received'

SELECT * FROM TRANSIT_CASH_SETTLEMENT
WHERE RECEIVING_ACCOUNT IS NOT NULL
AND CAST(CREATED_DATE AS DATE) = '2019-09-11'

SELECT * FROM FASTMONEYPRO_REMIT.DBO.AGENTMASTER WHERE PARENTID = 393877

